"""
Generate RLAIF pairs: Claude Sonnet self-corrects the same LLM outputs
that the practitioner edited. Creates Condition C for DPO experiment.

Writes checkpoint after EVERY item — safe to kill and resume.

Usage:
  cd rlhf-signals
  python3 training/generate_rlaif_pairs.py [--concurrency 3] [--limit 0]
"""

import json
import time
import argparse
import random
from pathlib import Path
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading

import boto3

BASE = Path(__file__).resolve().parent
DATA_DIR = BASE / "data"

MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
REGION = "us-east-1"

SYSTEM_PROMPT = """You are a careful editor. You will receive a text that was generated by an AI assistant. Your task is to edit this text to improve its quality.

Rules:
- Make whatever changes you think are needed: small fixes, restructuring, factual corrections, or substantial rewrites
- If the text is already good, make only minor improvements or return it as-is
- If the text is fundamentally flawed, rewrite it substantially
- Preserve the original intent and technical content
- Preserve all code fragments, variable names, file paths exactly
- Output ONLY the edited text, no preamble or explanation"""

SEED = 42
TRAIN_SPLIT = 0.9

write_lock = threading.Lock()


def create_client():
    return boto3.client("bedrock-runtime", region_name=REGION)


def generate_rlaif_edit(client, prompt: str, llm_output: str) -> str | None:
    user_message = f"Context/task:\n{prompt}\n\n---\n\nAI-generated text to edit:\n{llm_output}"
    try:
        response = client.converse(
            modelId=MODEL_ID,
            system=[{"text": SYSTEM_PROMPT}],
            messages=[{"role": "user", "content": [{"text": user_message}]}],
            inferenceConfig={"maxTokens": 4096, "temperature": 0.3},
        )
        return response["output"]["message"]["content"][0]["text"]
    except Exception as e:
        print(f"    API error: {e}")
        time.sleep(5)
        return None


def process_one(item, client, idx, total, checkpoint_path):
    prompt = item["prompt"]
    rejected = item["rejected"]

    rlaif_edit = generate_rlaif_edit(client, prompt, rejected)

    unchanged = not rlaif_edit or rlaif_edit.strip() == rejected.strip()
    result = {
        "prompt": prompt,
        "chosen": rlaif_edit or rejected,
        "rejected": rejected,
        "metadata": {
            **item.get("metadata", {}),
            "condition": "rlaif",
            "model": MODEL_ID,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            **({"unchanged": True} if unchanged else {}),
        },
    }

    with write_lock:
        with open(checkpoint_path, "a") as f:
            f.write(json.dumps(result, ensure_ascii=False) + "\n")

    if (idx + 1) % 50 == 0:
        print(f"  [{idx+1}/{total}] processed", flush=True)

    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--concurrency", type=int, default=3)
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    input_path = DATA_DIR / "full_with_metadata.jsonl"
    items = [json.loads(l) for l in input_path.read_text().splitlines()]

    if args.limit > 0:
        items = items[:args.limit]

    checkpoint_path = DATA_DIR / "rlaif_checkpoint.jsonl"
    completed = 0
    if checkpoint_path.exists():
        completed = sum(1 for _ in open(checkpoint_path))
        items = items[completed:]
        print(f"Resuming from checkpoint: {completed} done, {len(items)} remaining")

    total = len(items) + completed
    print(f"RLAIF generation: {len(items)} items, concurrency={args.concurrency}")
    print(f"Model: {MODEL_ID} ({REGION})")
    print(f"Checkpoint: {checkpoint_path}")
    print(flush=True)

    clients = [create_client() for _ in range(args.concurrency)]

    with ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        futures = {}
        for i, item in enumerate(items):
            idx = completed + i
            client = clients[i % args.concurrency]
            f = executor.submit(process_one, item, client, idx, total, checkpoint_path)
            futures[f] = idx

        errors = 0
        for f in as_completed(futures):
            try:
                f.result()
            except Exception as e:
                errors += 1
                print(f"  Error at idx {futures[f]}: {e}")

    # Read checkpoint and produce final files
    all_results = [json.loads(l) for l in checkpoint_path.read_text().splitlines()]
    print(f"\nDone. Total: {len(all_results)} RLAIF pairs, {errors} errors")

    unchanged = sum(1 for r in all_results if r.get("metadata", {}).get("unchanged"))
    print(f"  Unchanged: {unchanged} ({100*unchanged/len(all_results):.1f}%)")

    random.seed(SEED)
    shuffled = list(all_results)
    random.shuffle(shuffled)

    split_idx = int(len(shuffled) * TRAIN_SPLIT)
    train = shuffled[:split_idx]
    val = shuffled[split_idx:]

    for path, data in [(DATA_DIR / "rlaif_train.jsonl", train), (DATA_DIR / "rlaif_val.jsonl", val)]:
        with open(path, "w") as f:
            for pair in data:
                f.write(json.dumps({"prompt": pair["prompt"], "chosen": pair["chosen"], "rejected": pair["rejected"]}, ensure_ascii=False) + "\n")
        print(f"  Written: {path} ({len(data)} records)")

    checkpoint_path.unlink()
    print("Done.")


if __name__ == "__main__":
    main()
