export const PHASE4_CONTENT: Record<number, { lectureEn: string; practiceEn: string[] }> = {
  45: {
    lectureEn: `Your GitHub profile is the first thing a hiring manager opens after reading your resume. For AppSec roles, it carries even more weight than for general software engineering, because security work is inherently about showing your thought process -- how you investigate, what you notice, and how clearly you communicate findings. A scattered collection of half-finished repos with default READMEs tells a hiring manager you treat your work as throwaway. A curated set of 5-7 polished projects tells them you are someone who finishes what they start and takes pride in clarity. That distinction alone can determine whether you get the interview.

Start by auditing every public repository on your profile. Archive or make private anything that is incomplete, irrelevant, or embarrassing -- old tutorial forks, abandoned weekend experiments, repos with no README. What remains should tell a coherent story: "This person transitioned from QA into AppSec, and here is the proof." The ideal pinned set includes at least one original security tool (even a small one, like your TLS checker from week 7 or a custom Semgrep rule pack), one vulnerability research write-up with a clear PoC, one CTF solution with detailed methodology, and one contribution to an open-source security project. Each of these demonstrates a different facet of the skillset hiring managers look for.

README quality is non-negotiable. Every pinned repo needs a README that answers four questions in under 60 seconds of reading: What does this project do? Why does it matter? How do I run it? What did you learn? Use a consistent structure across all repos: a one-sentence summary at the top, a screenshot or terminal recording (asciinema or a GIF via Terminalizer), an installation section, a usage section, and a "Background / What I learned" section. Do not write a wall of text -- use bullet points, code blocks, and headers. If the project involves a vulnerability, include a sanitized reproduction section that shows you understand responsible disclosure.

Profile-level polish matters too. Write a profile README (the special repo named after your GitHub username) with a brief professional summary, your key skills, and links to your blog and LinkedIn. Use GitHub's pinning feature to surface your best 6 repositories. Make sure your profile photo is professional, your bio mentions "AppSec" or "Application Security," and your contribution graph shows recent activity. Hiring managers do check the graph -- not for volume, but for consistency. A steady pattern of commits over the last few months signals genuine engagement, not a last-minute portfolio rush.

Finally, think about the demo experience. For tools and scripts, include a GIF or video showing the tool in action. For write-ups, include a table of contents so readers can jump to the interesting parts. For CTF solutions, structure them as a narrative: what you tried first, what failed, what insight led to the breakthrough. The goal is to make it effortless for a reviewer to understand your work in under two minutes. Hiring managers review dozens of candidates -- make their job easy and they will remember you.`,
    practiceEn: [
      'Audit all public repositories: archive or make private anything incomplete, irrelevant, or without a README. Aim to keep only 8-12 public repos total, with 5-7 being showcase quality.',
      'Write or rewrite the README for each pinned repository using this structure: one-line summary, screenshot/GIF, installation, usage, "What I learned" section. Use asciinema (asciinema.org) or Terminalizer to record terminal demos for CLI tools.',
      'Create a profile README (repository named your-username/your-username) with a professional summary, tech stack badges, links to your blog and LinkedIn, and a brief "Currently focused on" section mentioning AppSec.',
      'Pin 6 repositories that tell your career story: 1 security tool you built, 1 vulnerability write-up, 1 CTF solution, 1 open-source contribution, 1 security pipeline/automation project, and 1 project from your QA background that shows transferable skills.',
      'Record a 2-3 minute Loom or OBS Studio video walking through your best project -- explain the problem, your approach, and the result. Embed the link in the README. This single artifact differentiates you from 90% of candidates.',
      'Review your profile as a stranger would: open it in an incognito browser, spend exactly 60 seconds, and note your first impressions. Fix anything that looks unfinished or confusing.'
    ],
  },
  46: {
    lectureEn: `Publishing technical content is the single highest-leverage activity for career switching into security. A well-written blog post about a vulnerability you analyzed or a tool you built does three things simultaneously: it forces you to understand the topic deeply enough to explain it, it creates a permanent searchable artifact that recruiters and hiring managers find, and it positions you as someone who contributes to the community rather than just consuming content. Many AppSec engineers got their first role because someone on the hiring committee had read their blog. This is not theoretical -- it is the most common "how did you get into security" story in the industry.

Choose your platform based on your goals. Hashnode gives you a custom domain for free, renders Markdown well, and has a built-in developer audience. Medium has broader reach but paywalls annoy readers and the editor can mangle code blocks. GitHub Pages with Hugo or Jekyll gives you complete control and shows additional technical skills, but takes longer to set up. For someone transitioning careers, Hashnode is the best balance of effort and reach. Set up your blog with a clean theme, a proper "About" page that mentions your QA-to-AppSec journey, and an RSS feed. Then commit to publishing at least two posts in this first week.

The structure of a good technical security post follows a predictable pattern that readers expect. Start with a hook -- a concrete scenario or question that makes the reader care. "Last week I found that a popular Express.js middleware leaks session tokens in error responses" is a hook. "In this blog post I will discuss XSS" is not. After the hook, provide enough background context that a mid-level developer can follow along (your audience is developers, not security researchers). Then walk through the technical details with code snippets, screenshots, or terminal output at every step. End with concrete takeaways: what should the reader do differently after reading this? A post without actionable conclusions is a post that gets forgotten.

For your first two posts, pick topics where you already have the material. Your strongest CVE analysis from week 38-39 can become "How CVE-XXXX-YYYY Works: A Line-by-Line Analysis of the Patch." Your Semgrep rules from week 33 can become "Writing Custom Semgrep Rules to Catch Auth Bypass in Express.js." Your bug bounty experience from week 40, even if the report was informational, can become "What I Learned From My First Bug Bounty Report." Repackage work you have already done -- do not start from scratch.

SEO for technical writers is simpler than general SEO but still matters. Use a specific, searchable title -- "SQL Injection in Django ORM: How filter() Can Still Be Vulnerable" will rank; "My Thoughts on SQL Injection" will not. Include the vulnerability name, the technology, and ideally the CVE number in the title and first paragraph. Use H2 and H3 headers that match search queries. Add alt text to images. Link to authoritative sources (OWASP, PortSwigger, NVD). Cross-post a summary on LinkedIn and Twitter with a link back to your blog. Share in relevant communities: the OWASP Slack, the tl;dr sec newsletter submission form, and relevant subreddits. One well-distributed post reaches more people than ten posts nobody sees.`,
    practiceEn: [
      'Set up a blog on Hashnode (hashnode.com): choose a custom subdomain, configure your "About" page with your QA-to-AppSec narrative, enable RSS, and select a clean theme. Total setup time should be under 30 minutes.',
      'Write and publish your first post: a CVE analysis or vulnerability write-up from your training. Structure it as: hook (1 paragraph), background context (2-3 paragraphs), technical walkthrough with code/screenshots (4-6 paragraphs), and takeaways (2-3 bullet points). Aim for 1200-1800 words.',
      'Write and publish your second post: a tool walkthrough or technique explanation. For example, "Building a Security Pipeline with Semgrep, gitleaks, and GitHub Actions" or "How I Found 5 Vulnerabilities in OWASP crAPI." Include working code snippets the reader can copy.',
      'Optimize both posts for search: ensure titles contain the specific technology and vulnerability type, add alt text to all images, use H2/H3 headers that match search queries, and link to at least 3 authoritative external sources per post.',
      'Distribute your posts: share each on LinkedIn with a 3-4 sentence summary and the link, post in the OWASP Slack #blog-posts channel, submit to tl;dr sec newsletter (tldrsec.com/contribute), and share on Twitter/X tagging relevant accounts (@PortSwigger, @OWASPFoundation).',
      'Set a recurring calendar reminder to publish one post every two weeks going forward. Create a backlog of 5-6 topic ideas drawn from your training artifacts so you never face a blank page.'
    ],
  },
  47: {
    lectureEn: `Your resume needs to tell one story: "I was a strong QA automation engineer, and I systematically acquired AppSec skills that make me ready for a security role." The biggest mistake career switchers make is hiding their QA experience or treating it as irrelevant. It is not. QA automation engineers who move into AppSec bring three things that pure security candidates often lack: deep familiarity with CI/CD pipelines (which is where security tooling lives), a testing mindset that naturally maps to adversarial thinking, and experience working embedded in development teams (which is exactly what AppSec engineers do). Your resume should make these connections explicit.

Structure your resume in this order: a 3-line professional summary at the top, then a "Security Skills" section, then "Experience" (with security-relevant bullets first), then "Projects & Publications" (linking to your GitHub and blog), then "Certifications," then "Education." The professional summary should read something like: "Application Security Engineer with a foundation in QA automation. Experienced in SAST/DAST pipeline integration, secure code review, and web vulnerability assessment. BSCP certified. Built and maintained CI/CD security tooling for X years of development experience." Notice: security first, QA experience as the foundation that supports it.

In your experience section, rewrite your QA bullets to emphasize security-adjacent work. "Wrote API tests for 50 endpoints" becomes "Tested 50 API endpoints for input validation, authentication bypass, and authorization flaws, identifying 12 security-relevant defects before production." "Set up CI/CD pipelines" becomes "Designed and maintained CI/CD pipelines integrating automated security checks including SAST scanning and dependency vulnerability analysis." "Performed regression testing" becomes "Conducted regression testing with focus on authentication flows, session management, and access control boundaries." You are not lying -- you are reframing the same work through a security lens, which is genuinely how it should be described for security roles.

LinkedIn optimization follows different rules than your resume. Your headline should not say "QA Engineer looking for AppSec role" -- it should say "Application Security Engineer | BSCP | Secure Code Review | SAST/DAST." Use the headline to state what you are, not what you want to be. Your About section should be a narrative version of your professional summary, written in first person, ending with what you are looking for. Turn on "Open to Work" but set it to visible only to recruiters. Join and engage in LinkedIn groups: OWASP, Application Security, DevSecOps. Comment substantively on posts by security leaders -- not "Great post!" but actual technical additions. This builds visibility with the people who make hiring decisions.

Networking is where most career switchers underperform because it feels uncomfortable. Start with structured environments: attend your local OWASP chapter meeting (find it at owasp.org/chapters), join a DEF CON local group (defcongroups.org), participate in security-focused Discord servers (like the PortSwigger or HackTheBox communities). At these events, your QA background is a conversation starter, not a liability -- say "I am transitioning from QA automation into AppSec and I am here to learn." People in security communities are overwhelmingly welcoming to career switchers who show genuine effort. For cold outreach to hiring managers, send a LinkedIn message that references something specific: their company's recent security blog post, a talk they gave, or a tool they maintain. Attach your best blog post. Keep it to 3 sentences. The response rate on personalized outreach is 10-15x higher than generic messages.`,
    practiceEn: [
      'Rewrite your resume from scratch using the security-first structure: professional summary (3 lines), Security Skills section (tools, methodologies, certifications), Experience (reframe every bullet through a security lens), Projects & Publications (with links), Certifications, Education. Keep it to 2 pages maximum.',
      'Reframe your top 8-10 QA experience bullets to emphasize security relevance. For each bullet, ask: "What security risk did this work address or could it have addressed?" Use verbs like "assessed," "identified," "mitigated," "secured," "audited" instead of "tested," "verified," "automated."',
      'Update your LinkedIn: change your headline to state your target role (not "seeking"), rewrite your About section as a first-person narrative, add all security certifications and training, list relevant skills (OWASP Top 10, Burp Suite, Semgrep, Threat Modeling, Secure Code Review), and request endorsements from colleagues.',
      'Send 5 personalized connection requests or messages to people at companies where you want to work. Each message should reference something specific about the recipient or their company and include a link to your best blog post or GitHub project. Template: "[Name], I read your post on [topic] and it helped me with [specific thing]. I am transitioning from QA automation into AppSec and recently wrote about [your topic]. Would love to connect."',
      'Register for your nearest OWASP chapter meeting (owasp.org/chapters) or a security meetup on Meetup.com. If none exist locally, join the OWASP Slack (owasp.org/slack/invite) and introduce yourself in the #career-advice channel. Attend at least one event this week.',
      'Create a target list of 15-20 companies you want to work at, with the name of their security team lead or hiring manager. Use LinkedIn to find these people. This list becomes your focused outreach target for the coming weeks.'
    ],
  },
  48: {
    lectureEn: `AppSec interviews typically consist of four to five distinct sections, and understanding the format in advance is the difference between performing at your actual skill level and underperforming due to surprise. The most common structure is: a web vulnerabilities deep-dive (30-45 minutes), a threat modeling exercise (30-45 minutes), a live code review (30-45 minutes), a system design discussion with security focus (30 minutes), and behavioral questions (30 minutes). Not every company runs all five, but preparing for all five means you are ready for any combination. Let us break down what each section actually tests and how to prepare.

The web vulnerabilities deep-dive is usually a conversation, not a quiz. The interviewer describes a scenario -- "You are testing an e-commerce application, walk me through your approach" -- and expects you to think out loud. They want to hear you prioritize: you would start with authentication and session management, check for IDOR on order/user endpoints, test payment flows for race conditions, look for stored XSS in product reviews, check CSRF protections on state-changing operations, and examine the API for mass assignment. For each vulnerability you mention, they will go deeper: "How would you test for blind SQL injection here?" or "What is the difference between reflected and DOM-based XSS in this context?" The key is structured thinking. Do not shotgun random vulnerability names -- walk through the application methodically, component by component. Your QA background is actually an advantage here because you already think in terms of test cases and edge cases.

The threat modeling exercise presents you with an architecture diagram -- typically a microservices system with a database, cache, external API, authentication service, and a frontend. You are asked to identify threats, usually using STRIDE. What matters is not naming every possible threat but demonstrating a systematic approach: identify trust boundaries, trace data flows, and for each component ask "What could go wrong with Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege?" Interviewers look for whether you catch the non-obvious issues: the internal service-to-service communication that lacks authentication, the logging system that might capture sensitive data, the cache that could serve stale authorization decisions, the message queue where message ordering matters for security.

Live code review is where your training pays off most directly. You will receive 100-300 lines of code in Python, JavaScript, Java, or Go and have 20-30 minutes to find security issues. The code will contain 3-5 planted vulnerabilities of varying severity. Approach it systematically: first scan for dangerous functions (eval, exec, system, raw SQL concatenation, innerHTML), then trace user input from entry points through the code (where does request.body end up?), then check authentication and authorization logic (is there a middleware? is it applied to all routes?), then look for cryptographic issues (hardcoded keys, weak algorithms, missing HTTPS). Do not try to find everything -- find the critical and high severity issues first and explain clearly why they matter. Interviewers care more about your explanation quality than the quantity of findings. When you find an issue, state: what the vulnerability is, where it is in the code, what the impact is, and how to fix it.

Behavioral questions in AppSec interviews focus on collaboration and communication, because the biggest challenge of the job is working with development teams who may see security as a blocker. Prepare stories using the STAR format (Situation, Task, Action, Result) for these specific scenarios: a time you convinced a team to fix a security issue they wanted to ignore, a time you had to balance security with a tight deadline, a time you found a bug that was hard to reproduce, how you handle pushback on security recommendations, and how you stay current with new vulnerabilities and attack techniques. For the last one, mention specific sources: tl;dr sec newsletter, PortSwigger research blog, Project Zero blog, OWASP chapter meetings. Interviewers want to see that you have a learning system, not just a list of bookmarks.`,
    practiceEn: [
      'Conduct a mock web vulnerability deep-dive: ask a friend or use an AI assistant to play the interviewer role with the prompt "You are testing a multi-tenant SaaS application with an API, OAuth login, file upload, and a billing system. Walk me through your security testing approach." Practice thinking out loud for 30 minutes, covering at least 8 distinct vulnerability categories with specific test cases for each.',
      'Practice a threat modeling exercise: draw a system architecture diagram for a ride-sharing application (mobile app, API gateway, auth service, payment service, driver matching service, PostgreSQL, Redis, S3). Apply STRIDE to each component and each data flow. Write down at least 15 specific threats with their severity and proposed mitigations. Time yourself -- you should complete this in 30 minutes.',
      'Complete a timed code review exercise: find a deliberately vulnerable application on GitHub (OWASP WebGoat source code, Damn Vulnerable Web Application source, or NodeGoat) and review 200 lines of code in 20 minutes. Document each finding in this format: file:line, vulnerability type, severity, impact statement, fix recommendation. Aim to find at least 4 issues.',
      'Prepare 5 STAR-format behavioral answers: (1) a time you identified a quality/security issue others missed, (2) a time you balanced thoroughness with deadline pressure, (3) how you give constructive feedback to developers, (4) how you handle disagreements about risk severity, (5) your system for staying current with security research. Write each answer in 150-200 words and practice delivering them in under 2 minutes.',
      'Run a full mock interview end-to-end: schedule 2 hours with a peer, mentor, or use Pramp (pramp.com). Cover all five sections in sequence with realistic time pressure. Record the session if possible and review it afterward, noting where you hesitated, rambled, or missed key points.',
      'Create a personal "cheat sheet" of the top 30 things you want to remember going into an interview: 10 vulnerability types with one-sentence explanations and fix patterns, 10 security tools with their purpose and one command you know by heart, 5 architecture security patterns (zero trust, defense in depth, least privilege, fail secure, separation of duties), and 5 industry frameworks/standards (OWASP Top 10, OWASP ASVS, NIST CSF, STRIDE, SLSA). Review this sheet the morning of every interview.'
    ],
  },
};
