export const PHASE3_CONTENT: Record<number, { lectureEn: string; practiceEn: string[] }> = {
  29: {
    lectureEn: `The Secure Software Development Lifecycle (SSDLC) is the backbone of any Application Security program. Unlike bolting security on at the end -- the old "pentest before release" model -- a mature SSDLC weaves security into every phase: requirements gathering, design, implementation, testing, deployment, and operations. As a QA engineer transitioning into AppSec, you already understand the value of catching bugs early. The same economic logic applies to security: a vulnerability found during design review costs orders of magnitude less to fix than one discovered in production through a breach. The shift-left philosophy means moving security activities earlier in the pipeline -- threat modeling during design, secure coding standards during implementation, SAST during code review. Shift-right complements this by adding runtime protections, monitoring, and incident response capabilities.

Your role as an AppSec engineer is fundamentally different from that of a penetration tester or a SOC analyst. You are an enabler, not a gatekeeper. The moment you become the person who blocks every release with a list of "must-fix" findings, you lose developer trust and become a bottleneck that teams route around. Instead, your job is to build security into the development process so that secure code is the path of least resistance. This means creating secure defaults in frameworks, writing reusable libraries for common security tasks (input validation, authentication wrappers, encryption utilities), and providing developers with self-service security tools they can run before they even open a pull request.

Security champions are your force multiplier. In any organization with more than a handful of development teams, you cannot personally review every design document and every pull request. A security champion program identifies one developer per team who receives additional security training, acts as the first point of contact for security questions, and helps triage SAST findings. Champions are not security experts -- they are developers who care about security and serve as a bridge between the AppSec team and their peers. Successful champion programs give participants recognition (titles, conference budgets), regular training sessions (monthly lunch-and-learn), and a direct communication channel to the security team.

Measuring an AppSec program is notoriously difficult, but metrics matter because they drive investment and demonstrate progress. Avoid vanity metrics like "total vulnerabilities found" -- a number that can be inflated by scanner noise. Instead, focus on actionable metrics: mean time to remediate (MTTR) by severity, percentage of projects with completed threat models, SAST coverage (percentage of repositories with scanners enabled), vulnerability escape rate (how many vulns reach production), and developer satisfaction scores from security tooling surveys. Track trends over quarters, not absolute numbers. A decreasing MTTR and a declining escape rate tell a compelling story to leadership, even if the raw vulnerability count is rising because you deployed better scanners.

Finally, understand where you fit in compliance and governance frameworks. SOC 2, ISO 27001, PCI DSS, and NIST CSF all have controls that map directly to SSDLC activities. Your threat models satisfy "risk assessment" controls. Your SAST pipeline satisfies "secure development" controls. Your vulnerability management process satisfies "remediation" controls. Learning to speak the language of compliance -- mapping technical activities to control frameworks -- makes you invaluable to the organization and ensures your AppSec program gets the budget it needs.`,
    practiceEn: [
      'Map out the current SDLC at your organization (or a hypothetical one). For each phase (requirements, design, code, test, deploy, operate), list what security activities should occur and who is responsible. Identify the gaps.',
      'Draft a one-page "Security Champion Program" proposal. Define the selection criteria, responsibilities, training plan (monthly topics for 6 months), recognition mechanisms, and escalation paths.',
      'Create a metrics dashboard mockup (spreadsheet or diagram) tracking: MTTR by severity, SAST coverage percentage, threat model completion rate, and vulnerability escape rate. Populate it with realistic sample data for a 12-month period.',
      'Write a "Developer Security Handbook" outline (table of contents with brief descriptions) covering: secure coding standards for your primary language, how to use the SAST tool, how to request a security review, and how to handle a security incident.',
      'Take one compliance framework (SOC 2 Type II or ISO 27001 Annex A) and map at least 10 controls to specific SSDLC activities. For each control, note what evidence artifact your AppSec program would produce.',
    ],
  },

  30: {
    lectureEn: `Threat modeling is the most impactful security activity you can perform, and STRIDE is the most widely adopted framework for doing it. Developed at Microsoft in the 1990s, STRIDE stands for Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege. Each category maps to a security property: Spoofing violates authentication, Tampering violates integrity, Repudiation violates non-repudiation, Information Disclosure violates confidentiality, Denial of Service violates availability, and Elevation of Privilege violates authorization. The power of STRIDE is that it gives you a systematic checklist to apply against every component of a system, ensuring you do not rely solely on intuition or experience to find threats.

The foundation of any STRIDE analysis is a Data Flow Diagram (DFD). A DFD is not a network diagram or an architecture diagram -- it specifically shows how data moves through a system. It uses four elements: external entities (users, third-party APIs), processes (your application code), data stores (databases, file systems, caches), and data flows (arrows showing data movement). You draw trust boundaries -- dashed lines that separate zones of different trust levels. The classic trust boundaries are: the internet vs. your DMZ, your DMZ vs. your internal network, your application vs. the database, and the client browser vs. the server. Every data flow that crosses a trust boundary is a potential attack surface. STRIDE threats are most likely to manifest at these boundary crossings.

Working through a STRIDE analysis is methodical. For each element in your DFD, you ask: Can this be spoofed? Can the data be tampered with? Can actions be repudiated? Can information leak? Can it be denied service? Can privileges be elevated? Not every STRIDE category applies to every element type -- for example, data stores cannot be spoofed (they do not have identity), but they are prime targets for tampering and information disclosure. Processes are vulnerable to all six categories. Data flows are primarily vulnerable to tampering and information disclosure. External entities are primarily targets for spoofing. Microsoft published a threat-per-element matrix that guides you on which categories to consider for each DFD element type.

Tooling can accelerate threat modeling significantly. The Microsoft Threat Modeling Tool is free and produces DFDs with automatic STRIDE threat generation based on element types and trust boundaries. OWASP Threat Dragon is an open-source alternative that runs in the browser and integrates with GitHub. Both tools generate threat lists that you then triage: for each generated threat, you assess whether it is applicable, what mitigations exist, and what the residual risk is. The output is a threat model document that becomes a living artifact -- updated when the architecture changes, reviewed during design reviews, and referenced during security testing to ensure coverage of identified threats.

A common mistake is treating threat modeling as a one-time ceremony performed only for new systems. In practice, threat models should be updated whenever significant architectural changes occur: adding a new microservice, integrating a third-party API, changing authentication mechanisms, or migrating to a new cloud provider. Incremental threat modeling -- focusing only on the changed components -- keeps the practice sustainable. Another mistake is producing threat models that are too abstract to be actionable. Each identified threat should have a concrete attack scenario ("an attacker who compromises the Redis cache can read session tokens and impersonate any user") and a specific mitigation ("encrypt session data at rest in Redis using AES-256, rotate encryption keys monthly").`,
    practiceEn: [
      'Install OWASP Threat Dragon or the Microsoft Threat Modeling Tool. Create a DFD for a typical web application with: browser client, load balancer, API server, database, Redis cache, and a third-party payment API. Draw all trust boundaries.',
      'Apply STRIDE to your DFD. For each element that crosses a trust boundary, enumerate at least one threat per applicable STRIDE category. Write each threat as a concrete attack scenario, not an abstract statement.',
      'For each threat identified, document a mitigation. Categorize mitigations as: already implemented, planned, accepted risk, or transferred (e.g., handled by cloud provider). Justify each "accepted risk" decision.',
      '★ Take a real-world breach report (e.g., Capital One 2019, SolarWinds 2020) and reverse-engineer the DFD of the affected system. Identify which trust boundary was violated and which STRIDE categories the attack exploited.',
      'Practice presenting a threat model to a non-security audience. Write a one-page executive summary of your threat model with: system description, top 5 risks ranked by severity, recommended mitigations, and resource requirements.',
    ],
  },

  31: {
    lectureEn: `While STRIDE is a threat-centric framework -- it starts with what can go wrong -- PASTA (Process for Attack Simulation and Threat Analysis) is a risk-centric framework that starts with business objectives and works down to technical threats. PASTA has seven stages: (1) Define Objectives, (2) Define Technical Scope, (3) Application Decomposition, (4) Threat Analysis, (5) Vulnerability Analysis, (6) Attack Modeling, and (7) Risk and Impact Analysis. The key differentiator is that PASTA explicitly connects threats to business impact and likelihood, producing risk scores that help prioritize remediation. This makes PASTA particularly valuable when you need to justify security investments to business stakeholders who care about ROI, not CVSS scores.

In PASTA's first three stages, you establish context. You identify the business objectives the application serves (e.g., "process $50M in annual payments"), the regulatory requirements it must meet (PCI DSS, GDPR), and the technical architecture. Stage 4 (Threat Analysis) leverages threat intelligence -- who are the likely attackers, what are their capabilities and motivations? A financial application faces different threat actors than an internal HR tool. Stage 5 maps known vulnerabilities to the architecture using CVE databases and vulnerability scan results. Stage 6 is where PASTA shines: you build attack trees that model how an attacker would chain vulnerabilities to achieve their objectives. Stage 7 combines likelihood and impact to produce prioritized risk ratings.

Attack trees are a complementary modeling technique that works well with both STRIDE and PASTA. An attack tree has a root node representing the attacker's goal (e.g., "steal customer credit card data") and branches representing different paths to achieve that goal. Each branch can be decomposed into sub-goals with AND/OR relationships. An AND node means all child conditions must be true for the attack to succeed; an OR node means any single child path suffices. Leaf nodes are atomic attack steps (e.g., "exploit SQL injection in search endpoint," "compromise admin credentials via phishing"). Attack trees help you identify the cheapest or most likely attack path, which should receive the highest priority for mitigation. You can annotate nodes with cost, difficulty, and detectability to create a quantitative risk model.

MITRE ATT&CK is an invaluable reference when building threat models and attack trees. ATT&CK catalogs real-world adversary tactics, techniques, and procedures (TTPs) observed in actual attacks. It is organized by platform (Enterprise, Mobile, ICS) and covers the full attack lifecycle from Initial Access through Exfiltration and Impact. When threat modeling, you can use ATT&CK to ensure your attack trees reflect realistic adversary behavior rather than theoretical attacks. For example, if you are modeling threats to a cloud-hosted application, ATT&CK's Cloud Matrix shows specific techniques like "Cloud Instance Metadata API" abuse (T1552.005), which led to the Capital One breach. Using ATT&CK makes your threat models more credible and actionable.

LINDDUN is a privacy-specific threat modeling framework that complements STRIDE. While STRIDE focuses on security properties (confidentiality, integrity, availability), LINDDUN focuses on privacy properties: Linkability, Identifiability, Non-repudiation (as a privacy risk -- sometimes you want repudiation), Detectability, Disclosure of information, Unawareness, and Non-compliance. In an era of GDPR, CCPA, and increasing privacy regulation, understanding privacy threats is essential for AppSec engineers. For example, LINDDUN would flag that storing user search queries linked to user IDs creates a linkability threat even if the data is encrypted at rest -- an attacker or insider who accesses the data can build behavioral profiles. STRIDE alone would not surface this privacy-specific risk.`,
    practiceEn: [
      '★ Choose a web application you know well and perform a PASTA analysis through all seven stages. For stages 1-3, document business objectives, compliance requirements, and create an application decomposition. For stages 4-7, identify at least three threat actors, map vulnerabilities, build attack trees, and calculate risk scores.',
      'Build an attack tree for the goal "exfiltrate customer PII from a SaaS application." Include at least three distinct attack paths with AND/OR nodes. Annotate leaf nodes with estimated difficulty (low/medium/high) and detectability (low/medium/high). Identify the most likely attack path.',
      '★ Using MITRE ATT&CK Navigator, create a heat map of techniques relevant to your application. Select at least 15 techniques from Initial Access through Exfiltration that apply to your threat model. For each, note whether you have detection or prevention controls in place.',
      'Perform a LINDDUN analysis on a user registration and login flow. Identify at least one threat per LINDDUN category. For each threat, propose a privacy-enhancing technology (PET) or design change as mitigation.',
      'Compare the outputs of STRIDE and PASTA applied to the same system. Write a one-page analysis of which threats each framework surfaced that the other missed, and recommend when to use each framework.',
      'Create a threat library -- a reusable catalog of 10 common threats with descriptions, attack scenarios, STRIDE/PASTA classifications, MITRE ATT&CK mappings, and standard mitigations. Format it so it can be reused across future threat models.',
    ],
  },

  32: {
    lectureEn: `Architecture review is where an AppSec engineer adds the most value per hour invested. A single design flaw -- storing secrets in client-side code, trusting user-supplied JWTs without validation, or using a shared database account for all microservices -- can undermine months of secure coding effort. Unlike code-level vulnerabilities that affect individual endpoints, architectural issues create systemic risk across the entire application. Your goal during an architecture review is to find these design-level problems before a single line of code is written, when the cost of change is lowest.

Reading architecture diagrams is a learned skill. You will encounter C4 model diagrams (Context, Container, Component, Code), UML sequence diagrams, cloud architecture diagrams (AWS/Azure/GCP), and informal whiteboard sketches. Regardless of format, you should extract the same information: What are the components? How do they communicate (synchronous HTTP, async message queue, gRPC)? Where is data stored and how does it flow? What are the trust boundaries? Who authenticates to whom? Where are secrets stored and how are they distributed? A useful technique is to mentally trace a user request from the browser through every component it touches, asking at each hop: "What could go wrong here?" Pay special attention to authentication and authorization boundaries -- the most common architectural flaw is inconsistent enforcement, where some services check permissions and others trust upstream assertions.

The most common architectural security issues follow predictable patterns. Insecure data flow: sensitive data traveling over unencrypted channels between internal services ("it's inside our VPC, so TLS isn't needed" -- until an attacker pivots into the VPC). Excessive trust: a frontend directly calling a database or an internal service accepting unauthenticated requests because "only our API gateway calls it." Insufficient isolation: multiple tenants sharing a database without row-level security, or running untrusted user code in the same process as privileged operations. Missing rate limiting: APIs that can be abused for credential stuffing, data scraping, or denial of service. Single points of failure in security controls: relying on a single API gateway for all authentication means compromising the gateway compromises everything.

Soft skills are critical for architecture reviews. Developers and architects invest significant effort in their designs, and a review that feels like an attack on their work will be met with defensiveness. Frame findings as risks, not mistakes. Instead of "this design is insecure because you're not using TLS between services," say "there's a risk of data interception if an attacker gains access to the internal network -- adding mTLS between services would mitigate this, and here's a library that makes it straightforward." Offer solutions, not just problems. When you suggest a change, quantify the effort and offer to help implement it. Ask questions before making assertions -- "how does service B verify that requests are coming from service A?" often leads the architect to realize the gap themselves.

Risk acceptance is a legitimate outcome of an architecture review. Not every finding needs to be fixed. The key is that risk acceptance must be informed, documented, and approved by someone with authority. A documented risk acceptance should include: what the risk is, what the potential impact is, why the team is accepting it (cost, timeline, low likelihood), what compensating controls exist, and when it will be reassessed. As an AppSec engineer, your job is to ensure that risk acceptance decisions are made with full information, not to unilaterally decide what must be fixed. Build a risk register that tracks accepted risks and schedule periodic reviews -- a risk accepted in 2024 may no longer be acceptable in 2025 as the threat landscape evolves.`,
    practiceEn: [
      'Find an open-source project with published architecture documentation (e.g., GitLab, Bitwarden, or any CNCF project). Review their architecture diagram and identify at least five security concerns. Write each as a risk statement: "If [threat], then [impact], because [architectural weakness]."',
      'Create a security architecture review checklist with at least 20 items organized by category: authentication, authorization, data protection, network security, secrets management, logging, error handling, and third-party integrations. Use this checklist against the architecture you reviewed.',
      'Practice the soft skills component: take one of your findings and write it up in two styles -- (a) a blunt "this is wrong" statement and (b) a collaborative risk-framed recommendation with a proposed solution and effort estimate. Reflect on which would be more effective.',
      'Draft a risk acceptance template with fields for: risk ID, description, CVSS or qualitative severity, affected components, business justification for acceptance, compensating controls, risk owner (name and role), acceptance date, and reassessment date.',
      '★ Trace a complete authentication flow through a multi-service architecture (use any microservices reference architecture). Document every point where identity is asserted, verified, or assumed. Identify any gaps where a compromised service could impersonate another.',
    ],
  },

  33: {
    lectureEn: `Static Application Security Testing (SAST) analyzes source code without executing it, finding vulnerabilities at the earliest possible stage -- before the code even reaches a test environment. Semgrep has emerged as the most practical SAST tool for AppSec teams because it strikes the right balance between power and usability. Unlike traditional SAST tools that require complex setup, proprietary licenses, and generate thousands of false positives, Semgrep uses a pattern-matching approach with a simple, readable rule syntax that security engineers can customize. Understanding SAST fundamentals and mastering Semgrep will be one of your most frequently used skills as an AppSec engineer.

SAST tools work through several techniques. The simplest is pattern matching -- essentially regex on steroids that understands code structure. More advanced tools build an Abstract Syntax Tree (AST), which represents the code's logical structure rather than its textual form. This means a SAST tool using AST analysis can match "user input flows to a SQL query" regardless of variable names, whitespace, or formatting. The most sophisticated technique is taint analysis: the tool tracks data from sources (user input, environment variables, file reads) through transformations and function calls to sinks (SQL queries, shell commands, HTML output). If tainted data reaches a dangerous sink without passing through a sanitizer, the tool flags a vulnerability. Semgrep supports all three approaches: simple pattern matching, AST-aware matching, and taint analysis via its "taint mode."

Semgrep's rule syntax is designed to be readable by security engineers who are not language designers. A basic rule specifies a pattern to match, the languages it applies to, a severity level, and a message. For example, a rule to find hardcoded AWS keys might match the pattern \`AKIA[0-9A-Z]{16}\` in any string literal. A more sophisticated rule uses metavariables (like \`$VAR\`) to capture arbitrary expressions, ellipsis operators (\`...\`) to match zero or more arguments, and metavariable types to constrain matches. Semgrep provides built-in rule packs organized by language and framework -- the "p/default" pack covers common vulnerabilities across popular languages, while framework-specific packs like "p/django" or "p/express" target framework-specific patterns. You can combine built-in packs with custom rules tailored to your organization's codebase.

Integrating Semgrep into CI/CD is where it delivers continuous value. The typical setup runs Semgrep on every pull request, blocking merges if high-severity findings are detected and posting comments for medium-severity issues. The key to successful CI integration is managing false positives. Every false positive that blocks a developer's PR erodes trust in the tool. Start with a conservative rule set (high-confidence, high-severity rules only), and gradually expand coverage as you tune rules and build developer confidence. Use Semgrep's \`nosemgrep\` inline comments for justified suppressions, but require a comment explaining why the suppression is safe. Track suppression rates -- a rule that is suppressed more than 30% of the time probably needs tuning.

Triaging SAST findings is a skill that improves with practice. When you receive a batch of findings from a new rule or a new codebase scan, start by grouping findings by rule. Look for patterns: are there ten instances of the same finding in test files? Those are probably false positives that can be excluded by path. Are there findings in generated code or vendored dependencies? Exclude those paths. For the remaining findings, assess exploitability: can an attacker actually reach this code path with controlled input? A SQL injection in an admin-only endpoint behind MFA is lower priority than one in a public API. Document your triage decisions so they can be reviewed and used to train junior team members.`,
    practiceEn: [
      'Install Semgrep CLI and run it against a deliberately vulnerable application (OWASP WebGoat, Juice Shop, or DVWA source code). Use the "p/default" rule pack. Categorize findings as true positives, false positives, or uncertain. Calculate the true positive rate.',
      'Write three custom Semgrep rules: (1) detect hardcoded passwords in Python/JavaScript assignment statements, (2) find uses of eval() or Function() in JavaScript with non-constant arguments, (3) detect SQL string concatenation in any language. Test each rule against sample vulnerable and safe code.',
      'Set up a Semgrep CI pipeline in a GitHub Actions workflow or GitLab CI config. Configure it to: run on pull requests, fail the build only on high-severity findings, post inline comments for medium-severity findings, and skip scanning of test directories and vendored code.',
      '★ Explore Semgrep taint mode by writing a taint rule that tracks user input from an Express.js request parameter (req.query, req.body, req.params) to a database query (using any ORM or raw SQL). Define appropriate sanitizers that should break the taint chain.',
      '★ Perform a triage exercise: run Semgrep with the full "p/security-audit" pack against a medium-sized open-source project. Triage the first 20 findings, documenting for each: rule ID, file/line, true positive or false positive, severity assessment, and recommended action.',
    ],
  },

  34: {
    lectureEn: `CodeQL takes static analysis to a deeper level by treating code as data that can be queried. Developed by GitHub (originally Semmle), CodeQL works by first extracting a relational database from your source code -- every function, variable, expression, and data flow relationship becomes a queryable table. You then write queries in a purpose-built language called QL (similar to SQL with object-oriented extensions) to find patterns. This approach is extraordinarily powerful: instead of writing pattern-matching rules, you can express complex security properties like "find all paths from user-controlled input to a database query that do not pass through a parameterization function, across any number of function calls and file boundaries."

CodeQL's code model is what makes it different from simpler SAST tools. When CodeQL builds its database, it resolves types, tracks method dispatch, follows interface implementations, and models library behavior. This means CodeQL can follow data through a chain of method calls across files and classes -- something that pattern-based tools like Semgrep struggle with. For example, if user input enters through a Spring MVC controller, passes through three service classes, gets transformed by a utility function, and eventually reaches a SQL query, CodeQL can trace that entire path. The tradeoff is build time: creating the CodeQL database requires compiling the code (for compiled languages) and can take minutes to hours for large codebases.

Writing basic CodeQL queries requires understanding QL's class hierarchy. Every language has a CodeQL library with classes like \`Function\`, \`MethodCall\`, \`StringLiteral\`, \`DataFlow::Node\`, and \`TaintTracking::Configuration\`. A simple query to find all calls to \`eval()\` in JavaScript looks like: \`from CallExpr call where call.getCalleeName() = "eval" select call, "Use of eval"\`. More useful queries use CodeQL's taint tracking library: you define a "source" (e.g., HTTP request parameters), a "sink" (e.g., SQL query construction), and optional "sanitizers" (e.g., parameterized query builders), and CodeQL finds all data flow paths from source to sink. CodeQL comes with hundreds of pre-built queries organized by language and CWE number, and GitHub's code scanning runs these automatically on public repositories.

Knowing when to use CodeQL versus Semgrep is an important practical decision. Semgrep excels at: fast feedback in CI (seconds, not minutes), simple pattern matching, custom organization-specific rules, and languages where CodeQL support is limited. CodeQL excels at: deep inter-procedural taint analysis, complex data flow queries, finding vulnerabilities that span multiple files and function calls, and systematic analysis of large codebases. In practice, most AppSec teams use both: Semgrep in the CI pipeline for fast feedback on every PR, and CodeQL for periodic deep scans (weekly or per-release) and for investigating specific vulnerability classes.

Beyond Semgrep and CodeQL, the SAST landscape includes several other tools worth understanding. Snyk Code uses AI-assisted analysis and is known for low false positive rates but is a commercial product. SonarQube (Community Edition is free) combines SAST with code quality analysis and is popular in enterprise environments, though its security rules are less sophisticated than dedicated security tools. Checkmarx and Fortify are enterprise SAST tools with deep language support but high license costs and complex deployment. Every SAST tool has fundamental limitations: they cannot analyze runtime behavior (configuration-dependent vulnerabilities, environment-specific issues), they struggle with custom frameworks and DSLs, and they produce false positives that require human triage. Understanding these limitations helps you set realistic expectations with developers and management.`,
    practiceEn: [
      'Set up CodeQL locally using the VS Code extension or CLI. Create a CodeQL database from a small Java or JavaScript project. Run the default security queries and examine the results, comparing them to what Semgrep found on the same codebase.',
      '★ Write a basic CodeQL query that finds all functions in a JavaScript project that take user input (from Express req object) and pass it to a child_process.exec() call without sanitization. Use the TaintTracking library to follow data flow across function boundaries.',
      '★ Run both Semgrep and CodeQL against the same vulnerable application (e.g., OWASP Benchmark for Java). Compare the findings: which vulnerabilities did each tool find? Which did each miss? Calculate precision and recall for both tools.',
      'Explore Snyk Code or SonarQube Community Edition on one of your projects. Compare the developer experience (setup time, scan speed, finding quality, IDE integration) with Semgrep and CodeQL. Write a tool comparison matrix.',
      'Investigate a SAST limitation: find a vulnerability class that none of the tools detect reliably (e.g., business logic flaws, TOCTOU race conditions, or complex deserialization gadget chains). Explain why static analysis fundamentally struggles with this class and what alternative detection methods exist.',
    ],
  },

  35: {
    lectureEn: `Software Composition Analysis (SCA) addresses a reality that many developers underestimate: the average modern application consists of 80-90% third-party code. When you import a package from npm, PyPI, or Maven Central, you inherit not just that package's code but its entire transitive dependency tree -- and every vulnerability in that tree. The npm ecosystem averages over 80 transitive dependencies per direct dependency. SCA tools scan your dependency manifests (package.json, requirements.txt, pom.xml, go.mod) and lock files, compare each dependency version against vulnerability databases (NVD, GitHub Advisory Database, OSV), and alert you to known vulnerabilities. But SCA is more than just vulnerability scanning -- it encompasses license compliance, dependency health assessment, and supply chain integrity.

The major SCA tools each have strengths. Dependabot (GitHub-native) automatically creates pull requests to update vulnerable dependencies, which is convenient but can create PR fatigue if you have many dependencies. Snyk provides richer vulnerability intelligence with exploit maturity data and fix recommendations, including automatic upgrade PRs and patch suggestions. OSV-Scanner (by Google) uses the Open Source Vulnerability database, which aggregates advisories from multiple sources and is completely free. The key metric for evaluating SCA tools is not just vulnerability detection but actionability: does the tool tell you whether the vulnerable function is actually called in your code (reachability analysis)? A vulnerability in a dependency you use but in a function you never call is lower priority than one in a function on your critical path.

Software Bill of Materials (SBOM) has become a regulatory requirement in many contexts. An SBOM is a machine-readable inventory of all software components in your application -- direct dependencies, transitive dependencies, their versions, licenses, and suppliers. Two standards dominate: CycloneDX (OWASP) and SPDX (Linux Foundation). US Executive Order 14028 requires SBOM for software sold to the federal government. Even if you do not sell to governments, generating SBOMs is a best practice because they enable rapid response during zero-day events. When Log4Shell (CVE-2021-44228) hit, organizations with SBOMs could immediately identify which applications used Log4j and which version -- those without SBOMs spent days or weeks on manual inventory. Generate SBOMs as part of your CI/CD pipeline and store them alongside your build artifacts.

Secrets scanning is an adjacent but critical supply chain security concern. Developers accidentally commit API keys, database passwords, JWT secrets, and cloud credentials to version control with alarming frequency. A 2023 GitGuardian report found over 10 million secrets exposed in public GitHub commits. Once a secret is committed, it exists in the git history forever unless you rewrite history (a disruptive operation). Prevention is far better than remediation. Tools like gitleaks and trufflehog scan git repositories (including full history) for patterns matching known secret formats (AWS keys start with AKIA, GitHub tokens start with ghp_, etc.). These should run as pre-commit hooks (catching secrets before they enter history) and in CI (catching anything that slips through).

The SLSA framework (Supply-chain Levels for Software Artifacts, pronounced "salsa") provides a maturity model for supply chain security. SLSA Level 1 requires that builds are documented. Level 2 requires that builds use a hosted build service with authenticated provenance. Level 3 requires that the build service is hardened and that provenance is non-forgeable. Level 4 (aspirational) requires a two-party review and hermetic, reproducible builds. SLSA addresses attacks like the SolarWinds breach, where attackers compromised the build system to inject malware into signed artifacts. Achieving SLSA Level 2 or 3 -- using GitHub Actions with signed provenance attestations, pinning actions by SHA rather than tag, and using verified base images -- is achievable for most teams and provides meaningful supply chain protection.`,
    practiceEn: [
      'Run three SCA tools (Dependabot/GitHub security alerts, Snyk, and OSV-Scanner) against the same project. Compare: which vulnerabilities does each find? Do they agree on severity? Which provides the most actionable remediation guidance? Which catches reachability?',
      'Generate an SBOM for a project using both CycloneDX (via cdxgen or syft) and SPDX formats. Examine the output: what information does each format capture? Feed the SBOM into a vulnerability scanner (grype or dependency-track) and compare results to direct SCA scanning.',
      'Set up gitleaks as a pre-commit hook and trufflehog as a CI scanner on a test repository. Commit several types of test secrets (use revoked/fake credentials) and verify detection. Examine the regex patterns each tool uses and identify any secret types they miss.',
      '★ Audit the supply chain of a specific npm or PyPI package: How many transitive dependencies does it pull in? Who maintains them? When were they last updated? Are any maintainers single individuals with no organizational backing? Use socket.dev or npm audit signatures to check for suspicious packages.',
      '★ Implement SLSA Level 2 for a GitHub repository: configure GitHub Actions to generate build provenance attestations, pin all action references by commit SHA instead of tag, and use a locked dependency file. Verify the provenance using slsa-verifier.',
      'Create an incident response playbook for "critical zero-day in a widely-used dependency" (like Log4Shell). Include steps for: identifying affected applications, assessing exposure, applying mitigations, communicating to stakeholders, and performing post-incident review.',
    ],
  },

  36: {
    lectureEn: `Dynamic Application Security Testing (DAST) takes the opposite approach from SAST: instead of analyzing source code, DAST tests a running application by sending HTTP requests and analyzing responses. This is closer to what an actual attacker does, which means DAST can find vulnerabilities that SAST cannot -- configuration issues, authentication flaws, runtime-dependent bugs, and the actual exploitability of potential vulnerabilities. The tradeoff is that DAST can only test what it can reach: it needs a running application, it can only find vulnerabilities in endpoints it discovers, and it cannot provide exact source code locations for findings. DAST and SAST are complementary, not competing -- a mature AppSec program uses both.

OWASP ZAP (Zed Attack Proxy) is the most widely used open-source DAST tool. In automated mode, ZAP can spider a web application to discover endpoints, then run active scanning that sends attack payloads (SQL injection strings, XSS payloads, path traversal sequences, etc.) to each discovered parameter. ZAP's automated scan produces a report categorized by risk level and CWE. For CI/CD integration, ZAP provides Docker images and a set of packaged scans: the Baseline Scan (passive analysis only, fast, few false positives), the Full Scan (active scanning, thorough but slow), and the API Scan (designed for REST/GraphQL APIs using OpenAPI/Swagger specs). The API Scan is particularly valuable because you feed it your API specification, and ZAP automatically generates requests for every endpoint with appropriate payloads.

Authenticated DAST is where most teams struggle and where you add the most value. An unauthenticated scan only tests the login page and public endpoints -- missing the vast majority of the application's attack surface. To scan authenticated functionality, you need to configure ZAP with valid credentials or session tokens. The approaches include: recording an authentication sequence (login form submission), providing a session token directly, using ZAP's built-in authentication mechanisms (form-based, JSON-based, script-based), or using ZAP as a downstream proxy behind an authentication proxy. For modern applications using OAuth2/OIDC, JWT, or multi-factor authentication, you often need to write a ZAP script (in Python or JavaScript) that handles the authentication flow. Session management is equally important -- ZAP needs to detect when a session has expired and re-authenticate.

Interactive Application Security Testing (IAST) is a hybrid approach that instruments the running application to observe code execution while DAST-style requests are being sent. IAST agents (deployed alongside the application runtime) can see the actual code paths executed, the SQL queries generated, the files accessed, and the data transformations applied. This gives IAST the coverage of DAST with the precision of SAST -- it can tell you exactly which line of code is vulnerable and confirm exploitability. The downside is that IAST requires deploying an agent into your application runtime, which can impact performance and may not be acceptable in all environments. Commercial IAST tools include Contrast Security and Hdiv Security.

Fuzz testing (fuzzing) is a powerful complement to structured DAST scanning. While DAST sends known attack payloads, fuzzing sends randomly generated or mutated inputs designed to trigger unexpected behavior -- crashes, hangs, memory corruption, and unhandled exceptions. For web APIs, tools like RESTler (from Microsoft Research) can automatically generate stateful fuzzing sequences from an API specification, testing not just individual endpoints but sequences of API calls that exercise state machines. For lower-level code (parsers, deserializers, protocol handlers), AFL++ and libFuzzer can find memory safety issues. Fuzzing is particularly effective at finding edge cases that developers and security testers do not think to test -- the bizarre Unicode string, the deeply nested JSON object, or the request with Content-Length disagreeing with the actual body length.`,
    practiceEn: [
      'Run OWASP ZAP Baseline Scan against OWASP Juice Shop (running in Docker). Review the findings report. Then run the Full Scan and compare: what additional vulnerabilities did active scanning find? How much longer did it take?',
      '★ Configure authenticated scanning in ZAP for a test application. Set up form-based authentication, configure session management (cookie-based or token-based), and verify that ZAP can access protected endpoints by checking the Sites tree for authenticated-only paths.',
      'Use ZAP API Scan mode with an OpenAPI specification. If you have an API project with a Swagger/OpenAPI spec, feed it to ZAP and examine how it generates requests. Compare the findings to a manual spider-and-scan approach.',
      '★ Set up a basic fuzzing pipeline: use a tool like wfuzz or ffuf to fuzz URL parameters, HTTP headers, and JSON body fields of a test API. Focus on finding: unexpected status codes (500), timing anomalies (potential blind injection), and response size variations (potential information disclosure).',
      'Integrate DAST into a CI/CD pipeline by running ZAP Baseline Scan in a GitHub Actions workflow against your application deployed in a test environment. Configure it to fail the pipeline on high-risk findings and generate an HTML report as a build artifact.',
    ],
  },

  37: {
    lectureEn: `Secure code review is the human complement to automated scanning -- and in many ways, it is more valuable. SAST tools excel at finding known patterns (SQL injection, XSS, hardcoded secrets), but they cannot understand business logic, evaluate the correctness of authorization checks, assess whether an algorithm is cryptographically sound, or determine if a race condition is exploitable in a given deployment context. A skilled security code reviewer catches the vulnerabilities that tools miss: broken access control, insecure direct object references, time-of-check-to-time-of-use (TOCTOU) bugs, logic flaws in payment processing, and subtle authentication bypasses. As a QA engineer, you already have the mindset of looking for edge cases -- security code review applies that same critical thinking to security-relevant code paths.

Developing a systematic approach to code review prevents you from getting lost in large codebases. Start with the entry points: HTTP route handlers, API controllers, WebSocket handlers, queue consumers, and scheduled job runners. These are where external input enters the system. From each entry point, trace the data flow: where does user input go? How is it validated? Is it sanitized before reaching a dangerous sink (database query, file system operation, shell command, HTML template, redirect URL)? After reviewing entry points, focus on the security-critical modules: authentication (login, session management, token validation), authorization (permission checks, role enforcement), cryptography (key generation, encryption, hashing), and data protection (PII handling, logging, error messages).

Prioritization is essential because you cannot review every line of code. Focus your review effort on: (1) new code in security-sensitive areas, (2) changes to authentication or authorization logic, (3) code that handles user input, (4) code that interacts with external systems (APIs, databases, file systems), (5) configuration changes (especially security headers, CORS policies, CSP), and (6) code flagged by SAST tools that needs human verification. Ignore (or deprioritize) test code, documentation, CSS/styling changes, and dependency version bumps (SCA handles those). Many teams use code ownership rules (CODEOWNERS in GitHub) to automatically request security review when security-sensitive files are modified.

Cognitive load management is an underappreciated aspect of code review. Research shows that review effectiveness drops significantly after about 60-90 minutes of continuous review or after reviewing more than 400 lines of code. For security reviews specifically, the number is probably lower because security analysis requires holding more mental context (threat models, attack vectors, trust boundaries). Break large reviews into sessions. Use a checklist to ensure consistency -- even experienced reviewers miss items when they rely solely on memory. Take notes as you review, marking areas that need deeper investigation, questions for the developer, and patterns you want to search for across the codebase.

Using AI assistants (like GitHub Copilot, ChatGPT, or Claude) for security code review requires careful judgment. AI can be genuinely helpful for: explaining unfamiliar code patterns, identifying potential issues you might investigate further, generating test cases for suspicious code, and speeding up your understanding of large codebases. However, AI assistants should never be your sole reviewer. They can miss context-dependent vulnerabilities, hallucinate false positives or false negatives with high confidence, fail to understand the application's specific threat model, and may not be aware of recent vulnerability classes. Use AI as a first pass to identify areas of interest, then apply your own judgment to verify findings and catch what the AI missed. Never let an AI generate a "security approved" stamp -- that is your professional responsibility.`,
    practiceEn: [
      'Pick a recent pull request from a popular open-source project (Node.js, Django, or similar) that touches authentication or authorization code. Conduct a 30-minute security review. Document your findings as inline comments, noting: the issue, why it matters, and a suggested fix.',
      'Create a security code review checklist tailored to your primary language/framework (e.g., Express.js or Django). Include at least 25 items across categories: input validation, authentication, authorization, cryptography, error handling, logging, data protection, and configuration. Test the checklist against a deliberately vulnerable application.',
      'Practice timed reviews: set a 20-minute timer and review a 200-line code change. After the timer, note what you found and what you did not have time to examine. Repeat with different code changes to improve your prioritization instincts.',
      '★ Review a piece of code that uses cryptographic operations (encryption, hashing, digital signatures). Check for: appropriate algorithm choices (not MD5/SHA1 for security), proper key sizes, secure random number generation, correct mode of operation (not ECB), and proper IV/nonce handling.',
      'Take a SAST finding that was marked as "needs review" and perform a deep-dive code review to determine if it is a true positive or false positive. Document your reasoning: the data flow, any sanitizers present, whether the code path is reachable with attacker-controlled input, and your verdict with justification.',
      'Use an AI assistant to review a piece of security-sensitive code, then review the same code yourself. Compare findings: what did the AI catch that you might have missed? What did it miss or get wrong? Document your observations about the strengths and limitations of AI-assisted review.',
    ],
  },

  38: {
    lectureEn: `Python and Node.js dominate web application development, and each ecosystem has its own vulnerability patterns shaped by language features, common frameworks, and developer conventions. As a security code reviewer, you need to recognize these patterns instantly -- the way an experienced developer recognizes a bug from a stack trace. This week focuses on building that pattern recognition for Express.js, FastAPI, and Django, the three most popular web frameworks in these languages.

In Express.js (Node.js), the most dangerous functions are those that evaluate or execute strings as code: \`eval()\`, \`Function()\`, \`setTimeout/setInterval\` with string arguments, \`vm.runInNewContext()\`, and \`child_process.exec()\`. Any of these that receive user input, directly or indirectly, are critical vulnerabilities. Command injection through \`child_process.exec()\` is especially common because developers use it for features like file conversion, PDF generation, or system information display. The safe alternative is \`child_process.execFile()\`, which does not invoke a shell. Template injection in Express is another pattern: if you use a template engine (EJS, Pug, Nunjucks) and pass user input as a template string rather than a template variable, the user can inject template directives that execute arbitrary code on the server. Check for patterns like \`res.render(userInput)\` or \`ejs.render(userInput)\`.

ORM injection is a subtle vulnerability class that many developers believe ORMs prevent. While ORMs do protect against classic SQL injection when used correctly, they still allow injection when developers pass raw queries or use unsafe query-building methods. In Sequelize (Node.js), using \`sequelize.query()\` with string interpolation is SQL injection. In Django ORM, using \`.raw()\` or \`.extra()\` with user input bypasses parameterization. SQLAlchemy (Python) has \`text()\` for raw SQL and \`column()\` for dynamic column names -- both can be injection vectors. Even the "safe" query methods can be vulnerable to NoSQL injection when using MongoDB with Mongoose: passing a JSON object where a string is expected (e.g., \`{$gt: ""}\` in a password field) bypasses authentication. Always check: is user input used in any ORM method that accepts raw expressions?

In Django, common vulnerability patterns include: CSRF protection disabled (\`@csrf_exempt\` decorator), unsafe deserialization (\`pickle.loads()\` on user data), path traversal in file handling (\`os.path.join()\` does not prevent absolute path injection -- use \`pathlib\` with proper validation), XML External Entity (XXE) processing (Python's \`xml.etree\` is safe but \`lxml\` with external entity processing enabled is not), and Server-Side Request Forgery (SSRF) through \`requests.get(user_url)\` without URL validation. In FastAPI, watch for: Pydantic model validation bypasses (using \`Any\` type or \`dict\` instead of typed models), background tasks that do not inherit authentication context, and WebSocket endpoints that skip authorization checks.

Python-specific dangerous functions include: \`eval()\`, \`exec()\`, \`compile()\`, \`__import__()\`, \`subprocess.call(shell=True)\`, \`os.system()\`, \`os.popen()\`, and \`pickle.loads()\`. The \`subprocess\` module deserves special attention: \`subprocess.call(cmd, shell=True)\` is command injection if \`cmd\` contains user input, while \`subprocess.call([binary, arg1, arg2], shell=False)\` is safe because arguments are passed directly without shell interpretation. Pickle deserialization is essentially arbitrary code execution -- never unpickle data from untrusted sources. Even YAML parsing can be dangerous: \`yaml.load()\` (without \`Loader=SafeLoader\`) in PyYAML can execute arbitrary Python code through YAML's \`!!python/object\` directive. In Node.js, watch for prototype pollution -- modifying \`Object.prototype\` through unvalidated JSON merge operations -- which can lead to authentication bypass, property injection, and even remote code execution in specific frameworks.`,
    practiceEn: [
      'Audit an Express.js application for command injection. Search for all uses of child_process (exec, execSync, spawn with shell:true), eval, Function, vm module, and setTimeout/setInterval with string arguments. For each finding, determine if user input can reach the dangerous function.',
      'Create a vulnerable FastAPI application with at least five different vulnerability types: SQL injection via raw query, SSRF via unvalidated URL, path traversal in file download, insecure deserialization with pickle, and missing authentication on an endpoint. Then write Semgrep rules that detect each vulnerability.',
      'Review a Django application for ORM injection. Search for uses of .raw(), .extra(), RawSQL(), and connection.cursor().execute() with string formatting. Check whether the QuerySet filter methods receive user input that could be a dict (NoSQL-style injection via Django filters).',
      '★ Build a test suite of 10 prototype pollution payloads for Node.js applications. Test them against common npm packages that perform deep merge operations (lodash.merge, deepmerge, etc.). Document which versions are vulnerable and which have been patched.',
      'Audit a Python project for dangerous deserialization. Search for: pickle.loads, yaml.load (without SafeLoader), json.loads followed by eval, and any custom deserialization logic. For each finding, assess whether the input source is trusted or attacker-controlled.',
    ],
  },

  39: {
    lectureEn: `Go and Java represent a different security landscape than Python and Node.js. Go's simplicity and compile-time type safety eliminate certain vulnerability classes (no eval, no prototype pollution), but introduce others through its unique concurrency model, error handling patterns, and the unsafe package. Java's enterprise ecosystem, with Spring as its dominant framework, has its own extensive attack surface shaped by decades of features, XML processing libraries, serialization mechanisms, and complex class-loading behavior. Reviewing code in these languages requires understanding their specific idioms and where security breaks down.

Go's concurrency model -- goroutines and channels -- is elegant but introduces subtle security bugs. Race conditions in Go typically manifest when multiple goroutines access shared state without proper synchronization. A classic security-relevant race condition is a TOCTOU (Time-of-Check-Time-of-Use) bug in authorization: one goroutine checks a user's permission and another goroutine modifies the permission state between the check and the use. The Go race detector (\`go build -race\`) catches many but not all data races at runtime. In security code review, look for shared maps accessed from multiple goroutines (maps are not goroutine-safe in Go), global variables modified in HTTP handlers, and caching patterns that do not use proper locking. Error handling in Go is another security concern: the \`err != nil\` pattern is easy to get wrong. A missing error check after a security-critical operation (TLS certificate validation, permission check, cryptographic verification) silently continues with a failure state. Grep for unchecked errors in security-sensitive code using \`errcheck\` or similar linters.

Go's \`unsafe\` package bypasses the type system and memory safety guarantees. While rare in application code, it appears in performance-critical libraries and system-level code. Any use of \`unsafe.Pointer\` can lead to memory corruption, and the \`reflect\` package can be used for type confusion attacks. The \`os/exec\` package in Go is safer than Python/Node.js equivalents because it does not use a shell by default -- \`exec.Command("ls", "-la")\` passes arguments directly to the binary. However, combining it with \`bash -c\` reintroduces shell injection: \`exec.Command("bash", "-c", userInput)\` is dangerous. Also watch for SSRF through Go's \`http.Get()\` -- the standard HTTP client follows redirects by default, which can be abused to reach internal services.

Java deserialization vulnerabilities have been among the most devastating in enterprise security. Java's native serialization (\`ObjectInputStream.readObject()\`) can trigger arbitrary code execution through carefully crafted byte streams that exploit "gadget chains" -- sequences of method calls across classes in the classpath that, when chained together through deserialization, achieve code execution. The ysoserial tool catalogs known gadget chains for common libraries (Apache Commons Collections, Spring, etc.). Spring applications are particularly vulnerable because they include many libraries with known gadget chains on the classpath. Beyond native serialization, watch for: JSON deserialization with type information (Jackson with \`enableDefaultTyping()\`, which allows attackers to specify which class to deserialize into), XML deserialization, and any mechanism that instantiates classes based on attacker-controlled input.

Spring Security misconfiguration is a frequent finding in Java application reviews. Common issues include: overly permissive security filter chains (using \`permitAll()\` on paths that should be protected), incorrect ordering of security rules (Spring evaluates rules in order, so a broad \`permitAll()\` before a specific \`authenticated()\` rule wins), disabled CSRF protection without proper justification, HTTP Basic authentication over non-TLS connections, and hardcoded credentials in configuration files. XXE (XML External Entity) injection is another Java-specific concern because Java's built-in XML parsers enable external entity processing by default. Any code using \`DocumentBuilderFactory\`, \`SAXParserFactory\`, or \`XMLInputFactory\` without explicitly disabling external entities is vulnerable. SSRF through Java's \`HttpURLConnection\` or Apache HttpClient is common in applications that fetch URLs provided by users (webhook configurations, profile image URLs, document imports).`,
    practiceEn: [
      '★ Review a Go HTTP service for concurrency bugs. Search for shared maps, global variables accessed in handlers, and goroutines that share state. Use the race detector (go build -race, go test -race) on the test suite and analyze any reported races for security impact.',
      'Audit a Go application for error handling security issues. Use errcheck or staticcheck to find unchecked errors. Focus on errors from: TLS operations, cryptographic functions, database queries, file operations, and authentication/authorization checks. Assess the security impact of each unchecked error.',
      '★ Build a test case for Java deserialization. Download ysoserial and generate payloads for common gadget chains (CommonsCollections, Spring). Set up a vulnerable Java endpoint that deserializes ObjectInputStream and demonstrate code execution. Then implement the fix (input validation, look-ahead deserialization, or migration to JSON).',
      'Review a Spring Boot application security configuration. Check: SecurityFilterChain rules ordering, CSRF configuration, CORS settings, session management, password encoding (BCrypt vs SHA-256), and actuator endpoint exposure. Document each finding with the misconfiguration and its security impact.',
      'Audit a Java application for XXE vulnerabilities. Search for all XML parsing (DocumentBuilderFactory, SAXParser, XMLInputFactory, Transformer, XPath). For each instance, verify whether external entities and DTDs are disabled. Write a proof-of-concept XXE payload and test it against any unprotected parser.',
      'Compare security linting tools for Go and Java. Run gosec on a Go project and SpotBugs (with FindSecBugs plugin) on a Java project. Evaluate finding quality, false positive rate, and coverage of security-relevant checks.',
    ],
  },

  40: {
    lectureEn: `Bug bounty programs represent the intersection of offensive security skills and professional practice. For an AppSec engineer, participating in bug bounties sharpens your attacker mindset, exposes you to diverse technology stacks, and builds a public track record that enhances your professional reputation. Unlike CTF challenges with guaranteed solutions, bug bounties are against real production systems maintained by real engineers -- findings may not exist, may require chaining multiple issues, and must be communicated clearly enough for the target organization to understand and reproduce. This is as close to real-world offensive security as you can get without a pentesting engagement.

Choosing the right program is your first strategic decision. Start with programs on platforms like HackerOne, Bugcrowd, or Intigriti rather than programs hosted directly by companies, because platforms provide mediation for disputes and standardized disclosure processes. Within platforms, look for programs with: a broad scope (more attack surface means more opportunity), responsive triage teams (check average time to first response), fair reward history (check public disclosed reports for payout amounts), and a safe harbor clause (legal protection for good-faith testing). Avoid programs with very narrow scopes, long response times, or histories of closing valid reports as "informative" without payment. Many programs have a "VDP" (Vulnerability Disclosure Policy) tier with no monetary rewards -- these are good for building your reputation but do not confuse a VDP with a bug bounty.

Reconnaissance is the foundation of successful bug bounty hunting. Before you touch the target application, you need to understand its full attack surface. Subdomain enumeration tools like Amass, Subfinder, and crt.sh (Certificate Transparency logs) reveal subdomains that may host forgotten test environments, old API versions, or admin panels. Httpx then probes each discovered host for live services, capturing status codes, titles, and technologies. Port scanning with Nmap or Masscan reveals non-HTTP services. Content discovery tools like Feroxbuster or ffuf brute-force URL paths to find hidden endpoints, admin interfaces, and API documentation. Technology fingerprinting with Wappalyzer or WhatWeb identifies the tech stack, which guides your vulnerability research. JavaScript file analysis using tools like LinkFinder extracts API endpoints and secrets from client-side code. This reconnaissance phase often reveals more about the target's attack surface than the program description discloses.

Documentation is what separates a report that gets paid from one that gets closed. A bug bounty report should contain: a clear title that summarizes the vulnerability and its impact, affected URLs or endpoints, step-by-step reproduction instructions that a non-security engineer can follow, proof of concept (screenshots, HTTP requests/responses, video), impact assessment (what an attacker could achieve), and suggested remediation. Use Burp Suite or Caido to capture exact HTTP requests for reproduction. Record videos with tools like OBS for complex multi-step attacks. Avoid overstating impact -- claiming "full account takeover" for a self-XSS damages your credibility. Conversely, do not understate impact -- if a reflected XSS can be combined with a CSRF token in the response to achieve account takeover, explain the chain.

Coordinated disclosure ethics are non-negotiable. Never access data beyond what is necessary to prove the vulnerability. Never modify or delete data. Never use automated scanners at volumes that could degrade the target's service. Never disclose a vulnerability publicly before the program authorizes it (typically 90 days after the fix or at mutual agreement). If you accidentally access sensitive data (PII, credentials, financial records), stop immediately, document what you accessed and how, report it to the program, and delete any data you downloaded. If a program is unresponsive to a critical vulnerability for an extended period, CERT/CC and the platform's mediation team are your escalation paths -- unilateral public disclosure should be an absolute last resort.`,
    practiceEn: [
      '★ Set up a bug bounty reconnaissance workflow. Using a practice domain (your own or a deliberately vulnerable target like pentesterlab.com), run: amass enum, subfinder, httpx for live host detection, and feroxbuster/ffuf for content discovery. Compile the results into a structured target map.',
      'Analyze HackerOne Hacktivity or Bugcrowd public disclosures. Read 10 disclosed reports across different vulnerability categories. For each, note: what the vulnerability was, how it was found, the quality of the report, the payout, and what you would have done differently.',
      'Write a mock bug bounty report for a vulnerability you find in a practice application (Juice Shop, HackTheBox, or a CTF). Follow the format: title, severity (CVSS), affected endpoint, reproduction steps, proof of concept, impact assessment, and remediation recommendation. Have a peer review the clarity.',
      'Practice JavaScript file analysis for secret discovery. Download the JavaScript bundles from a web application (your own or a practice target), use tools like LinkFinder and SecretFinder to extract endpoints and potential secrets. Document any API keys, internal URLs, or configuration data found in client-side code.',
      'Set up a personal bug bounty methodology document. Define your phases (recon, mapping, testing, reporting), the tools for each phase, your prioritized vulnerability checklist (what you test first), and your rules of engagement (what you will and will not do). This becomes your playbook for efficient testing.',
    ],
  },

  41: {
    lectureEn: `AWS IAM (Identity and Access Management) is the single most important security service in AWS, and it is also the most commonly misconfigured. Every API call to every AWS service is authenticated and authorized through IAM. Understanding IAM deeply is essential because misconfigurations here do not just expose one resource -- they can grant an attacker access to your entire cloud infrastructure. IAM operates on the principle of identity-based policies (attached to users, groups, or roles) and resource-based policies (attached to resources like S3 buckets or SQS queues). The interaction between these two policy types, combined with permission boundaries, service control policies, and session policies, creates a complex authorization model that even experienced engineers struggle with.

IAM users are identities with long-lived credentials (access key ID and secret access key). In modern AWS practice, IAM users should be minimized or eliminated entirely in favor of IAM roles. Roles are identities without permanent credentials -- instead, they issue temporary security tokens via the AWS Security Token Service (STS). The \`AssumeRole\` API call is central to how roles work: a principal (user, service, or another role) calls \`sts:AssumeRole\` with the role's ARN, and if both the role's trust policy and the principal's permissions policy allow it, STS returns temporary credentials. This two-policy requirement is a fundamental IAM concept: the trust policy on the role says who can assume it, and the permissions policy on the caller says what roles they can assume. Both must allow the action for it to succeed.

The confused deputy problem is a classic cloud security issue that arises when a service assumes a role on behalf of a customer. Imagine a logging service (Account A) that writes logs to your S3 bucket (Account B). You create a role in Account B that trusts Account A. But what if another customer of the logging service tricks it into assuming your role to access your data? The attacker (Account C) never has access to your role directly -- they use the logging service as a confused deputy. The solution is the \`ExternalId\` condition in the trust policy: you set a unique secret value that Account A must provide when assuming the role, and only you and Account A know this value. AWS also uses the \`aws:SourceArn\` and \`aws:SourceAccount\` conditions to prevent cross-customer abuse in AWS service integrations.

Service Control Policies (SCPs) are guardrails applied at the AWS Organizations level. Unlike IAM policies that grant permissions, SCPs restrict the maximum permissions available to all principals in an account. If an SCP does not allow an action, no IAM policy in that account can grant it. SCPs are the organizational equivalent of permission boundaries for individual principals. Common SCP patterns include: denying access to unused regions (preventing attackers from spinning up resources in regions you do not monitor), requiring specific tags on resource creation, preventing disabling of CloudTrail or GuardDuty, and restricting the use of certain high-risk services. SCPs do not affect the management account, which is why the management account should be used only for organizational management, never for workloads.

Achieving least privilege in AWS is an ongoing process, not a one-time configuration. Start with AWS Access Analyzer, which analyzes CloudTrail logs to identify permissions that are granted but never used. The IAM Access Advisor shows when each service was last accessed by a principal, helping you identify overly broad policies. When writing IAM policies, be specific: instead of \`"Action": "s3:*"\`, list only the specific actions needed (\`s3:GetObject\`, \`s3:PutObject\`). Instead of \`"Resource": "*"\`, specify the exact ARN of the resource. Use conditions to further restrict access: \`aws:RequestedRegion\` limits actions to specific regions, \`aws:PrincipalTag\` enables attribute-based access control, and \`s3:prefix\` restricts S3 access to specific key prefixes. Regularly audit IAM policies using tools like Parliament, IAM Lint, or AWS Access Analyzer custom policy checks.`,
    practiceEn: [
      'In an AWS sandbox account (or using LocalStack), create a least-privilege IAM setup: a role for a web application that can only read from a specific S3 bucket prefix and write to a specific DynamoDB table. Verify the permissions work and test that actions outside the policy are denied.',
      '★ Demonstrate the confused deputy problem. Create two roles: one that trusts an external account (simulated), and one with the ExternalId condition. Show that without ExternalId, any principal in the trusted account can assume the role. Then show that with ExternalId, only callers providing the correct ExternalId succeed.',
      'Use AWS Access Analyzer to analyze an existing IAM policy. Identify: unused permissions, overly broad resource specifications (wildcards), and missing conditions. Rewrite the policy following least-privilege principles and validate it using the IAM policy simulator.',
      '★ Write three Service Control Policies: (1) deny all actions in unused AWS regions, (2) prevent disabling CloudTrail, GuardDuty, or Config, (3) require a "CostCenter" tag on all newly created EC2 instances and RDS databases. Test each SCP in a sandbox organizational unit.',
      'Audit an existing AWS account for IAM risks. Check for: IAM users with long-lived access keys (especially keys older than 90 days), users with console access but no MFA, policies with "Action": "*" or "Resource": "*", roles with overly permissive trust policies, and unused roles or policies. Document findings and recommended remediation.',
    ],
  },

  42: {
    lectureEn: `AWS networking and data protection form the second pillar of cloud security (after IAM). While IAM controls who can do what, networking controls determine what can communicate with what, and data protection ensures that information remains confidential and integral even if other controls fail. In the defense-in-depth model, these are independent layers -- a misconfigured security group should not lead to a data breach if data is properly encrypted, and stolen credentials should not expose data if network segmentation prevents access to the database tier.

A Virtual Private Cloud (VPC) is your isolated network in AWS. Within a VPC, subnets determine where resources are placed. The critical distinction is between public subnets (with a route to an Internet Gateway) and private subnets (no direct internet access). Databases, application servers, and internal services should always be in private subnets. Only load balancers and bastion hosts (if needed) should be in public subnets. For resources in private subnets that need outbound internet access (for software updates, API calls, etc.), use a NAT Gateway -- this allows outbound connections but prevents inbound connections from the internet. Security Groups are stateful firewalls attached to individual resources (EC2 instances, RDS databases, Lambda functions). Network ACLs (NACLs) are stateless firewalls at the subnet level. The key difference: Security Groups are stateful (return traffic is automatically allowed), while NACLs are stateless (you must explicitly allow both inbound and outbound traffic).

S3 bucket misconfigurations have caused some of the most publicized cloud data breaches. The main risk vectors are: public access via bucket policies or ACLs, overly permissive CORS configurations that allow cross-origin data access, missing encryption, and inadequate access logging. AWS has progressively added guardrails: S3 Block Public Access (account-level and bucket-level settings that prevent public policies), bucket ownership controls (disabling ACLs entirely), and access points for fine-grained access control. Despite these improvements, S3 misconfigurations persist because developers create buckets programmatically without enabling these guardrails, or because legacy buckets predate the guardrails. Your security review should verify: Block Public Access is enabled at the account level, bucket policies do not contain \`"Principal": "*"\` without appropriate conditions, server-side encryption is enforced, access logging is enabled, and versioning is on for sensitive data (providing recovery from accidental deletion or ransomware).

KMS (Key Management Service) is AWS's managed encryption key service. Understanding KMS is essential because encryption without proper key management is security theater. KMS manages Customer Master Keys (CMKs) that encrypt data keys, which in turn encrypt your data (envelope encryption). The critical security control is the KMS key policy, which determines who can use the key for encryption/decryption and who can manage the key itself. A common mistake is granting \`kms:*\` to broad principals -- this allows them to encrypt data, decrypt data, and even schedule key deletion (destroying all data encrypted with that key). Separate key administrators (who can manage key policies but not use keys for crypto operations) from key users (who can encrypt/decrypt but not change policies). For cross-account access, both the key policy and the caller's IAM policy must allow the action.

VPC endpoints (AWS PrivateLink) keep traffic between your VPC and AWS services within the AWS network, avoiding the public internet entirely. There are two types: Gateway endpoints (free, for S3 and DynamoDB) and Interface endpoints (priced per hour plus data transfer, for most other services). Using VPC endpoints for S3 eliminates the risk of S3 traffic being intercepted on the internet and enables you to create S3 bucket policies that deny access from outside the VPC endpoint -- ensuring that even if credentials are stolen, they can only be used from within your VPC. This is a powerful defense-in-depth control that is underutilized. Combine VPC endpoints with security group controls on the endpoint itself to restrict which resources within the VPC can reach which AWS services.`,
    practiceEn: [
      'Design a VPC architecture for a three-tier web application (web, app, data tiers) with proper subnet segmentation. Create public subnets for ALB, private subnets for application servers, and isolated subnets for databases. Configure security groups with least-privilege rules between tiers (only the specific ports needed).',
      'Audit S3 bucket security in an AWS account. For each bucket, check: Block Public Access settings, bucket policy for public access grants, encryption configuration (SSE-S3, SSE-KMS, or none), access logging status, versioning status, and lifecycle policies. Create a compliance report with findings and recommendations.',
      '★ Set up KMS encryption for S3 with proper key policy separation. Create a KMS key with a key policy that separates administrators (can manage key but not use it) from users (can encrypt/decrypt but not modify policy). Configure an S3 bucket to use this key for server-side encryption. Test that unauthorized principals cannot decrypt objects.',
      '★ Implement VPC endpoints for S3 and verify network path changes. Create a Gateway endpoint for S3, update route tables, and add a bucket policy condition that denies access except through the VPC endpoint (aws:sourceVpce condition). Verify that access from outside the VPC is denied even with valid credentials.',
      'Conduct a network security assessment of an AWS environment. Map all security groups and NACLs, identify overly permissive rules (0.0.0.0/0 inbound, broad port ranges), check for resources in public subnets that should be private, and verify NAT Gateway configuration for private subnet egress. Document findings with remediation priorities.',
    ],
  },

  43: {
    lectureEn: `Container security begins with the container image -- the immutable artifact from which containers are created. A container image is a layered filesystem, and each layer can introduce vulnerabilities through outdated base images, unpatched packages, embedded secrets, or insecure configurations. Image scanning tools like Trivy (Aqua Security, open-source) and Grype (Anchore, open-source) analyze image layers against vulnerability databases (NVD, GitHub Advisory, OS-specific advisories) and report known CVEs in installed packages. But scanning alone is not sufficient -- you need to prevent vulnerable images from running in production through admission controls and build pipeline gates.

Dockerfile best practices significantly reduce your attack surface. Use minimal base images: \`alpine\` (5 MB) or \`distroless\` (by Google, no shell, no package manager) instead of \`ubuntu\` or \`debian\` (which include hundreds of packages you do not need, each with potential vulnerabilities). Use multi-stage builds: compile your application in a builder stage with build tools, then copy only the compiled artifact to a minimal runtime stage. Never run containers as root -- add \`USER nonroot\` (or a specific UID) in your Dockerfile. Do not embed secrets in images (even if you delete them in a later layer, they persist in the layer cache). Pin base image versions by digest (\`FROM node:20-alpine@sha256:abc...\`) rather than tag (\`FROM node:20-alpine\`) to prevent supply chain attacks through tag mutation. Use \`.dockerignore\` to exclude sensitive files (.env, .git, private keys) from the build context.

Kubernetes security is a deep topic, but the core controls every AppSec engineer should understand are RBAC, Pod Security, Network Policies, and Secrets management. RBAC (Role-Based Access Control) in Kubernetes determines who can do what within the cluster. The key resources are Roles/ClusterRoles (define permissions) and RoleBindings/ClusterRoleBindings (assign permissions to subjects). Common RBAC misconfigurations include: granting \`cluster-admin\` to application service accounts, using \`*\` (wildcard) for verbs or resources, and not restricting which namespaces a service account can access. Review RBAC with \`kubectl auth can-i --list --as=system:serviceaccount:namespace:sa-name\` to see effective permissions.

Pod Security Standards (replacing the deprecated PodSecurityPolicy) define three levels: Privileged (unrestricted), Baseline (prevents known privilege escalations), and Restricted (heavily locked down). At minimum, enforce the Baseline level on all namespaces. The Restricted level adds: must run as non-root, must drop all capabilities, must use a read-only root filesystem, and must not allow privilege escalation. These controls prevent a compromised container from escalating to host access. Network Policies are Kubernetes firewalls that restrict pod-to-pod communication. By default, Kubernetes allows all pods to communicate with all other pods -- this is terrible from a security perspective because a compromised pod can scan and attack the entire cluster. Network Policies let you define ingress and egress rules based on pod labels, namespaces, and IP blocks. Start with a default-deny policy for each namespace, then explicitly allow only the traffic patterns your application requires.

Kubernetes Secrets management is often misunderstood. Kubernetes Secrets are base64-encoded (not encrypted) and stored in etcd. Anyone with API access to read Secrets in a namespace can decode them. For production environments, enable encryption at rest for etcd, use an external secrets manager (AWS Secrets Manager, HashiCorp Vault, or the Sealed Secrets controller), and restrict Secret read permissions in RBAC. The External Secrets Operator is a popular pattern that synchronizes secrets from external managers into Kubernetes Secrets, keeping the secret values out of your git repository and Kubernetes manifests. Never store secrets in ConfigMaps (which are not even base64-encoded), environment variables in pod specs (visible in the API), or container image layers.`,
    practiceEn: [
      'Scan a set of Docker images with both Trivy and Grype. Compare a full Ubuntu-based image with an Alpine-based image and a Distroless image for the same application. Count the CVEs in each and assess: how many are actually exploitable in your application context?',
      'Write a hardened Dockerfile for a Node.js or Python web application following all best practices: multi-stage build, minimal base image, non-root user, pinned base image by digest, no secrets in layers, .dockerignore configured, HEALTHCHECK instruction, and minimal installed packages.',
      'Set up Kubernetes RBAC for a multi-team environment. Create namespaces for "frontend" and "backend" teams. Define Roles that allow each team to manage pods, services, and configmaps in their namespace but not Secrets. Create a "security-auditor" ClusterRole with read-only access to all namespaces. Verify with kubectl auth can-i.',
      '★ Implement Network Policies for a microservices application. Start with a default-deny-all policy in the namespace. Then add policies that allow: frontend pods to talk to backend pods on port 8080, backend pods to talk to the database pod on port 5432, and only backend pods to make egress connections to external APIs. Verify that unauthorized traffic is blocked.',
      'Audit Kubernetes Secrets handling. Check: are Secrets encrypted at rest in etcd? Are Secret read permissions in RBAC appropriately restricted? Are any Secrets mounted as environment variables (less secure than volume mounts)? Are any secrets hardcoded in pod specs or ConfigMaps? Propose a migration to an external secrets manager.',
      '★ Create a container security pipeline: build a Docker image, scan it with Trivy in CI, fail the build if critical/high CVEs are found, sign the image with cosign (Sigstore), and verify the signature before deployment. Document the full pipeline configuration.',
    ],
  },

  44: {
    lectureEn: `Detection, logging, and incident response are the "shift-right" capabilities that complement your preventive controls. No matter how strong your SSDLC, threat modeling, and security testing are, some attacks will succeed. The question is not whether you will be breached, but whether you will detect it quickly, respond effectively, and learn from it. The average time to detect a breach (dwell time) was 204 days in 2023 according to the IBM Cost of a Data Breach report. Organizations with mature detection and response programs measured in hours or days rather than months. Building these capabilities is a core part of the AppSec engineer's role.

AWS provides a layered detection stack. CloudTrail logs every API call made in your account -- who did what, from where, and when. CloudTrail is non-negotiable: it must be enabled in all regions, with logs delivered to a centralized S3 bucket with integrity validation enabled. GuardDuty is AWS's managed threat detection service that analyzes CloudTrail, VPC Flow Logs, and DNS logs using machine learning and threat intelligence to identify suspicious activity: unusual API calls, compromised credentials, cryptocurrency mining, unauthorized access patterns, and data exfiltration. Security Hub aggregates findings from GuardDuty, Inspector, Macie, Firewall Manager, and third-party tools into a single pane, mapped to compliance frameworks (CIS AWS Foundations Benchmark, PCI DSS). Config tracks resource configuration changes and evaluates them against rules -- for example, alerting if an S3 bucket becomes publicly accessible or a security group allows SSH from 0.0.0.0/0.

Application-level logging is equally important and often neglected. Your application should log security-relevant events with enough detail to support investigation: authentication attempts (success and failure, with username and source IP), authorization decisions (who was denied access to what), data access patterns (who accessed which records), administrative actions (configuration changes, user management), and input validation failures (potential attack indicators). Logs must be structured (JSON format), include correlation IDs for tracing requests across services, and be shipped to a centralized logging system in near-real-time. Never log sensitive data: passwords, API keys, credit card numbers, personal identification numbers, or session tokens. Use log levels appropriately: security events should be at INFO or WARN level so they are not lost when DEBUG logging is disabled in production.

A Security Information and Event Management (SIEM) system aggregates logs from multiple sources, normalizes them into a common format, and provides detection rules, correlation, and investigation capabilities. Modern SIEM platforms include Splunk, Elastic Security, Microsoft Sentinel, and open-source options like Wazuh. The key challenge with SIEM is signal-to-noise ratio: a production environment generates millions of log events daily, and security-relevant events are a tiny fraction. Detection rules must be tuned to minimize false positives while maintaining detection coverage. The MITRE ATT&CK framework is invaluable here -- each ATT&CK technique has associated detection strategies and data sources, so you can systematically map your detection rules to the threat landscape and identify gaps.

The NIST 800-61 Incident Response framework defines four phases: Preparation, Detection and Analysis, Containment-Eradication-Recovery, and Post-Incident Activity. Preparation includes: establishing an incident response team, defining communication plans, preparing runbooks for common incident types, deploying detection tools, and conducting tabletop exercises. Detection and Analysis is where you triage alerts, determine if an incident has occurred, assess scope and severity, and escalate appropriately. Containment aims to stop the bleeding -- isolating compromised systems, revoking compromised credentials, and blocking attacker IP addresses -- without destroying forensic evidence. Eradication removes the attacker's foothold (backdoors, compromised accounts, malware). Recovery restores systems to normal operation with verified integrity. Post-Incident Activity (the "lessons learned" phase) is the most frequently skipped and arguably the most valuable: documenting what happened, what worked, what failed, and what changes will prevent recurrence. Every significant incident should produce actionable improvements to detection rules, response procedures, or preventive controls.`,
    practiceEn: [
      'Set up a complete AWS detection stack in a sandbox account: enable CloudTrail (all regions, multi-region trail to a centralized bucket with log file validation), enable GuardDuty, enable Security Hub with CIS Foundations Benchmark, and enable AWS Config with managed rules for security-relevant resources. Generate sample findings by intentionally triggering GuardDuty alerts (e.g., port scanning, credential exfiltration simulation).',
      'Design an application logging specification for a web application. Define the exact log format (JSON schema with required fields), enumerate all security events that must be logged (at least 15 event types across authentication, authorization, data access, and administrative actions), specify what must never be logged (PII, credentials), and create sample log entries for each event type.',
      'Create incident response runbooks for three common scenarios: (1) compromised AWS IAM credentials (access key exposed on GitHub), (2) web application data breach (SQL injection leading to PII exfiltration), (3) ransomware on a server (encrypted files, ransom note). Each runbook should cover detection indicators, immediate containment steps, investigation procedures, eradication steps, and recovery plan.',
      'Conduct a tabletop exercise: simulate a security incident (e.g., an alert that an IAM access key is being used from an unusual country) and walk through your incident response process. Document: what information you need to triage the alert, what tools you would use for investigation, what containment actions you would take, and what your communication plan would be.',
      '★ Build detection rules for five MITRE ATT&CK techniques relevant to your environment. For each technique, specify: the data source needed (CloudTrail, application logs, VPC Flow Logs), the detection logic (specific log fields and values to match), expected false positive sources and how to tune them out, and the response action when the rule fires.',
      'Write a post-incident report template and fill it in for a simulated or historical incident. Include: incident timeline, root cause analysis, impact assessment, detection and response evaluation (what worked, what was slow, what was missed), and specific remediation actions with owners and deadlines.',
    ],
  },
};
