export const PHASE1_CONTENT: Record<number, { lectureEn: string; practiceEn: string[] }> = {
  1: {
    lectureEn: `Everything in network security starts with understanding how data actually moves between machines. The OSI model gives you seven conceptual layers -- Physical, Data Link, Network, Transport, Session, Presentation, Application -- but in practice, you will work with the TCP/IP model which collapses these into four: Link, Internet, Transport, and Application. The reason this matters for security is that attacks exploit the boundaries and assumptions at each layer. ARP spoofing happens at Layer 2 because the protocol trusts any machine that claims to own an IP. IP spoofing is possible because the source address field in an IP packet is just a number that the sender fills in -- nothing in the protocol verifies it. Understanding these trust assumptions is the foundation of offensive and defensive security alike.

TCP is the workhorse of the internet, and you need to understand its three-way handshake (SYN, SYN-ACK, ACK) not as a textbook diagram but as something you can observe byte-by-byte in Wireshark. Each TCP connection moves through states: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, TIME_WAIT, CLOSE_WAIT, LAST_ACK, CLOSED. When you see a server with thousands of connections stuck in CLOSE_WAIT, that is a resource leak -- the application is not closing sockets. When you see thousands of SYN_RECEIVED connections, that could be a SYN flood attack. The state machine is not academic; it directly tells you what is happening on a system under stress or attack.

UDP is simpler -- no handshake, no guaranteed delivery, no connection state. DNS, DHCP, and many streaming protocols use UDP. From a security perspective, UDP's lack of a handshake makes it trivially spoofable: you can send a UDP packet with a forged source IP and the receiver has no way to verify it. This is why DNS amplification attacks work -- an attacker sends a small DNS query with the victim's IP as the source, and the DNS server sends a large response to the victim. ICMP is another protocol you should understand: it carries error messages and diagnostic tools like ping and traceroute. ICMP can be abused for reconnaissance (ping sweeps to find live hosts), covert channels (tunneling data inside ICMP echo payloads), and denial of service.

NAT (Network Address Translation) sits at the boundary between private and public networks. Your home router uses NAT to allow multiple devices to share a single public IP. From a security standpoint, NAT provides incidental protection -- unsolicited inbound connections cannot reach devices behind NAT because the router has no translation entry for them. But NAT is not a firewall, and techniques like NAT slipstreaming have shown that a malicious web page can trick a browser into creating NAT mappings that expose internal services. Understanding routing -- how packets find their path through networks via routing tables, default gateways, and protocols like BGP -- completes the picture. BGP hijacking, where an attacker announces routes for IP prefixes they do not own, has been used to redirect traffic for cryptocurrency theft and surveillance.

Wireshark is your primary tool for this week. It is a packet analyzer that captures and dissects network traffic at every protocol layer. You will use it constantly throughout this program -- for analyzing HTTP requests, debugging TLS handshakes, spotting anomalous traffic patterns, and understanding exactly what is on the wire. Learning Wireshark's display filters (e.g., tcp.flags.syn == 1 && tcp.flags.ack == 0 to find initial SYN packets) is as important as learning grep for a Linux administrator. Public pcap repositories like Wireshark's own SampleCaptures page and malware-traffic-analysis.net provide real-world captures you can practice on without generating any traffic yourself.`,
    practiceEn: [
      'Install Wireshark on your machine. Open a capture on your primary network interface and browse to https://example.com. Stop the capture after 60 seconds. Use the display filter "tcp.port == 443" to isolate the connection. Find the three-way handshake (SYN, SYN-ACK, ACK) and note the sequence numbers, window sizes, and TCP options (MSS, SACK, window scaling) negotiated during the handshake. Export these three packets as a separate pcap file.',
      'Download a sample pcap from https://wiki.wireshark.org/SampleCaptures (choose "http.cap" or "telnet-cooked.pcap"). Open it in Wireshark and use "Follow TCP Stream" on one of the conversations. Examine the raw ASCII data exchanged. For the HTTP capture, identify request methods, response codes, and any cookies or authentication headers. Write a short annotation (5-10 lines) per stream explaining what happened.',
      'Run "netstat -an" (Windows) or "ss -tunapl" (Linux) on your machine and identify all listening TCP and UDP ports. For each listening port, determine which process owns it. Cross-reference with Wireshark: start a capture filtered to one of those ports (e.g., tcp.port == 5432 for PostgreSQL) and trigger some traffic. Observe the handshake and data exchange.',
      'Using tcpdump on a Linux VM (or Wireshark CLI "tshark"), capture ICMP traffic while running "ping -c 10 8.8.8.8" and "traceroute 8.8.8.8" simultaneously from another terminal. Examine the ICMP types and codes in the capture. Identify how traceroute uses incrementing TTL values and ICMP Time Exceeded messages to map the route.',
      'Open Wireshark and capture traffic while performing a DNS lookup with "nslookup example.com" or "dig example.com". Apply the display filter "dns" and examine the query and response packets. Note the transaction ID, query type (A, AAAA), the response IP addresses, and the TTL value. Then try "dig example.com ANY" and compare the difference in response size -- this illustrates why ANY queries were historically used in DNS amplification attacks.',
    ],
  },
  2: {
    lectureEn: `HTTP is the protocol you will attack and defend more than any other in your AppSec career, so you need to understand it at the byte level, not just as something your browser handles transparently. HTTP/1.1 is a text-based protocol: a request is literally "GET /path HTTP/1.1\\r\\n" followed by headers as "Key: Value\\r\\n" pairs, an empty line, and optionally a body. The method (GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD) determines intent. GET requests should be idempotent and safe -- they should never cause side effects. When a developer puts a delete action behind a GET endpoint, that is a vulnerability because prefetch mechanisms, browser history, and cached proxies can trigger unintended deletions.

Headers carry critical security information. The Host header tells the server which virtual host to serve -- it is attacker-controlled input and the basis of host header injection attacks. The Cookie header carries session tokens -- if it lacks the HttpOnly flag, JavaScript can steal it via XSS. The Content-Type header determines how the server parses the body -- mismatches between Content-Type and actual body format can lead to parser confusion exploits. The Origin and Referer headers are used in CORS and CSRF protection, but both can be manipulated or omitted under certain conditions. Response headers like Set-Cookie (with Secure, HttpOnly, SameSite attributes), Strict-Transport-Security (HSTS), Content-Security-Policy (CSP), and X-Content-Type-Options: nosniff are your defensive tools. Understanding exactly what each header does and when it is sent is fundamental.

CORS (Cross-Origin Resource Sharing) is one of the most commonly misconfigured security mechanisms. The Same-Origin Policy prevents JavaScript on site-a.com from reading responses from site-b.com. CORS relaxes this by letting site-b.com send Access-Control-Allow-Origin headers to whitelist specific origins. The dangerous misconfiguration is reflecting the request's Origin header directly into the response (effectively allowing any origin), or setting Access-Control-Allow-Origin: * with Access-Control-Allow-Credentials: true (which browsers block, but developers often work around incorrectly). You need to be able to spot these misconfigurations in response headers and understand their impact.

HTTP/2 changes the wire format fundamentally: it uses binary framing instead of text, multiplexes multiple streams over a single TCP connection, and supports header compression via HPACK. From a security perspective, HTTP/2 introduces new attack surfaces: HPACK bomb (malicious header compression that expands to exhaust memory), stream prioritization abuse for DoS, and most critically, HTTP/2 downgrade attacks where a frontend speaks HTTP/2 but the backend uses HTTP/1.1, leading to request smuggling vulnerabilities. You do not need to master HTTP/2 internals, but you need to understand that the translation layer between HTTP/2 frontends and HTTP/1.1 backends is a rich source of vulnerabilities.

Burp Suite and Caido are your interception proxies -- they sit between your browser and the server, letting you inspect, modify, and replay every request. Burp Suite Community Edition is the industry standard. Caido is a modern alternative written in Rust with a cleaner UI. Setting these up correctly involves installing the proxy's CA certificate in your browser's trust store (so it can intercept HTTPS by performing a man-in-the-middle), configuring your browser to route traffic through localhost:8080 (Burp's default), and understanding the Proxy, Repeater, and Intruder tabs. From this week forward, every HTTP interaction you analyze should go through your proxy first.`,
    practiceEn: [
      'Install Burp Suite Community Edition and configure Firefox to use it as a proxy (127.0.0.1:8080). Install Burp\'s CA certificate in Firefox\'s certificate store (Settings > Privacy & Security > View Certificates > Import). Verify HTTPS interception works by browsing to https://example.com and confirming the request appears in Burp\'s Proxy > HTTP History tab. Then install Caido (https://caido.io/) and repeat the same setup with a different browser or profile.',
      'Using curl from the command line, craft 10 different HTTP requests manually and analyze the responses. Include: (1) GET with custom User-Agent, (2) POST with JSON body and Content-Type: application/json, (3) PUT request, (4) DELETE request, (5) HEAD request (compare with GET -- no body), (6) OPTIONS request to a CORS-enabled API, (7) GET with If-None-Match for cache validation, (8) POST with application/x-www-form-urlencoded body, (9) GET with Range header for partial content, (10) Request with a forged Origin header. For each, document the response status code, interesting headers, and any security-relevant observations.',
      'Set up a local HTTP server (e.g., "python3 -m http.server 8000") and capture the traffic in Wireshark while making requests via curl. Apply the display filter "http" and use "Follow HTTP Stream" to see the raw text protocol. Observe the literal text of request and response lines, headers, and body. Compare what Wireshark shows with what Burp Suite shows for the same request -- notice how Burp parses and presents the same raw bytes in a more structured way.',
      'Find a public API that supports CORS (e.g., https://api.github.com or https://jsonplaceholder.typicode.com). Using Burp Repeater, send a request with "Origin: https://evil.com" and examine the Access-Control-Allow-Origin response header. Does the server reflect your origin? Does it send Access-Control-Allow-Credentials: true? Document your findings and explain whether this configuration is secure or exploitable.',
      'Using curl with the --http2 flag, connect to a site that supports HTTP/2 (e.g., "curl -v --http2 https://www.google.com"). Compare the verbose output with a plain HTTP/1.1 request ("curl -v --http1.1 https://www.google.com"). Note the differences in the connection negotiation (ALPN protocol negotiation in TLS) and response framing. In Wireshark, capture both connections and observe how HTTP/2 traffic appears as binary frames rather than readable text (filter: "http2").',
    ],
  },
  3: {
    lectureEn: `TLS (Transport Layer Security) is what puts the "S" in HTTPS, and understanding its handshake is essential because so many attacks target this layer. In TLS 1.2, the handshake takes two round trips: the client sends ClientHello (listing supported cipher suites and a random value), the server responds with ServerHello (choosing a cipher suite), its certificate, and a ServerKeyExchange message (for Diffie-Hellman key exchange), then the client verifies the certificate, sends its key exchange parameters, and both sides derive the session keys. TLS 1.3 simplifies this to a single round trip by combining the key exchange and hello messages, removing support for insecure algorithms (RSA key exchange, CBC mode ciphers, SHA-1), and encrypting more of the handshake. The security implication is concrete: TLS 1.3 eliminates entire classes of attacks like BEAST, POODLE, and Lucky13 that exploited CBC mode padding in TLS 1.2.

X.509 certificates are the identity system of TLS. A certificate binds a public key to a domain name, signed by a Certificate Authority (CA). The trust chain works like this: your browser trusts a set of root CAs (preinstalled in the OS or browser). A root CA signs an intermediate CA's certificate, and the intermediate CA signs the server's certificate. When you connect to a site, the server sends its certificate and the intermediate certificate; your browser chains these up to a trusted root. If any link in this chain is missing, expired, revoked, or signed with a weak algorithm, the connection should fail. The real-world attacks here include: compromised CAs (DigiNotar in 2011 was breached and issued fake certificates for google.com, allowing man-in-the-middle attacks on Iranian users), misissued certificates (Symantec was distrusted by browsers for repeatedly issuing unauthorized certificates), and certificate transparency log monitoring (which is why CT logs exist -- to detect unauthorized certificates for your domains).

HSTS (HTTP Strict Transport Security) solves a critical problem: the first time a user visits your site by typing "example.com" in the browser, the browser defaults to HTTP, and an attacker on the network can intercept the HTTP-to-HTTPS redirect (an sslstrip attack). When a site sends the header "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload", the browser remembers for one year to always use HTTPS, even for the first connection. The preload list goes further -- browsers ship with a hardcoded list of HSTS domains, eliminating even the first-visit vulnerability. Certificate pinning (now largely deprecated in favor of Certificate Transparency) was the practice of associating a host with its expected certificate or public key, preventing even CA-level compromises. Expect-CT and Certificate Transparency are the modern replacements.

SNI (Server Name Indication) is a TLS extension that solves the problem of hosting multiple HTTPS domains on a single IP address. The client includes the desired hostname in the ClientHello message (before encryption is established), so the server knows which certificate to present. The security implication is that SNI leaks the destination hostname in plaintext -- anyone monitoring the network can see which site you are connecting to, even if the content is encrypted. Encrypted Client Hello (ECH, formerly ESNI) is the emerging solution, encrypting the SNI field using a key published in DNS. Until ECH is widely deployed, TLS metadata analysis remains a viable surveillance tool.

Mutual TLS (mTLS) flips the script: instead of only the server presenting a certificate, the client also presents one. The server verifies the client's certificate against a trusted CA, authenticating the client at the transport layer. mTLS is widely used for service-to-service authentication in microservices architectures (e.g., Istio service mesh), API security for high-trust integrations, and zero-trust networks. The operational challenge is certificate lifecycle management -- issuing, rotating, and revoking client certificates at scale. Tools like step-ca, Vault PKI, and cert-manager for Kubernetes address this. Understanding mTLS is becoming essential as zero-trust architecture adoption accelerates.`,
    practiceEn: [
      'Use openssl s_client to inspect the TLS handshake of three different sites: "openssl s_client -connect google.com:443 -servername google.com", "openssl s_client -connect github.com:443", and a site you know uses an older TLS configuration. For each, note: the TLS version negotiated, the cipher suite selected, the certificate chain (issuer and subject of each certificate), and the certificate expiration date. Verify the chain with "openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt server.pem".',
      'Create your own mini Certificate Authority using openssl. Generate a root CA key and self-signed certificate ("openssl req -x509 -newkey rsa:4096 -keyout ca.key -out ca.crt -days 365 -nodes"). Then generate a server key and CSR ("openssl req -newkey rsa:2048 -keyout server.key -out server.csr -nodes"), sign it with your CA ("openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 90"), and configure nginx to serve HTTPS using this certificate. Access it from a browser and observe the "untrusted certificate" warning, then install your ca.crt as a trusted root and verify the warning disappears.',
      'Capture a full TLS 1.2 and TLS 1.3 handshake in Wireshark. For TLS 1.2, use "openssl s_client -connect example.com:443 -tls1_2" and for TLS 1.3, use "openssl s_client -connect example.com:443 -tls1_3". In Wireshark (filter: "tls.handshake"), compare: the number of round trips, which messages are encrypted (in TLS 1.3, the Certificate and CertificateVerify are encrypted), and the cipher suites offered vs selected. Write a summary of the differences you observe.',
      'Check three websites of your choice for HSTS configuration. Use curl -I to inspect response headers and look for "Strict-Transport-Security". Check the HSTS preload list at hstspreload.org. For a site without HSTS, demonstrate the risk by using Burp Suite to intercept the initial HTTP redirect (start with http:// not https://) and show how an attacker could modify the response.',
      'Set up mutual TLS using mkcert (https://github.com/FiloSottile/mkcert). Generate a local CA with "mkcert -install", create a server certificate with "mkcert localhost 127.0.0.1", and a client certificate with "mkcert -client localhost". Configure nginx with ssl_verify_client on and ssl_client_certificate pointing to your CA. Test with curl using "--cert client.pem --key client-key.pem" and verify that connections without the client certificate are rejected with HTTP 400.',
    ],
  },
  4: {
    lectureEn: `DNS is the internet's phone book, translating human-readable domain names into IP addresses, but it was designed in 1983 without any security mechanisms -- no authentication, no encryption, no integrity verification. This makes it a remarkably fertile attack surface. Understanding the record types is the starting point: A records map names to IPv4 addresses; AAAA records map to IPv6; CNAME records create aliases; MX records direct email; TXT records hold arbitrary text (used for SPF, DKIM, domain verification); NS records delegate zones to nameservers. Each record type has security implications. A dangling CNAME pointing to a decommissioned cloud service can be taken over by anyone who re-registers that service name. MX records without SPF/DKIM/DMARC allow email spoofing. TXT records sometimes inadvertently leak internal configuration or verification tokens.

The DNS resolution process involves recursive and authoritative servers. When you type "app.example.com" in your browser, your stub resolver asks a recursive resolver (like 8.8.8.8 or your ISP's server), which queries the root nameservers, then the .com TLD servers, then example.com's authoritative nameservers. Each step is a UDP query-response pair with no authentication. DNS cache poisoning (the Kaminsky attack, discovered in 2008) exploits this: an attacker races to inject a forged DNS response before the legitimate one arrives, poisoning the recursive resolver's cache. If successful, all users of that resolver are directed to the attacker's IP for the poisoned domain. The attack was possible because DNS transaction IDs are only 16 bits and responses were accepted on predictable source ports. Modern resolvers randomize source ports and use other mitigations, but the fundamental weakness -- unsigned responses -- remains without DNSSEC.

DNSSEC adds cryptographic signatures to DNS records, allowing resolvers to verify that responses are authentic and unmodified. The chain of trust starts from the DNS root zone (signed by ICANN) down through each delegated zone. In practice, DNSSEC adoption is incomplete (many domains do not sign their zones, and many resolvers do not validate signatures), and DNSSEC introduces its own issues: larger response sizes (enabling amplification attacks), key management complexity, and zone enumeration via NSEC records (which reveal all records in a zone unless NSEC3 is used). Despite these limitations, DNSSEC is the only standard mechanism to authenticate DNS responses, and you should understand both its value and its operational challenges.

DNS rebinding is a clever attack that bypasses the browser's Same-Origin Policy. The attacker controls a domain with a very short TTL. The first DNS response points to the attacker's server, which serves malicious JavaScript. Before the JavaScript makes its next request, the DNS record is changed to point to an internal IP (e.g., 192.168.1.1 -- the victim's router). The browser considers this the same origin (same domain name) and allows the JavaScript to interact with the internal service. This can be used to reconfigure routers, access internal APIs, or exfiltrate data from the local network. Defenses include DNS pinning (browsers caching the first IP), private network access restrictions, and configuring internal services to reject requests with unexpected Host headers.

DNS exfiltration uses DNS queries themselves as a data channel. Since DNS traffic is almost always allowed through firewalls, an attacker can encode stolen data as subdomain labels: "dGhpcyBpcyBzZWNyZXQ.evil.com" -- the base64-encoded data appears as a subdomain in a DNS query to the attacker's authoritative server. Tools like dnscat2 and iodine build full bidirectional tunnels over DNS. From a defensive perspective, detecting DNS exfiltration requires monitoring for anomalously long subdomain labels, high query volumes to unusual domains, or TXT record queries to suspicious destinations. DNS over HTTPS (DoH) and DNS over TLS (DoT) encrypt DNS traffic between the client and the recursive resolver, preventing eavesdropping and tampering by on-path attackers, but they also prevent network-based DNS monitoring tools from inspecting queries -- a trade-off that security teams must understand.`,
    practiceEn: [
      'Perform a comprehensive DNS enumeration of a domain you control (or a permissive target like scanme.nmap.org). Use dig to query each record type: "dig example.com A", "dig example.com AAAA", "dig example.com MX", "dig example.com NS", "dig example.com TXT", "dig example.com SOA", "dig example.com CNAME". Then use "dig +trace example.com" to observe the full recursive resolution path from root servers to the authoritative answer. Document each step of the delegation chain.',
      'Set up a local DNS server using dnsmasq or BIND9 in a Docker container. Configure it as a recursive resolver for your local network and add a custom zone file with A, CNAME, MX, and TXT records for a test domain (e.g., test.lab). Query your server with dig ("dig @localhost test.lab A") and verify your records resolve correctly. Then inspect the query logs to see what recursive resolution looks like from the server side.',
      'Install dnscat2 (https://github.com/iagox86/dnscat2) and set up a DNS tunnel on your local testbed. Run the dnscat2 server on one machine (or container) configured as the authoritative nameserver for a test domain. Run the dnscat2 client on another machine. Establish a session and transfer a small text file through the tunnel. Capture the DNS traffic in Wireshark and observe how the data is encoded in DNS query labels. Note the query types used (TXT, CNAME, MX) and the pattern of communication.',
      'Write a Python script using the dnspython library that takes a domain name as input and performs a security-focused DNS audit: checks for SPF records (TXT records starting with "v=spf1"), DMARC records (_dmarc subdomain TXT), DKIM selectors (common ones like google._domainkey), DNSSEC presence (RRSIG records via "dig +dnssec"), dangling CNAMEs (resolve the CNAME target and report if it fails), and zone transfer attempt ("dig @ns1.example.com example.com AXFR"). Test your script against 5 real domains and document the findings.',
      'Research and demonstrate DNS rebinding conceptually: using dig, set a very low TTL (e.g., 1 second) on an A record for a domain you control ("dig @your-ns test.yourdomain.com" showing TTL=1). Explain in writing how an attacker would use this to pivot from external JavaScript to an internal IP address. List three defenses: browser DNS pinning behavior, Private Network Access specification in browsers, and validating Host headers on internal services. Test whether your browser respects the short TTL by running "dig test.yourdomain.com" twice with a record change in between.',
    ],
  },
  5: {
    lectureEn: `Linux privilege escalation is one of the most practical skills in security, and it starts with understanding how Linux manages identity. Every process runs under a user ID (UID) and group ID (GID). UID 0 is root -- unrestricted access to everything. The real UID identifies who launched the process, while the effective UID determines what permissions it actually has. This distinction exists because of SUID (Set User ID): when a binary has the SUID bit set (chmod u+s), it runs with the effective UID of the file owner, not the user who executed it. The classic example is /usr/bin/passwd -- it needs to write to /etc/shadow (owned by root), so it has SUID root. But if any SUID root binary has a vulnerability -- a buffer overflow, a command injection, an unrestricted file read -- it becomes a privilege escalation vector. Finding SUID binaries is the first thing an attacker does after gaining initial access: "find / -perm -4000 -type f 2>/dev/null".

SGID (Set Group ID) works similarly but for group permissions. The sticky bit on directories (like /tmp) prevents users from deleting files they do not own. Linux capabilities split root's monolithic power into granular units: CAP_NET_BIND_SERVICE lets a process bind to ports below 1024 without being root; CAP_DAC_READ_SEARCH lets a process bypass file read permission checks; CAP_SYS_ADMIN is a catch-all that grants nearly root-level power. From a security perspective, capabilities are a double-edged sword: they enable running services with minimal privileges, but misconfigured capabilities (especially on binaries accessible to unprivileged users) create privilege escalation paths that are harder to spot than traditional SUID.

The files /etc/passwd and /etc/shadow are the heart of local authentication. /etc/passwd is world-readable and contains username, UID, GID, home directory, and shell for each user -- but the password field shows "x", indicating the actual password hash is in /etc/shadow. /etc/shadow is readable only by root and contains the hashed password, last change date, and aging policy. The hash format "$6$salt$hash" indicates SHA-512 (the "6"); "$y$" indicates yescrypt (modern Debian/Ubuntu). If an attacker can read /etc/shadow -- via a file read vulnerability, backup exposure, or misconfigured permissions -- they can attempt offline password cracking with hashcat or john. PAM (Pluggable Authentication Modules) is the framework that mediates all authentication: login, su, sudo, SSH. PAM configuration in /etc/pam.d/ defines the authentication stack -- which modules run, in what order, and whether they are required or optional. Misconfigured PAM can completely bypass authentication.

Namespaces and cgroups are the Linux kernel features that make containers possible, and understanding them is essential for modern security work. A namespace isolates a process's view of a system resource: PID namespaces give a process its own process ID space (PID 1 inside the container); network namespaces give it its own network stack; mount namespaces give it its own filesystem view; user namespaces allow mapping UID 0 inside the container to an unprivileged UID outside. Cgroups limit resource consumption: CPU time, memory, I/O bandwidth, number of processes. A container is just a process running in a set of namespaces with cgroup limits -- there is no hypervisor, no separate kernel. This means container escapes are possible: if a container runs as root (UID 0 mapped to UID 0 on the host), has access to the host's filesystem via a bind mount, or has dangerous capabilities like CAP_SYS_ADMIN, it can break out of its isolation.

The practical takeaway for your security career is this: every time you audit a Linux system, you should check for SUID/SGID binaries in non-standard locations, writable cron jobs and systemd timers, misconfigured sudo rules (especially NOPASSWD entries and binaries that can escape to a shell), world-readable sensitive files, kernel version (for known privilege escalation CVEs), Docker socket access (/var/run/docker.sock writable by your user means instant root), and capabilities on binaries. Tools like linpeas.sh and LinEnum automate these checks, but understanding the underlying mechanisms lets you find what automated tools miss.`,
    practiceEn: [
      'On a Linux VM (any distro), enumerate all SUID binaries: "find / -perm -4000 -type f 2>/dev/null". For each binary found, check GTFOBins (https://gtfobins.github.io/) to determine if it can be abused for privilege escalation. Pick one SUID binary that has a GTFOBins entry (e.g., find, vim, python) and demonstrate the escalation in your VM. Document the exact commands used.',
      'Examine the authentication files on your Linux VM. Read /etc/passwd and identify all user accounts with UID 0 (root-equivalent), accounts with login shells vs /usr/sbin/nologin, and accounts with home directories in unusual locations. Attempt to read /etc/shadow as a non-root user (it should fail). Then, as root, examine the password hash format for your user account -- identify the algorithm identifier ($6$ = SHA-512, $y$ = yescrypt, etc.). Use "passwd -S username" to check the password status for several accounts.',
      'Explore Linux capabilities: run "getcap -r / 2>/dev/null" to find all binaries with file capabilities. Create a test scenario: copy /usr/bin/python3 to /tmp/python3_cap, set CAP_DAC_READ_SEARCH on it ("sudo setcap cap_dac_read_search+ep /tmp/python3_cap"), then use it as an unprivileged user to read /etc/shadow ("./python3_cap -c \'print(open(\"/etc/shadow\").read())\'"). This demonstrates why capabilities on user-accessible binaries are dangerous. Clean up by removing the binary afterward.',
      'Set up a Docker container scenario that demonstrates namespace isolation. Run "docker run --rm -it ubuntu bash" and inside the container: check your UID ("id"), list processes ("ps aux" -- you only see container processes), check the hostname, and attempt to access the host filesystem. Then run a container with weakened isolation: "docker run --rm -it --pid=host --privileged ubuntu bash" and repeat the same checks -- observe that you can now see host processes and have root-level access to the host. Document the security implications.',
      'Download and run linpeas.sh (https://github.com/peass-ng/PEASS-ng) on a Linux VM where you have a non-root user account. Read through the output carefully -- it highlights potential privilege escalation vectors in red and yellow. Focus on sections: SUID binaries, sudo configuration, writable files in PATH directories, cron jobs, kernel exploits, and Docker group membership. For each finding linpeas highlights, explain in one sentence why it is a security risk.',
      'Configure PAM to understand its authentication flow. Read /etc/pam.d/sudo and /etc/pam.d/login. Identify the module stack (pam_unix, pam_env, pam_permit, etc.) and the control flags (required, sufficient, optional). On a test VM, create a scenario where you add "auth sufficient pam_permit.so" as the first line in /etc/pam.d/sudo -- this allows passwordless sudo for everyone. Test it, document the behavior, then immediately revert the change. This demonstrates how a single PAM misconfiguration can completely bypass authentication.',
    ],
  },
  6: {
    lectureEn: `The Linux filesystem is not just files and directories -- it is a sophisticated data structure that security professionals must understand. Every file and directory is backed by an inode, a data structure containing metadata: ownership, permissions, timestamps, size, and pointers to data blocks. The filename itself is just an entry in a directory that maps a human-readable name to an inode number. This matters for security because hard links create multiple directory entries pointing to the same inode -- deleting one link does not remove the file until all links are gone. Symlinks (symbolic links) are different: they point to a path, not an inode. Symlink attacks are a classic vulnerability class: a privileged process writing to /tmp/predictable_name can be tricked if an attacker creates a symlink at that path pointing to /etc/shadow -- the process follows the symlink and overwrites the password file. The O_NOFOLLOW flag and sticky bit on /tmp are defenses against this.

Mount points deserve attention because they define the filesystem topology and have security-relevant options. The "noexec" mount option prevents execution of binaries on that partition (useful for /tmp). "nosuid" ignores SUID bits on mounted filesystems (critical for removable media). "nodev" prevents device file creation. You can check current mount options with "mount | grep /tmp" or "findmnt". In containerized environments, bind mounts from the host into the container can expose sensitive host directories. A common Docker security mistake is mounting /var/run/docker.sock into a container -- anyone inside the container can now control Docker and effectively has root on the host.

Logging is your forensic trail. Linux offers multiple logging systems that overlap: journald (systemd's binary log, queried with journalctl), syslog/rsyslog (text-based, typically writing to /var/log/), and the kernel ring buffer (dmesg). For security, the most important logs are auth.log (or secure on RHEL) for authentication events (SSH logins, sudo usage, failed passwords), kern.log for kernel messages (including AppArmor/SELinux denials), and application-specific logs. Auditd is the Linux Audit Framework -- a kernel-level auditing system that can monitor specific system calls, file accesses, and user actions. An auditd rule like "auditctl -w /etc/shadow -p wa -k shadow_changes" logs every write or attribute change to /etc/shadow. The audit log (/var/log/audit/audit.log) is the primary evidence source in incident response on Linux. Learning to write audit rules and parse audit logs with ausearch and aureport is an essential skill.

The Linux network stack provides several built-in security tools. iptables (legacy) and nftables (modern replacement) are the kernel's packet filtering framework. An iptables rule like "iptables -A INPUT -p tcp --dport 22 -s 10.0.0.0/8 -j ACCEPT" followed by "iptables -A INPUT -p tcp --dport 22 -j DROP" allows SSH only from the 10.0.0.0/8 network. Understanding the chain model (INPUT for incoming, OUTPUT for outgoing, FORWARD for routed traffic) and the table model (filter, nat, mangle) lets you audit and configure host-based firewalls. The ss command (replacement for netstat) shows socket statistics: "ss -tunapl" lists all TCP and UDP listening sockets with their associated processes. This is your first check when assessing what services a machine exposes. tcpdump is the command-line packet capture tool -- lighter than Wireshark and available on servers where you cannot run a GUI. A command like "tcpdump -i eth0 -nn 'port 80 or port 443' -w capture.pcap" captures web traffic for later analysis.

Systemd manages almost everything on modern Linux. Understanding unit files (.service, .timer, .socket) matters for security because: misconfigured service files can run processes as root unnecessarily, timer files (cron replacement) can be abused for persistence if writable, and socket-activated services define how network connections are handled. The command "systemctl list-units --type=service --state=running" shows active services, and examining their unit files (systemctl cat servicename) reveals the user they run as, their capabilities, their filesystem restrictions, and their restart behavior. Systemd also supports sandboxing directives like ProtectSystem, ProtectHome, NoNewPrivileges, and PrivateTmp that restrict what a service can access -- these are often left unconfigured, leaving services with more privileges than they need.`,
    practiceEn: [
      'Write a bash script called "security-monitor.sh" that performs the following checks and outputs a report: (1) Find all SUID files created or modified in the last 24 hours: "find / -perm -4000 -mtime -1 2>/dev/null". (2) List all files changed in /etc in the last 24 hours: "find /etc -mtime -1 -type f 2>/dev/null". (3) List all listening TCP/UDP ports and their owning processes: "ss -tunapl". (4) Check for world-writable files in system directories: "find /usr /etc /var -perm -o+w -type f 2>/dev/null". (5) Show recent failed SSH login attempts: "grep \'Failed password\' /var/log/auth.log | tail -20". Make the script executable and run it on your Linux VM.',
      'Set up auditd on your Linux VM. Install it if needed ("sudo apt install auditd"). Add three audit rules: (1) monitor changes to /etc/passwd: "sudo auditctl -w /etc/passwd -p wa -k passwd_changes", (2) monitor execution of binaries in /tmp: "sudo auditctl -w /tmp -p x -k tmp_execution", (3) monitor sudo usage: "sudo auditctl -w /var/log/auth.log -p wa -k auth_log". Then trigger each rule: edit /etc/passwd, run a script from /tmp, use sudo. Search the audit log with "sudo ausearch -k passwd_changes" and "sudo aureport --auth". Document what each audit event shows.',
      'Practice with iptables by creating a set of firewall rules on your VM. Start with "sudo iptables -L -n" to see current rules. Then: (1) Allow SSH from only your IP: "sudo iptables -A INPUT -p tcp --dport 22 -s YOUR_IP -j ACCEPT", (2) Drop all other SSH: "sudo iptables -A INPUT -p tcp --dport 22 -j DROP", (3) Allow established connections: "sudo iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT", (4) Log dropped packets: "sudo iptables -A INPUT -j LOG --log-prefix \'DROPPED: \'". Test by trying to SSH from a different source. Check /var/log/kern.log for the LOG entries. Flush rules when done: "sudo iptables -F".',
      'Examine systemd service security. Pick three running services on your VM (e.g., sshd, cron, a database). For each: (1) show the unit file: "systemctl cat servicename", (2) check which user it runs as, (3) check for sandboxing directives (ProtectSystem, ProtectHome, NoNewPrivileges, PrivateTmp, CapabilityBoundingSet), (4) run "systemd-analyze security servicename" which gives a security exposure score from 0 (safest) to 10 (most exposed). Document the score and the top 3 missing protections for each service.',
      'Demonstrate a symlink attack scenario on your VM. Create a directory /tmp/symlink_lab/. As a non-root user, create a script that writes to a predictable filename in /tmp: "echo data > /tmp/symlink_lab/output.txt". Then, before the script runs, replace /tmp/symlink_lab/output.txt with a symlink to a file you want to overwrite (in your own home directory for safety). Run the script again and observe that it follows the symlink and overwrites the target. Then demonstrate the defense: rewrite the script to use mktemp for unpredictable filenames and O_NOFOLLOW behavior (in Python: os.open with os.O_NOFOLLOW).',
    ],
  },
  7: {
    lectureEn: `Bash scripting is not glamorous, but it is the language of system administration and the glue that holds security tooling together. As a security engineer, you will write bash scripts daily -- to automate reconnaissance, parse log files, chain tools together, and create quick proof-of-concept exploits. The features you need to master go beyond basic scripting. Pipes connect the stdout of one command to the stdin of the next: "cat access.log | grep 'POST /login' | awk '{print $1}' | sort | uniq -c | sort -rn | head -20" gives you the top 20 IPs hitting your login endpoint. Process substitution (<() and >()) lets you use command output as a file argument: "diff <(ssh server1 cat /etc/passwd) <(ssh server2 cat /etc/passwd)" compares passwd files across servers without temporary files.

Here-documents (<<EOF) let you embed multi-line text in scripts, useful for generating payloads or configuration files. Traps (trap 'cleanup' EXIT) ensure your script cleans up temporary files and kills background processes even if it is interrupted -- essential for security tools that create listeners or temporary credentials. Error handling with "set -euo pipefail" makes scripts fail fast on errors instead of silently continuing with corrupt state: -e exits on any command failure, -u treats unset variables as errors (preventing injection through undefined variables), -o pipefail makes pipes return the exit code of the first failed command. In security tooling, silent failures can mean missed vulnerabilities or incomplete scans.

Python is your primary language for writing security tools that go beyond simple shell scripts. The requests library is your HTTP client -- it handles cookies, redirects, sessions, and authentication. For security testing, you will write scripts that iterate over parameter values, fuzz input fields, check for access control bypasses, and validate security headers across hundreds of endpoints. The argparse module gives your tools proper command-line interfaces with help text, required arguments, and type validation -- this matters because security tools are often shared with teammates and used months after they are written. Socket programming with Python's socket module lets you build custom network clients and servers: TCP scanners, banner grabbers, reverse shells (for authorized testing), and protocol fuzzers. The ssl module wraps sockets with TLS, letting you programmatically check certificate details, supported cipher suites, and TLS versions.

JSON processing is everywhere in security work -- API responses, configuration files, tool outputs, and log formats. Python's json module handles parsing and serialization, but for security testing, you often need to manipulate JSON in specific ways: adding unexpected fields to test mass assignment, changing data types to test type confusion, embedding payloads in string values. The jq command-line tool complements Python for quick JSON manipulation in bash pipelines. Log parsing is another daily task: writing Python scripts that process auth.log, web server access logs, or application logs to extract indicators of compromise, calculate statistics, or correlate events across multiple log sources.

The combination of bash and Python creates a powerful security automation workflow. Bash excels at chaining existing tools, file manipulation, and system-level tasks. Python excels at HTTP interaction, complex logic, data processing, and creating reusable tools. A typical security assessment might involve: a bash script that runs nmap, extracts open ports, and pipes them to a Python script that tests each service for known vulnerabilities, outputs findings as JSON, and generates an HTML report. Learning to move fluidly between bash and Python -- knowing when to use which -- is what separates productive security engineers from those who struggle with tooling.`,
    practiceEn: [
      'Write a bash script called "web-recon.sh" that takes a domain as an argument and performs automated reconnaissance: (1) DNS lookups for A, MX, NS, and TXT records using dig, (2) subdomain enumeration using a wordlist and dig ("for sub in $(cat subdomains.txt); do dig +short $sub.domain; done"), (3) HTTP header checks on discovered hosts using curl -I, (4) certificate information extraction using "echo | openssl s_client -connect host:443 2>/dev/null | openssl x509 -noout -subject -issuer -dates". Use proper error handling (set -euo pipefail), traps for cleanup, and output results to a timestamped file. Create a small subdomains.txt wordlist with entries like www, mail, api, dev, staging, admin.',
      'Write a Python script called "header_checker.py" that takes a file of URLs (one per line) as input and checks each URL for security headers. For each URL, use the requests library to fetch the response and check for: Strict-Transport-Security, Content-Security-Policy, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy, and whether cookies have Secure, HttpOnly, and SameSite attributes. Output a formatted table showing which headers are present, missing, or misconfigured. Use argparse for CLI arguments and handle connection errors gracefully.',
      'Write a Python script called "log_analyzer.py" that parses an nginx access log file (Common Log Format). The script should: (1) count requests per IP address and show the top 10, (2) count requests per status code, (3) identify all IPs that received 401 or 403 responses (potential brute force or access control testing), (4) find all requests to paths containing common attack patterns (../,  /etc/passwd, SELECT, UNION, <script>), (5) calculate requests-per-minute for each IP to detect automated scanning. Use argparse for the log file path and output format (text or JSON). Test with a sample log file you generate or download.',
      'Build a Python TCP port scanner using the socket module. The script should take a target IP and port range as arguments, attempt TCP connections with a configurable timeout (default 1 second), report open ports with service names (using socket.getservbyport()), and support concurrent scanning using threading or concurrent.futures for speed. Add a banner-grabbing feature: for open ports, read the first 1024 bytes of data sent by the service. Include proper error handling, a progress indicator, and respect rate limits with a configurable delay between connections.',
      'Combine bash and Python in a pipeline: write a bash script that runs "ss -tunapl" to list all listening ports, pipes the output to a Python script that parses it, extracts the port numbers and process names, performs a lookup of each port in a "known-vulnerable-services.json" file you create (e.g., {"21": "FTP - plaintext credentials", "23": "Telnet - plaintext", "3306": "MySQL - check for remote root"}), and outputs a risk assessment. This demonstrates the bash-Python pipeline pattern used in real security automation.',
    ],
  },
  8: {
    lectureEn: `Active Directory (AD) is the backbone of enterprise authentication on Windows networks, and understanding it is essential even if you primarily work with web applications, because most corporate environments use AD for single sign-on, and compromising AD means compromising everything. An AD domain is a logical grouping of objects -- users, computers, groups, organizational units -- managed by Domain Controllers (DCs). The DC holds the ntds.dit database, which contains all user password hashes. Multiple domains can be connected via trusts into forests. The key principle to grasp is that AD is fundamentally a database of identity and permissions that every Windows machine in the domain queries for authentication and authorization decisions.

NTLM (NT LAN Manager) is the legacy authentication protocol that refuses to die. In NTLM authentication, the server sends a challenge, the client hashes the challenge with the user's password hash (the NT hash, which is just the MD4 of the Unicode password -- no salt), and sends the response. The critical security property of NTLM is that possessing the NT hash is equivalent to possessing the password for authentication purposes -- this is "pass the hash." If an attacker extracts NT hashes from memory (using tools like mimikatz, which reads the LSASS process), they can authenticate to any service that accepts NTLM without knowing the actual password. NTLM also lacks mutual authentication -- the client cannot verify the server's identity, enabling relay attacks where an attacker captures an authentication attempt and relays it to a different server.

Kerberos is AD's primary authentication protocol and significantly more secure than NTLM, but it has its own well-known attack surface. In Kerberos, the user authenticates to the Key Distribution Center (KDC, which runs on the DC) and receives a Ticket Granting Ticket (TGT). To access a service, the user presents the TGT to the KDC and receives a Service Ticket. The attacks you need to understand conceptually are: Kerberoasting -- any domain user can request service tickets for service accounts, and the tickets are encrypted with the service account's password hash, so they can be cracked offline. AS-REP Roasting -- if a user account has "Do not require Kerberos preauthentication" set (a common misconfiguration), anyone can request an AS-REP encrypted with that user's hash and crack it offline. Golden Ticket -- if an attacker obtains the KRBTGT account's hash (by compromising a DC), they can forge TGTs for any user, including non-existent ones, with any group memberships, essentially owning the domain indefinitely until the KRBTGT password is changed twice.

SIDs (Security Identifiers) uniquely identify every security principal (user, group, computer) in Windows. The format S-1-5-21-domainID-RID includes a domain-specific portion and a Relative Identifier. Well-known SIDs like S-1-5-18 (SYSTEM) and S-1-5-32-544 (Administrators group) are universal. ACLs (Access Control Lists) on every object define who can do what: DACLs contain Access Control Entries (ACEs) that grant or deny specific permissions. The ACL model is powerful but complex, and misconfigurations are common attack vectors. An ACE granting a helpdesk group "WriteDACL" permission on user objects means the helpdesk can grant themselves any permission on those users -- including resetting passwords. Tools like BloodHound map these ACL relationships to find attack paths from any compromised user to Domain Admin.

Group Policy Objects (GPOs) push configuration to domain-joined machines: password policies, software installation, firewall rules, security settings. From an attacker's perspective, GPOs stored in the SYSVOL share on DCs sometimes contain credentials in XML files (the cpassword field, encrypted with a publicly known AES key -- MS14-025). PowerShell is the native scripting and administration tool for Windows -- it provides direct access to .NET, WMI, COM objects, and the Active Directory module. For security work, PowerShell can query AD ("Get-ADUser -Filter * -Properties PasswordLastSet"), enumerate shares ("Get-SmbShare"), examine ACLs ("Get-Acl"), and much more. Offensive tools like PowerView and defensive tools like PSScriptAnalyzer are both written in PowerShell.`,
    practiceEn: [
      'Draw a detailed diagram of the Kerberos authentication flow: Client -> KDC (AS-REQ/AS-REP for TGT) -> Client -> KDC (TGS-REQ/TGS-REP for Service Ticket) -> Client -> Service Server (AP-REQ/AP-REP). For each step, note: what is encrypted, with which key, and what information the message contains. Then add annotations showing where each major attack (Kerberoasting, AS-REP Roasting, Golden Ticket, Silver Ticket, Pass-the-Ticket) intercepts or abuses the flow.',
      'Research and write a detailed description (1 page each) of three classic AD attacks: (1) Kerberoasting -- how a domain user requests service tickets, extracts them, and cracks them offline with hashcat; include the SPNs (Service Principal Names) concept. (2) AS-REP Roasting -- how the "Do not require Kerberos preauthentication" flag enables offline cracking; include the LDAP query to find vulnerable accounts. (3) Golden Ticket -- how compromising the KRBTGT hash gives persistent domain access; include why the KRBTGT password must be changed TWICE to invalidate golden tickets.',
      'Install a Windows Server evaluation VM (available free from Microsoft) and set up a basic AD domain lab. Create a domain controller, join a Windows 10 client to the domain, create five user accounts with different group memberships (Domain Admins, Domain Users, a custom "Helpdesk" group). On the domain controller, open Active Directory Users and Computers, right-click a user, go to Properties > Security > Advanced, and examine the ACL entries. Identify which groups have what permissions. This hands-on experience with the AD GUI makes the abstract concepts concrete.',
      'If you have the AD lab from step 3, run "Get-ADUser -Filter * -Properties PasswordLastSet,PasswordNeverExpires,Enabled | Select-Object Name,PasswordLastSet,PasswordNeverExpires,Enabled | Format-Table" in PowerShell on the DC. Then run "Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true}" to find AS-REP Roastable accounts. Run "Get-ADUser -Filter {ServicePrincipalName -ne \'$null\'} -Properties ServicePrincipalName" to find Kerberoastable accounts. If you do not have the lab, study the output format of these commands from HackTricks (https://book.hacktricks.wiki/) and explain what each field means.',
      'Complete the "Active Directory Basics" room on TryHackMe (https://tryhackme.com/room/activedirectorybasics) or the equivalent free resource. Document your progress and key takeaways. Focus on understanding the relationship between domain trusts, organizational units, group policy inheritance, and how these structural elements create security boundaries (or fail to).',
    ],
  },
  9: {
    lectureEn: `Symmetric encryption uses the same key for both encryption and decryption. AES (Advanced Encryption Standard) is the dominant symmetric cipher, operating on 128-bit blocks with key sizes of 128, 192, or 256 bits. But AES itself is just a block cipher -- it encrypts exactly one 16-byte block. How you combine it with data larger than 16 bytes is the "mode of operation," and this is where catastrophic mistakes happen. ECB (Electronic Code Book) encrypts each block independently with the same key. This means identical plaintext blocks produce identical ciphertext blocks, preserving patterns. The classic demonstration is encrypting a bitmap image with ECB -- the penguin's outline remains visible in the ciphertext. ECB is never appropriate for data longer than one block, yet it appears in production code and exam questions regularly.

CBC (Cipher Block Chaining) fixes ECB's pattern problem by XORing each plaintext block with the previous ciphertext block before encryption. The first block is XORed with an Initialization Vector (IV). CBC is secure when used correctly, but it is vulnerable to the padding oracle attack: if a server reveals whether the padding of a decrypted message is valid (through different error messages or timing differences), an attacker can decrypt the entire message without the key, one byte at a time. The BEAST and Lucky13 attacks exploited CBC in TLS. CTR (Counter) mode turns AES into a stream cipher by encrypting a counter value and XORing the result with plaintext. CTR allows parallel encryption and random access but requires a unique nonce for every message -- reusing a nonce with the same key reveals the XOR of two plaintexts, completely breaking confidentiality. GCM (Galois/Counter Mode) combines CTR encryption with authentication, producing both ciphertext and an authentication tag. GCM is the recommended mode for most applications because it provides both confidentiality and integrity, but nonce reuse in GCM is even more catastrophic than in CTR -- it reveals the authentication key, allowing forgery.

RSA is the most widely known asymmetric algorithm. It is based on the difficulty of factoring the product of two large primes. A key pair consists of a public key (n, e) for encryption and a private key (n, d) for decryption. RSA can be used for encryption (send a message only the key owner can decrypt) and signing (prove a message came from the key owner). The fundamental weakness in RSA implementations is key size: 1024-bit RSA is considered broken, and 2048-bit is the minimum for current use. Textbook RSA (no padding) is deterministic and vulnerable to many attacks; OAEP padding for encryption and PSS padding for signatures are required. RSA key generation requires strong random number generators for the primes -- weak randomness leads to factorable keys (the "mining your Ps and Qs" research found that 0.2% of all RSA keys on the internet shared a prime factor due to weak random number generators on embedded devices).

Elliptic Curve Cryptography (ECC) provides the same security level as RSA with much smaller key sizes: a 256-bit ECC key is roughly equivalent to a 3072-bit RSA key. This makes ECC faster and more bandwidth-efficient, which is why modern TLS connections overwhelmingly use ECDHE (Elliptic Curve Diffie-Hellman Ephemeral) for key exchange and ECDSA or EdDSA for signatures. Diffie-Hellman (DH) is a key exchange protocol that allows two parties to establish a shared secret over an insecure channel. The "ephemeral" variants (DHE, ECDHE) generate fresh key pairs for each session, providing forward secrecy: even if the server's long-term private key is later compromised, past session keys cannot be recovered. This is why TLS 1.3 mandates ephemeral key exchange and why RSA key exchange (where the client encrypts the pre-master secret with the server's static public key) was removed -- it does not provide forward secrecy.

Common cryptographic mistakes in real applications include: using ECB mode for multi-block data, reusing nonces in CTR or GCM mode, using MD5 or SHA-1 for security-critical operations (both have practical collision attacks), using random number generators seeded with predictable values (time, PID), implementing crypto from scratch instead of using audited libraries, hardcoding encryption keys in source code, and using encryption without authentication (which enables ciphertext manipulation). The padding oracle attack deserves special attention: it demonstrates that even a single bit of information leakage (valid padding vs. invalid padding) can unravel an entire encrypted message. This is why authenticated encryption (like AES-GCM or ChaCha20-Poly1305) is always preferred over encrypt-only modes.`,
    practiceEn: [
      'Complete Cryptopals Challenge Set 1, Challenges 1 through 4 (https://cryptopals.com/sets/1). Challenge 1 (hex to base64 conversion) teaches you to manipulate raw bytes. Challenge 2 (fixed XOR) shows the fundamental operation behind stream ciphers. Challenge 3 (single-byte XOR cipher) teaches frequency analysis to break substitution ciphers. Challenge 4 (detect single-character XOR) applies this at scale. Implement solutions in Python and write comments explaining the cryptographic principle behind each challenge.',
      'Demonstrate why ECB mode is dangerous. Using Python\'s cryptography library (pip install cryptography), encrypt a 256-byte file containing repeated patterns (e.g., "AAAAAAAAAAAAAAAA" repeated 16 times) with AES-ECB and AES-CBC. Compare the hex output: ECB will show repeated ciphertext blocks, CBC will not. Then download the classic ECB penguin image demonstration: encrypt a PPM bitmap with ECB and CBC, and visually compare the results. Document your code and findings.',
      '★ Implement a simplified padding oracle attack demonstration. Create a Python Flask server that decrypts AES-CBC ciphertext and returns different HTTP status codes: 200 if decryption and padding are valid, 400 if padding is invalid, and 500 for other errors. Then write a client script that uses only the 200/400 distinction to decrypt a ciphertext byte by byte without knowing the key. Use the PyCryptodome library for AES operations. This exercise will take 2-3 hours but will permanently cement your understanding of why encryption without authentication is dangerous.',
      'Use CyberChef (https://gchq.github.io/CyberChef/) to explore cryptographic operations interactively. Perform these exercises: (1) Encrypt text with AES-ECB and AES-CBC, observing the difference. (2) Hash the same text with MD5, SHA-1, SHA-256, and SHA-512, noting output sizes. (3) Generate an RSA key pair, encrypt a short message with the public key, and decrypt with the private key. (4) Demonstrate that changing one bit of input to SHA-256 produces a completely different hash (avalanche effect). Take screenshots of each operation.',
      'Research nonce reuse in AES-GCM. Write a Python script that encrypts two different messages with AES-GCM using the SAME nonce and key. Capture both ciphertexts. Then demonstrate that XORing the two ciphertexts reveals the XOR of the two plaintexts (because the keystream is identical). Write a brief explanation of why this also reveals the authentication key (the GHASH key H), making the integrity guarantee worthless. Include references to real-world incidents of nonce reuse (e.g., the PlayStation 3 ECDSA nonce reuse that exposed Sony\'s private signing key).',
    ],
  },
  10: {
    lectureEn: `Hash functions are the workhorses of modern security -- they appear in password storage, digital signatures, message authentication, data integrity verification, blockchain, and dozens of other applications. A cryptographic hash function takes arbitrary-length input and produces a fixed-length output with three critical properties: preimage resistance (given a hash, you cannot find an input that produces it), second preimage resistance (given an input, you cannot find a different input with the same hash), and collision resistance (you cannot find any two different inputs with the same hash). SHA-2 (SHA-256, SHA-384, SHA-512) is the current standard, producing 256-bit or 512-bit digests. SHA-3 (Keccak) is the backup standard, based on a completely different construction (sponge function vs Merkle-Damgard). BLAKE2 and BLAKE3 are newer hash functions that are significantly faster than SHA-2 while maintaining equivalent security -- BLAKE3 can hash at over 10 GB/s on modern hardware due to its tree structure enabling parallelism.

HMAC (Hash-based Message Authentication Code) solves a specific problem: how do you verify that a message was not tampered with and that it came from someone who knows a shared secret? A naive approach of hash(key || message) is vulnerable to length extension attacks (which we will discuss shortly). HMAC uses a double-hashing construction: HMAC(key, message) = hash((key XOR opad) || hash((key XOR ipad) || message)), where opad and ipad are fixed padding values. This construction is provably secure even if the underlying hash function has some weaknesses. HMAC is used everywhere: API authentication (AWS uses HMAC-SHA256 for request signing), cookie integrity (signing session cookies so they cannot be tampered with), and webhook verification (GitHub signs webhook payloads with HMAC-SHA256 so you can verify they really came from GitHub).

The length extension attack is a fascinating vulnerability that exploits the Merkle-Damgard construction used by MD5, SHA-1, and SHA-2. If you know hash(secret || message) and the length of secret, you can compute hash(secret || message || padding || extension) without knowing the secret. In practical terms: if a web application uses hash(secret_key + user_data) as an integrity check, an attacker who sees the hash can append arbitrary data and compute a valid hash for the extended message. This attack does NOT work against HMAC (due to the double hashing), SHA-3 (sponge construction), or BLAKE2/3. Real-world impact: the Flickr API used hash(secret + parameters) for request signing and was vulnerable to this attack, allowing parameter injection.

Password hashing is perhaps the most practically important application of hash functions, and it is where most developers get it wrong. The requirements for password hashing are deliberately different from general-purpose hashing: you WANT the function to be slow (to make brute-force cracking expensive), you need a unique salt per password (to prevent rainbow table attacks and prevent identical passwords from having identical hashes), and you want memory-hardness (to make GPU and ASIC cracking expensive). bcrypt has been the standard since 1999: it uses Blowfish-based key derivation with a configurable work factor (cost parameter). A cost of 12 takes about 250ms per hash on modern hardware. scrypt adds memory-hardness on top of computational cost, making it expensive to parallelize on GPUs. Argon2id (the winner of the Password Hashing Competition in 2015) is the current recommendation: it combines memory-hardness, time cost, and parallelism parameters, and comes in three variants -- Argon2d (GPU-resistant), Argon2i (side-channel-resistant), and Argon2id (hybrid, recommended for passwords).

Salt and pepper serve different purposes. A salt is a unique random value stored alongside the password hash -- its job is to ensure two users with the same password have different hashes, preventing precomputed attacks. A pepper is a secret value NOT stored in the database (stored in application config or a hardware security module) -- its job is to ensure that a database breach alone is not enough to begin offline cracking. The work factor (cost parameter) should be tuned to your hardware: the recommendation is to set it so that hashing takes 250ms-1000ms. This seems slow, but users authenticate infrequently. For attackers with stolen hashes trying billions of candidates, this makes cracking infeasible for strong passwords. The critical mistake is using fast hashes like SHA-256 for passwords: a modern GPU can compute billions of SHA-256 hashes per second, cracking most passwords in hours, whereas bcrypt at cost 12 limits the same GPU to hundreds of attempts per second.`,
    practiceEn: [
      'Complete Cryptopals Challenge Set 1, Challenges 5 through 8. Challenge 5 (repeating-key XOR encryption) implements a Vigenere-like cipher. Challenge 6 (break repeating-key XOR) teaches Hamming distance and automated key-length detection -- this is a fundamental cryptanalysis technique. Challenge 7 (AES in ECB mode) uses a real cipher. Challenge 8 (detect AES in ECB mode) applies the statistical weakness of ECB. Document your solutions with explanations of why each approach works.',
      'Write a Python script that benchmarks password hashing algorithms at various parameters. Use the bcrypt, hashlib (for scrypt), and argon2-cffi libraries. For bcrypt, test cost factors 10, 12, and 14. For scrypt, test n=2^14 and n=2^16 with r=8 and p=1. For Argon2id, test memory_cost=65536 and memory_cost=262144 with time_cost=3. For each configuration, hash the same password 10 times and report the average time. Present your results in a table and recommend parameters for: (1) a web application handling 100 logins/second, (2) a low-traffic internal tool, (3) a mobile application.',
      'Demonstrate the length extension attack. Using the hashpumpy Python library (pip install hashpumpy), or by implementing the attack manually: (1) Create a secret key (e.g., "SECRET"). (2) Compute SHA-256(secret + "amount=100&to=alice"). (3) Using only the hash output and knowledge of the key length, compute a valid SHA-256 hash for "amount=100&to=alice" + padding + "&admin=true" WITHOUT knowing the secret. (4) Verify the attack works by computing SHA-256(secret + extended_message) and confirming it matches. (5) Show that the same attack fails against HMAC-SHA256.',
      'Create a practical demonstration of why salting matters. Write a Python script that: (1) Creates a list of 1000 common passwords (download from SecLists). (2) Hashes each with SHA-256 WITHOUT salt and stores the results. (3) Hashes each with SHA-256 WITH a unique 16-byte random salt. (4) Simulates a "rainbow table attack" by precomputing SHA-256 hashes of the same password list and checking for matches in the unsalted set. (5) Shows that the precomputed table is useless against salted hashes. Report the time to "crack" unsalted vs salted hashes.',
      'Audit a real open-source application\'s password storage. Clone a well-known project (e.g., Ghost CMS, Discourse, or Django\'s auth module) and find where passwords are hashed. Identify: (1) which algorithm is used (bcrypt, Argon2, PBKDF2?), (2) what the cost/work factor is set to, (3) how salts are generated and stored, (4) whether the implementation uses a pepper, (5) whether there is a mechanism to upgrade hashes when users log in (rehashing with stronger parameters). Write a brief assessment: is this implementation following current best practices?',
    ],
  },
  11: {
    lectureEn: `JSON Web Tokens (JWTs) are the most common token format for modern web authentication, and they are also one of the most frequently misimplemented security mechanisms. A JWT consists of three base64url-encoded parts separated by dots: the header (specifying the algorithm and token type), the payload (containing claims like user ID, expiration time, and roles), and the signature (computed over the header and payload). The critical thing to understand is that the header and payload are NOT encrypted -- they are merely base64url-encoded. Anyone can decode a JWT and read its contents. The signature only provides integrity and authenticity: it proves the token was created by someone who knows the signing key and has not been modified.

The algorithm field in the JWT header determines how the signature is computed. HS256 (HMAC-SHA256) uses a shared secret -- the same key signs and verifies. RS256 (RSA-SHA256) uses an asymmetric key pair -- the private key signs, the public key verifies. ES256 (ECDSA with P-256) is similar but uses elliptic curves for smaller signatures. EdDSA (Ed25519) is the newest and fastest asymmetric option. The choice between HS256 and RS256 has security implications: HS256 requires the secret to be present on every server that verifies tokens (increasing the attack surface), while RS256 allows the private key to remain on the authentication server and distributes only the public key for verification. In microservices architectures, RS256 or ES256 is strongly preferred.

The alg=none vulnerability is the most infamous JWT attack. The JWT specification allows an "alg": "none" header, indicating no signature is required. If a JWT library accepts this without explicit opt-in, an attacker can forge any token by stripping the signature and setting the algorithm to none. This is not theoretical -- multiple widely-used libraries were vulnerable. The key confusion attack exploits a subtler flaw: if a server uses RS256 (asymmetric), the public key is used for verification. If the server's JWT library can be tricked into treating the public key as an HS256 secret (by changing the alg header to HS256), the attacker can sign tokens with the public key (which is, by definition, public). This works because the library uses whatever algorithm the token specifies rather than what the server expects.

Weak secrets in HS256 are depressingly common. If the signing secret is short or predictable ("secret", "password", "your-256-bit-secret" from the jwt.io example), offline brute-force cracking is trivial. The tool jwt_tool and hashcat (mode 16500) can test millions of candidate secrets per second against a captured JWT. The fix is simple: use a cryptographically random secret of at least 256 bits (32 bytes), or better yet, use an asymmetric algorithm. The kid (Key ID) header parameter tells the server which key to use for verification. If the server resolves the kid from a database query, filesystem path, or URL without proper validation, it can be exploited for SQL injection ("kid": "1 UNION SELECT 'attacker-controlled-key'"), path traversal ("kid": "../../etc/hostname"), or SSRF ("kid": "https://attacker.com/key").

Beyond algorithm-specific attacks, JWT implementation errors include: not validating expiration (exp claim), accepting tokens issued in the future (iat claim), not checking the audience (aud claim) allowing a token meant for one service to be used on another, storing JWTs in localStorage (accessible to XSS) instead of HttpOnly cookies, using excessively long expiration times (JWTs cannot be revoked individually without additional infrastructure), and failing to rotate signing keys. A well-implemented JWT system validates the algorithm against a whitelist (not from the token header), checks exp, iat, nbf, iss, and aud claims, uses short expiration times (15 minutes) with refresh tokens, stores tokens securely, and has a key rotation procedure. Tools like jwt.io for decoding, jwt_tool for testing, and the PortSwigger JWT labs provide hands-on practice with all these attack vectors.`,
    practiceEn: [
      'Go to jwt.io and decode three JWTs from different sources (create test tokens on jwt.io with different algorithms: HS256, RS256, ES256). For each token, manually base64url-decode the header and payload (using Python: base64.urlsafe_b64decode(segment + "==")) and examine the raw JSON. Identify the algorithm, all claims present, and the expiration time. Change a claim in the payload (e.g., change "role": "user" to "role": "admin"), re-encode it, and verify that the signature no longer validates.',
      'Set up a vulnerable JWT Express.js server. Create a simple Node.js/Express app with three endpoints: POST /login (issues a JWT), GET /profile (requires valid JWT), GET /admin (requires JWT with admin role). Intentionally introduce five vulnerabilities: (1) accept alg=none tokens, (2) use a weak HS256 secret ("secret123"), (3) do not validate the exp claim, (4) do not check the aud claim, (5) resolve kid from a file path without sanitization. Then write exploit scripts in Python demonstrating each attack: forge a token with alg=none, crack the weak secret with jwt_tool, use an expired token, swap a token between services, and use path traversal in kid to sign with a known file.',
      'Install jwt_tool (https://github.com/ticarpi/jwt_tool) and use it to test your vulnerable server from step 2. Run the following attacks: "python3 jwt_tool.py <token> -X a" (test alg=none), "python3 jwt_tool.py <token> -X k -pk public.pem" (key confusion with RS256 to HS256), "python3 jwt_tool.py <token> -C -d /path/to/wordlist" (crack HS256 secret). Document the output of each attack and the exact token modifications jwt_tool makes.',
      'Complete the PortSwigger JWT labs (https://portswigger.net/web-security/jwt). There are multiple labs covering: unverified signature, flawed signature verification (accepting alg=none), weak signing key, jwk header injection, jku header injection, and kid header path traversal. For each lab, document: the vulnerability, your exploitation steps in Burp Suite, the crafted JWT, and the fix that would prevent the attack.',
      'Implement a secure JWT system. Using Node.js (jsonwebtoken library) or Python (PyJWT), create an authentication server that: (1) uses RS256 with a 2048-bit RSA key pair, (2) validates the algorithm from a server-side whitelist (never from the token header), (3) sets exp to 15 minutes, (4) includes iss and aud claims and validates them on every request, (5) implements a refresh token flow with refresh tokens stored server-side (database or Redis), (6) rotates signing keys by supporting multiple kids simultaneously. Compare your implementation against the OWASP JWT Cheat Sheet and document any gaps.',
    ],
  },
  12: {
    lectureEn: `This week is your Phase 1 checkpoint -- a consolidation week where you step back from learning new material and instead build connections between everything you have covered. The first 11 weeks gave you three pillars: networking and protocols (weeks 1-4), operating systems (weeks 5-8), and cryptography (weeks 9-11). These are not separate domains -- they interweave constantly in real security work. When you analyze a web application attack, you are simultaneously dealing with HTTP (application layer), TLS (transport security), TCP (reliable delivery), DNS (name resolution), Linux processes and permissions (where the server runs), and cryptographic primitives (how sessions and credentials are protected). The ability to think across these layers is what separates a security professional from someone who can follow a tutorial.

Consider a concrete attack scenario to see how everything connects. An attacker discovers a subdomain "staging.example.com" through DNS enumeration (Week 4). The subdomain runs an HTTP application (Week 2) behind nginx on a Linux server (Weeks 5-6). The TLS certificate (Week 3) for this staging server is valid, but the application uses a JWT (Week 11) with a weak HS256 secret. The attacker captures a valid JWT by intercepting traffic (possible if HSTS is not configured -- Week 3), cracks the secret offline (Week 10 -- password cracking applies to secrets too), and forges an admin token. With admin access, the attacker finds a command injection vulnerability that executes commands as the www-data user. From there, they escalate privileges via a SUID binary (Week 5) to read the application's configuration file containing database credentials. Every step of this chain used knowledge from a different week.

Setting up your final lab environment is a practical task with lasting value. Your lab should include Kali Linux as your primary attack platform -- it comes preloaded with hundreds of security tools organized by category (information gathering, vulnerability analysis, web application analysis, exploitation, privilege escalation, etc.). You do not need to know every tool, but you should be comfortable navigating its menu structure and understanding what category of problem each tool solves. Your vulnerable target should be at least one of: OWASP Juice Shop (a modern JavaScript web application with a rich set of deliberately planted vulnerabilities), DVWA (Damn Vulnerable Web Application -- PHP-based, simpler but covers the classics well), or Metasploitable (a full VM with multiple vulnerable services -- FTP, SSH, web, databases). Running these in VirtualBox or Docker on your own machine ensures you have a legal and always-available testing environment.

Burp Suite should already be familiar from Week 2, but now is the time to go deeper. Learn the Intruder tool for automated payload delivery (brute-forcing, fuzzing), the Comparer for identifying subtle differences in responses, and the Decoder for encoding and hashing. If you are using Burp Community, understand its limitations: Intruder is throttled to one request per second, and the scanner is not available. Consider Caido as a complement -- its HTTPQL query language and built-in automation can fill some gaps. The combination of Kali tools for network-level testing and Burp/Caido for web application testing will carry you through the entire rest of this program.

Your essay assignment this week is not busywork -- it forces you to articulate the relationships between layers that you have been studying in isolation. When you explain how the network stack creates attack surface (SYN floods, ARP spoofing, DNS poisoning), how the operating system creates attack surface (privilege escalation, insecure file permissions, exposed services), and how cryptography creates attack surface (weak algorithms, implementation errors, key management failures), you are building the mental model that professional security engineers use daily. The best security engineers can explain not just WHAT is vulnerable but WHY -- tracing the root cause down to the protocol design decision, the kernel behavior, or the cryptographic property that the developer misunderstood. This is your opportunity to practice that kind of thinking.`,
    practiceEn: [
      'Set up a complete lab environment. Install VirtualBox and create three VMs: (1) Kali Linux (latest rolling release), (2) OWASP Juice Shop running in Docker ("docker run -p 3000:3000 bkimminich/juice-shop"), and (3) Metasploitable 2 or DVWA in Docker ("docker run -d -p 8080:80 vulnerables/web-dvwa"). Verify network connectivity between VMs. In Kali, confirm that Burp Suite, Wireshark, nmap, and john are installed and functional. Take a screenshot of each running VM and document the network configuration (IP addresses, accessible ports).',
      'Perform a comprehensive assessment of your Juice Shop instance using the skills from all 11 previous weeks. Start with network reconnaissance: run "nmap -sV -sC -p- <juice-shop-ip>" from Kali to identify all open ports and services. Capture the initial page load in Wireshark and identify the TLS handshake parameters. Use Burp Suite to map the application: browse all pages with the proxy active, then review the Site Map and identify API endpoints. Attempt to find at least 5 vulnerabilities of different types (look for SQL injection, XSS, broken authentication, sensitive data exposure, broken access control).',
      'Create a self-assessment checklist covering every week. For each topic, rate yourself honestly (1 = "I would struggle to explain this", 2 = "I understand the concept but need references for practice", 3 = "I can explain and demonstrate this confidently"). Topics: TCP handshake and states, HTTP methods and security headers, TLS 1.2 vs 1.3 handshake, DNS record types and DNS attacks, Linux permission model (SUID/capabilities), Linux logging and auditd, Bash scripting for security, AD and Kerberos concepts, AES modes and their weaknesses, HMAC and password hashing, JWT structure and attacks. For any topic rated 1 or 2, go back to that week\'s resources and spend 30 minutes reviewing.',
      'Write the 1500-word essay: "How the network stack, operating system, and cryptography form the attack surface of a web application." Structure it around a concrete example -- trace a user logging into a web application and identify security-relevant decisions at each layer: DNS resolution (what could go wrong?), TCP connection (SYN flood, connection hijacking), TLS negotiation (downgrade attacks, certificate issues), HTTP request (header injection, cookie security), server-side processing (OS permissions, process isolation), and credential verification (hashing, timing attacks). Include at least three real-world incidents as examples (e.g., DigiNotar CA breach for TLS trust, Heartbleed for implementation bugs, SolarWinds for supply chain).',
      'Verify your tooling proficiency with quick exercises: (1) In Burp Repeater, modify a request to Juice Shop -- change a parameter value and observe the response difference. (2) In Wireshark, capture and filter traffic to show only DNS queries ("dns.qr == 0"). (3) On your Kali VM, use john to crack a simple password hash: create /tmp/test.hash with the content "testuser:$6$rounds=1000$salt$<hash>" (generate this with openssl passwd -6 -salt salt password123) and run "john /tmp/test.hash --wordlist=/usr/share/wordlists/rockyou.txt.gz". (4) Run a basic nmap scan: "nmap -sS -sV <target-ip>" and interpret every line of output.',
      'Plan your Phase 2 trajectory. Review the weeks 13-24 syllabus (web vulnerabilities). Create a PortSwigger Web Security Academy account if you have not already (https://portswigger.net/web-security). Browse the lab categories (SQL injection, XSS, CSRF, SSRF, etc.) and complete one Apprentice-level lab from any category to confirm your setup works. This preview will help you hit the ground running in Phase 2.',
    ],
  },
};
