export interface WeekResource {
  name: string;
  url: string;
}

export interface Week {
  week: number;
  titleEn: string;
  titleUk: string;
  topicsEn: string;
  topicsUk: string;
  artifactEn: string;
  artifactUk: string;
  hours: number;
  advanced?: boolean;
  resources: WeekResource[];
}

export interface MonthData {
  weeks: Week[];
}

export interface PhaseData {
  months: MonthData[];
}

export const WEEKS_DATA: Week[] = [
  // ─── PHASE 1: FOUNDATION ───────────────────────────────────────────
  // Month 1
  {
    week: 1,
    titleEn: 'TCP/IP and the anatomy of the network stack',
    titleUk: 'TCP/IP та анатомія мережевого стеку',
    topicsEn: 'OSI and TCP/IP models; IP, TCP, UDP, ICMP; TCP handshake and connection states; NAT, routing. Wireshark setup, analyzing pcap files from public datasets.',
    topicsUk: 'Моделі OSI та TCP/IP; IP, TCP, UDP, ICMP; TCP handshake та стани з\'єднань; NAT, маршрутизація. Встановлення Wireshark, розбір pcap-файлів з публічних датасетів.',
    artifactEn: 'Annotated pcap file analyzing three TCP sessions (handshake, data transfer, teardown)',
    artifactUk: 'Анотований pcap-файл з розбором трьох TCP-сесій (handshake, передача даних, закриття)',
    hours: 7,
    resources: [
      { name: 'Wireshark', url: 'https://www.wireshark.org/' },
      { name: 'Sample Captures', url: 'https://wiki.wireshark.org/SampleCaptures' },
    ],
  },
  {
    week: 2,
    titleEn: 'HTTP/HTTPS at the raw byte level',
    titleUk: 'HTTP/HTTPS на рівні сирих байтів',
    topicsEn: 'HTTP/1.1 methods, headers, statuses, cookies, caching, CORS. HTTP/2 — multiplexing, binary framing. Setting up Burp Suite Community and Caido.',
    topicsUk: 'HTTP/1.1 методи, заголовки, статуси, cookies, кешування, CORS. HTTP/2 — мультиплексування, бінарний формат. Встановлення Burp Suite Community та Caido.',
    artifactEn: 'Markdown document: 10 types of HTTP requests crafted manually via curl with analysis of each header',
    artifactUk: 'Markdown-документ: 10 типів HTTP-запитів вручну через curl з розбором кожного заголовка',
    hours: 7,
    resources: [
      { name: 'Burp Suite Community', url: 'https://portswigger.net/burp/communitydownload' },
      { name: 'Caido', url: 'https://caido.io/' },
      { name: 'curl', url: 'https://curl.se/' },
    ],
  },
  {
    week: 3,
    titleEn: 'TLS and trust infrastructure',
    titleUk: 'TLS та інфраструктура довіри',
    topicsEn: 'TLS 1.2 and 1.3 handshake, differences. X.509 certificates, trust chains, CAs. HSTS, certificate pinning. SNI and its role. Mutual TLS.',
    topicsUk: 'TLS 1.2 і 1.3 handshake, відмінності. Сертифікати X.509, ланцюжки довіри, CA. HSTS, certificate pinning. SNI та його роль. Mutual TLS.',
    artifactEn: 'Self-signed CA + certificate for a local domain, nginx configured with HTTPS',
    artifactUk: 'Самопідписаний CA + сертифікат для локального домену, налаштований nginx з HTTPS',
    hours: 6,
    resources: [
      { name: 'Let\'s Encrypt', url: 'https://letsencrypt.org/' },
      { name: 'nginx', url: 'https://nginx.org/' },
      { name: 'mkcert (GitHub)', url: 'https://github.com/FiloSottile/mkcert' },
    ],
  },
  {
    week: 4,
    titleEn: 'DNS as an attack surface',
    titleUk: 'DNS як поверхня атаки',
    topicsEn: 'Records: A, AAAA, CNAME, MX, TXT, NS. Recursive and authoritative servers. DNSSEC. Attacks: cache poisoning, DNS rebinding, exfiltration via DNS. DoH and DoT.',
    topicsUk: 'Записи A, AAAA, CNAME, MX, TXT, NS. Рекурсивні та авторитативні сервери. DNSSEC. Атаки: cache poisoning, DNS rebinding, exfiltration через DNS. DoH і DoT.',
    artifactEn: 'Python script implementing DNS tunneling on a local testbed',
    artifactUk: 'Скрипт на Python, що реалізує DNS-тунелювання на локальному стенді',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'dnscat2', url: 'https://github.com/iagox86/dnscat2' },
      { name: 'Cloudflare DNS Guide', url: 'https://www.cloudflare.com/learning/dns/what-is-dns/' },
    ],
  },
  // Month 2
  {
    week: 5,
    titleEn: 'Linux: processes, users, permissions',
    titleUk: 'Linux: процеси, користувачі, права',
    topicsEn: 'UID, GID, effective/real identifiers. SUID, SGID, sticky bit. Capabilities. /etc/passwd, /etc/shadow. PAM. Namespaces and cgroups as container foundations.',
    topicsUk: 'UID, GID, ефективні/реальні ідентифікатори. SUID, SGID, sticky bit. Capabilities. /etc/passwd, /etc/shadow. PAM. Namespaces і cgroups як основа контейнерів.',
    artifactEn: 'Vulnerable VM on VirtualBox with three privilege escalation scenarios, each documented',
    artifactUk: 'Вразлива VM на VirtualBox з трьома сценаріями privilege escalation, опис кожного',
    hours: 7,
    resources: [
      { name: 'Kali Linux', url: 'https://www.kali.org/' },
      { name: 'VirtualBox', url: 'https://www.virtualbox.org/' },
      { name: 'Metasploitable3', url: 'https://github.com/rapid7/metasploitable3' },
    ],
  },
  {
    week: 6,
    titleEn: 'Linux: filesystem, logs, networking',
    titleUk: 'Linux: файлова система, журнали, мережа',
    topicsEn: 'Inodes, symlinks, mounting. Journald, syslog, auditing via auditd. iptables/nftables. ss, netstat, tcpdump. Basic systemd: unit files, targets.',
    topicsUk: 'Inodes, симлінки, монтування. Journald, syslog, аудит через auditd. iptables/nftables. ss, netstat, tcpdump. Базовий systemd: unit-файли, таргети.',
    artifactEn: 'Bash script monitoring suspicious activity (new SUID files, /etc changes, unknown listening ports)',
    artifactUk: 'Bash-скрипт моніторингу підозрілої активності (нові SUID, зміни в /etc, невідомі порти)',
    hours: 6,
    resources: [
      { name: 'OverTheWire Bandit', url: 'https://overthewire.org/wargames/bandit/' },
      { name: 'linuxcommand.org', url: 'https://linuxcommand.org/' },
    ],
  },
  {
    week: 7,
    titleEn: 'Bash and Python for the security engineer',
    titleUk: 'Bash і Python для security-інженера',
    topicsEn: 'Bash: pipes, process substitution, here-documents, traps. Python: requests, argparse, basic socket networking, JSON processing, log parsing.',
    topicsUk: 'Bash: pipes, process substitution, here-documents, ловушки. Python: requests, argparse, базова робота з мережевими сокетами, обробка JSON, парсинг логів.',
    artifactEn: 'CLI utility in Python that checks a list of domains for TLS configuration (version, certificate, ciphers)',
    artifactUk: 'CLI-утиліта на Python, що перевіряє список доменів на TLS-конфігурацію (версія, сертифікат, шифри)',
    hours: 8,
    resources: [
      { name: 'Python docs: argparse', url: 'https://docs.python.org/3/library/argparse.html' },
      { name: 'Python docs: socket', url: 'https://docs.python.org/3/library/socket.html' },
      { name: 'Requests library', url: 'https://requests.readthedocs.io/' },
    ],
  },
  {
    week: 8,
    titleEn: 'Windows and Active Directory: concepts',
    titleUk: 'Windows і Active Directory: концепції',
    topicsEn: 'Conceptual level. AD domain architecture. NTLM vs Kerberos. SIDs, ACLs, access tokens. Group Policy. PowerShell for security tasks.',
    topicsUk: 'Концептуальний рівень. Доменна архітектура AD. NTLM vs Kerberos. SIDs, ACLs, токени доступу. Group Policy. PowerShell для security-задач.',
    artifactEn: 'Summary with Kerberos authentication diagram and description of three classic attacks (Kerberoasting, AS-REP roasting, golden ticket)',
    artifactUk: 'Конспект з діаграмою Kerberos-автентифікації та описом трьох класичних атак (Kerberoasting, AS-REP roasting, golden ticket)',
    hours: 6,
    resources: [
      { name: 'AD Overview (Microsoft)', url: 'https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview' },
      { name: 'HackTheBox', url: 'https://www.hackthebox.com/' },
      { name: 'TryHackMe', url: 'https://tryhackme.com/' },
    ],
  },
  // Month 3
  {
    week: 9,
    titleEn: 'Symmetric and asymmetric cryptography',
    titleUk: 'Симетрична та асиметрична криптографія',
    topicsEn: 'AES (CBC, CTR, GCM), why ECB is dangerous. RSA, ECC, Diffie-Hellman. When to use each. Common mistakes: nonce reuse, padding oracle, weak randomness.',
    topicsUk: 'AES (CBC, CTR, GCM), чому ECB небезпечний. RSA, ECC, Diffie-Hellman. Коли що застосовувати. Типові помилки: повторне використання nonce, padding oracle, weak randomness.',
    artifactEn: 'Cryptopals Set 1: challenges 1–4 with solutions and commentary',
    artifactUk: 'Cryptopals Set 1: завдання 1–4 з рішеннями та коментарями',
    hours: 7,
    resources: [
      { name: 'Cryptopals', url: 'https://cryptopals.com/' },
      { name: 'CyberChef', url: 'https://gchq.github.io/CyberChef/' },
    ],
  },
  {
    week: 10,
    titleEn: 'Hash functions, MAC, KDF',
    titleUk: 'Хеш-функції, MAC, KDF',
    topicsEn: 'SHA-2, SHA-3, BLAKE2/3. HMAC. Password hashing: bcrypt, scrypt, Argon2id. Salt, pepper, work factor. Length extension attack.',
    topicsUk: 'SHA-2, SHA-3, BLAKE2/3. HMAC. Хешування паролів: bcrypt, scrypt, Argon2id. Сіль, перець, робочий фактор. Length extension attack.',
    artifactEn: 'Cryptopals Set 1: challenges 5–8. Script comparing bcrypt vs Argon2id speed at different parameters',
    artifactUk: 'Cryptopals Set 1: завдання 5–8. Скрипт порівняння швидкості bcrypt vs Argon2id при різних параметрах',
    hours: 7,
    resources: [
      { name: 'Cryptopals', url: 'https://cryptopals.com/' },
      { name: 'OWASP Password Storage', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html' },
      { name: 'Argon2', url: 'https://www.argon2.com/' },
    ],
  },
  {
    week: 11,
    titleEn: 'JWT, signatures, PKI',
    titleUk: 'JWT, підписи, PKI',
    topicsEn: 'JWT structure (header, payload, signature). Algorithms: HS256, RS256, ES256, EdDSA. Classic JWT vulnerabilities: alg=none, key confusion, weak secrets, kid injection.',
    topicsUk: 'Структура JWT (header, payload, signature). Алгоритми: HS256, RS256, ES256, EdDSA. Класичні вразливості JWT: alg=none, key confusion, weak secrets, kid injection.',
    artifactEn: 'Lab of 5 vulnerable JWT configurations (write an Express server, demonstrate attack on each)',
    artifactUk: 'Лабораторія з 5 вразливих JWT-конфігурацій (написати сервер на Express, продемонструвати атаку на кожну)',
    hours: 8,
    advanced: true,
    resources: [
      { name: 'jwt.io', url: 'https://jwt.io/' },
      { name: 'jwt_tool', url: 'https://github.com/ticarpi/jwt_tool' },
      { name: 'PortSwigger JWT labs', url: 'https://portswigger.net/web-security/jwt' },
    ],
  },
  {
    week: 12,
    titleEn: 'Phase 1 checkpoint',
    titleUk: 'Контрольний тиждень фази 1',
    topicsEn: 'Review, filling gaps. Setting up the final lab: Kali, vulnerable VM (Metasploitable3 or Juice Shop), Burp Suite.',
    topicsUk: 'Повторення, заповнення прогалин. Встановлення фінального лабораторного стенду: Kali, вразлива VM (Metasploitable3 або Juice Shop), Burp Suite.',
    artifactEn: '1500-word essay: how the network stack, OS, and cryptography form the attack surface of a web application',
    artifactUk: 'Есе на 1500 слів: як мережевий стек, ОС та криптографія формують поверхню атаки веб-застосунку',
    hours: 6,
    resources: [
      { name: 'OWASP Juice Shop', url: 'https://owasp.org/www-project-juice-shop/' },
      { name: 'DVWA', url: 'https://github.com/digininja/DVWA' },
      { name: 'Metasploitable 2', url: 'https://docs.rapid7.com/metasploit/metasploitable-2/' },
    ],
  },
  // ─── PHASE 2: WEB VULNERABILITIES ──────────────────────────────────
  // Month 4
  {
    week: 13,
    titleEn: 'Injection vulnerabilities',
    titleUk: 'Injection-вразливості',
    topicsEn: 'SQL injection (UNION, blind, time-based). NoSQL injection (MongoDB). Command injection. LDAP injection. Parameterized queries as defense.',
    topicsUk: 'SQL injection (UNION, blind, time-based). NoSQL injection (MongoDB). Command injection. LDAP injection. Параметризовані запити як захист.',
    artifactEn: 'PortSwigger Academy: complete all SQL injection labs (~17 labs). Cheat sheet with defensive patterns per language (PHP, Python, Node.js, Java)',
    artifactUk: 'PortSwigger Academy: пройти всі лаби по SQL injection (~17 лаб). Конспект із захисними паттернами для кожної мови (PHP, Python, Node.js, Java)',
    hours: 8,
    resources: [
      { name: 'PortSwigger SQL Injection', url: 'https://portswigger.net/web-security/sql-injection' },
      { name: 'OWASP SQLi Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html' },
    ],
  },
  {
    week: 14,
    titleEn: 'XSS in all forms',
    titleUk: 'XSS у всіх формах',
    topicsEn: 'Reflected, stored, DOM-based XSS. Contexts (HTML body, attribute, JS, URL, CSS). Filter bypass. CSP: protection levels, bypasses via JSONP and unsafe-inline. Trusted Types.',
    topicsUk: 'Reflected, stored, DOM-based XSS. Контексти (HTML body, attribute, JS, URL, CSS). Bypass фільтрів. CSP: рівні захисту, обходи через JSONP і unsafe-inline. Trusted Types.',
    artifactEn: 'PortSwigger Academy: all XSS labs. Custom XSS payload bypassing three different CSP configurations',
    artifactUk: 'PortSwigger Academy: всі лаби по XSS. Свій XSS-payload, що обходить три різних CSP-конфігурації',
    hours: 8,
    resources: [
      { name: 'PortSwigger XSS', url: 'https://portswigger.net/web-security/cross-site-scripting' },
      { name: 'MDN CSP', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP' },
    ],
  },
  {
    week: 15,
    titleEn: 'CSRF, SSRF, open redirects',
    titleUk: 'CSRF, SSRF, відкриті редиректи',
    topicsEn: 'CSRF: classic scenario, SameSite cookies, double submit, synchronizers. SSRF — why critical in cloud (metadata endpoints: AWS 169.254.169.254, GCP). Blind SSRF.',
    topicsUk: 'CSRF: класичний сценарій, SameSite cookies, double submit, синхронізатори. SSRF — чому критично в хмарі (metadata endpoints: AWS 169.254.169.254, GCP). Blind SSRF.',
    artifactEn: 'PortSwigger Academy: all CSRF and SSRF labs. Reproduce Capital One-style attack (2019) in local AWS simulation via LocalStack',
    artifactUk: 'PortSwigger Academy: всі лаби по CSRF і SSRF. Відтворення Capital One-style атаки (2019) в локальній AWS-імітації через LocalStack',
    hours: 8,
    advanced: true,
    resources: [
      { name: 'PortSwigger CSRF', url: 'https://portswigger.net/web-security/csrf' },
      { name: 'PortSwigger SSRF', url: 'https://portswigger.net/web-security/ssrf' },
      { name: 'OWASP CSRF Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
    ],
  },
  {
    week: 16,
    titleEn: 'Authentication and sessions',
    titleUk: 'Автентифікація та сесії',
    topicsEn: 'Broken authentication: brute force, credential stuffing, default credentials. Session fixation, session hijacking. MFA bypass scenarios. Attacks on password reset flows.',
    topicsUk: 'Broken authentication: brute force, credential stuffing, default credentials. Session fixation, session hijacking. Сценарії обходу MFA. Атаки на flow відновлення паролю.',
    artifactEn: 'PortSwigger Academy: authentication labs. Threat model for the password reset process of a typical SaaS',
    artifactUk: 'PortSwigger Academy: лаби по authentication. Threat model для процесу відновлення паролю типового SaaS',
    hours: 7,
    resources: [
      { name: 'PortSwigger Authentication', url: 'https://portswigger.net/web-security/authentication' },
    ],
  },
  // Month 5
  {
    week: 17,
    titleEn: 'IDOR, broken access control, mass assignment',
    titleUk: 'IDOR, broken access control, mass assignment',
    topicsEn: 'Authorization vs authentication. Vertical and horizontal privilege escalation. Mass assignment in Rails, Django, Express. Forced browsing. Access control in REST and GraphQL.',
    topicsUk: 'Authorization vs authentication. Вертикальна і горизонтальна ескалація привілеїв. Mass assignment в Rails, Django, Express. Forced browsing. Access control в REST і GraphQL.',
    artifactEn: 'PortSwigger Academy: access control labs. IDOR audit of an open-source Express app (e.g. NodeBB or Ghost)',
    artifactUk: 'PortSwigger Academy: лаби по access control. Аудит open-source застосунку на Express (наприклад, NodeBB або Ghost) на предмет IDOR',
    hours: 7,
    resources: [
      { name: 'PortSwigger Access Control', url: 'https://portswigger.net/web-security/access-control' },
      { name: 'NodeBB', url: 'https://github.com/nodebb/nodebb' },
      { name: 'Ghost', url: 'https://ghost.org/' },
    ],
  },
  {
    week: 18,
    titleEn: 'Race conditions and concurrency bugs',
    titleUk: 'Race conditions та concurrency-баги',
    topicsEn: 'Logical race conditions: double spending, limit bypass. TOCTOU. Burp Turbo Intruder for exploitation. Defense: optimistic locks, idempotency.',
    topicsUk: 'Логічні race conditions: подвійне списання, обхід лімітів. TOCTOU. Burp Turbo Intruder для експлуатації. Захист: оптимістичні блокування, ідемпотентність.',
    artifactEn: 'PortSwigger Academy: all race condition labs. PoC race condition in own test app (e.g. race in discount code logic)',
    artifactUk: 'PortSwigger Academy: всі лаби по race conditions. PoC race condition у власному тестовому застосунку (наприклад, race в логіці промокодів)',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'PortSwigger Race Conditions', url: 'https://portswigger.net/web-security/race-conditions' },
      { name: 'Smashing the State Machine', url: 'https://portswigger.net/research/smashing-the-state-machine' },
    ],
  },
  {
    week: 19,
    titleEn: 'HTTP request smuggling',
    titleUk: 'HTTP request smuggling',
    topicsEn: 'CL.TE, TE.CL, TE.TE variants. HTTP/2 downgrade smuggling. When it occurs (proxy, load balancer). Impact: cache poisoning, credential theft.',
    topicsUk: 'CL.TE, TE.CL, TE.TE варіанти. HTTP/2 downgrade smuggling. Коли виникає (проксі, балансувальник). Вплив: cache poisoning, credential theft.',
    artifactEn: 'PortSwigger Academy: all request smuggling labs. Written analysis of James Kettle research paper',
    artifactUk: 'PortSwigger Academy: всі лаби по request smuggling. Письмовий розбір дослідження James Kettle',
    hours: 8,
    advanced: true,
    advanced: true,
    resources: [
      { name: 'PortSwigger Request Smuggling', url: 'https://portswigger.net/web-security/request-smuggling' },
      { name: 'HTTP Desync Attacks (Kettle)', url: 'https://portswigger.net/research/http-desync-attacks-request-smuggling-reborn' },
    ],
  },
  {
    week: 20,
    titleEn: 'Deserialization and prototype pollution',
    titleUk: 'Десеріалізація та prototype pollution',
    topicsEn: 'Insecure deserialization in Java, Python (pickle), PHP, .NET. Prototype pollution in JS — client and server. Gadget chains. Defense: avoid, sandboxing.',
    topicsUk: 'Insecure deserialization в Java, Python (pickle), PHP, .NET. Prototype pollution в JS — клієнтський і серверний. Ланцюжки гаджетів. Захист: уникати, sandboxing.',
    artifactEn: 'PortSwigger Academy: deserialization and prototype pollution labs. Analysis of a public CVE with deserialization vector',
    artifactUk: 'PortSwigger Academy: лаби по deserialization і prototype pollution. Аналіз публічного CVE з десеріалізаційним вектором',
    hours: 7,
    advanced: true,
    advanced: true,
    resources: [
      { name: 'PortSwigger Deserialization', url: 'https://portswigger.net/web-security/deserialization' },
      { name: 'PortSwigger Prototype Pollution', url: 'https://portswigger.net/web-security/prototype-pollution' },
    ],
  },
  // Month 6
  {
    week: 21,
    titleEn: 'API security — OWASP API Top 10',
    titleUk: 'API security — OWASP API Top 10',
    topicsEn: 'BOLA (API1), broken authentication (API2), broken object property level authorization (API3), unrestricted resource consumption (API4), broken function level authorization (API5).',
    topicsUk: 'BOLA (API1), broken authentication (API2), broken object property level authorization (API3), unrestricted resource consumption (API4), broken function level authorization (API5).',
    artifactEn: 'Deploy OWASP crAPI or VAmPI. Find and document at least 5 vulnerabilities of different categories with PoC',
    artifactUk: 'Розгорнути OWASP crAPI або VAmPI. Знайти і задокументувати мінімум 5 вразливостей різних категорій з PoC',
    hours: 8,
    resources: [
      { name: 'OWASP API Security', url: 'https://owasp.org/API-Security/' },
      { name: 'OWASP crAPI', url: 'https://github.com/OWASP/crAPI' },
      { name: 'VAmPI', url: 'https://github.com/erev0s/VAmPI' },
    ],
  },
  {
    week: 22,
    titleEn: 'GraphQL and gRPC security',
    titleUk: 'GraphQL та gRPC security',
    topicsEn: 'GraphQL: introspection, batching attacks, alias-based DoS, depth and complexity limiting. gRPC: protobuf parsing, mutual TLS, reflection. Schema disclosure attacks.',
    topicsUk: 'GraphQL: introspection, batching attacks, alias-based DoS, depth і complexity limiting. gRPC: protobuf-парсинг, mutual TLS, reflection. Атаки на schema disclosure.',
    artifactEn: 'Audit of GraphQL API in DVGA (Damn Vulnerable GraphQL Application) with written report',
    artifactUk: 'Аудит GraphQL API у DVGA (Damn Vulnerable GraphQL Application) з письмовим звітом',
    hours: 7,
    resources: [
      { name: 'DVGA', url: 'https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application' },
      { name: 'GraphQL Voyager', url: 'https://graphql-kit.com/graphql-voyager/' },
    ],
  },
  {
    week: 23,
    titleEn: 'Web cache poisoning and host header attacks',
    titleUk: 'Web cache poisoning та host header attacks',
    topicsEn: 'Unkeyed inputs, cache key normalization issues. Web cache deception. Host header injection. Routing-based SSRF via header manipulation.',
    topicsUk: 'Unkeyed inputs, проблеми нормалізації cache key. Web cache deception. Host header injection. Routing-based SSRF через маніпуляції з заголовками.',
    artifactEn: 'PortSwigger Academy: all web cache poisoning labs. Summary of James Kettle research on the topic',
    artifactUk: 'PortSwigger Academy: всі лаби по web cache poisoning. Конспект досліджень James Kettle з теми',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'PortSwigger Cache Poisoning', url: 'https://portswigger.net/web-security/web-cache-poisoning' },
      { name: 'Practical Cache Poisoning (Kettle)', url: 'https://portswigger.net/research/practical-web-cache-poisoning' },
    ],
  },
  {
    week: 24,
    titleEn: 'Chaining web vulnerabilities into realistic scenarios',
    titleUk: 'Збірка веб-вразливостей у реалістичні сценарії',
    topicsEn: 'Vulnerability chains. Bug bounty mindset: what to report, how to write PoC, what counts as a duplicate. Structure of a good report.',
    topicsUk: 'Ланцюжки вразливостей. Bug bounty mindset: що звітувати, як писати PoC, що вважається дублікатом. Структура хорошого звіту.',
    artifactEn: 'Complete HackTheBox Web Challenges (medium level) — minimum 3 machines with full write-ups',
    artifactUk: 'Проходження HackTheBox Web Challenges (медіум-рівень) — мінімум 3 машини з повними write-up',
    hours: 8,
    advanced: true,
    resources: [
      { name: 'HackTheBox', url: 'https://www.hackthebox.com/' },
      { name: 'HackerOne', url: 'https://www.hackerone.com/' },
      { name: 'Bugcrowd', url: 'https://www.bugcrowd.com/' },
    ],
  },
  // Month 7
  {
    week: 25,
    titleEn: 'OAuth 2.0 and OIDC internals',
    titleUk: 'OAuth 2.0 та OIDC зсередини',
    topicsEn: 'Authorization Code, Implicit (deprecated), Client Credentials, Device flow. PKCE. ID token vs access token. Scope. Refresh tokens. OIDC over OAuth.',
    topicsUk: 'Authorization Code, Implicit (deprecated), Client Credentials, Device flow. PKCE. ID token vs access token. Scope. Refresh tokens. OIDC поверх OAuth.',
    artifactEn: 'Deploy Keycloak locally, connect a test SPA + API. Document which 5 default settings are wrong for production',
    artifactUk: 'Розгорнути Keycloak локально, підключити тестове SPA + API. Документація: які 5 налаштувань неправильні за замовчуванням для production',
    hours: 7,
    resources: [
      { name: 'Keycloak', url: 'https://www.keycloak.org/' },
      { name: 'OAuth 2.0', url: 'https://oauth.net/2/' },
      { name: 'OpenID Connect', url: 'https://openid.net/developers/how-connect-works/' },
    ],
  },
  {
    week: 26,
    titleEn: 'Attacks on OAuth and SAML',
    titleUk: 'Атаки на OAuth і SAML',
    topicsEn: 'Open redirect in redirect_uri. State parameter and CSRF. PKCE downgrade. SAML: golden SAML, XML signature wrapping, comment injection in NameID.',
    topicsUk: 'Open redirect в redirect_uri. State parameter і CSRF. PKCE downgrade. SAML: golden SAML, XML signature wrapping, comment injection в NameID.',
    artifactEn: 'PortSwigger Academy: OAuth labs. Written analysis of Microsoft Power Apps SAML bypass or similar public research',
    artifactUk: 'PortSwigger Academy: лаби по OAuth. Письмовий розбір Microsoft Power Apps SAML bypass або аналогічного публічного дослідження',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'PortSwigger OAuth', url: 'https://portswigger.net/web-security/oauth' },
      { name: 'Authentik', url: 'https://goauthentik.io/' },
    ],
  },
  {
    week: 27,
    titleEn: 'WebAuthn, passkeys, MFA bypass',
    titleUk: 'WebAuthn, passkeys, MFA bypass',
    topicsEn: 'FIDO2 architecture. Attestation. Resident vs non-resident credentials. MFA bypass: SIM swap, push fatigue, prompt bombing. Phishing-resistant MFA.',
    topicsUk: 'FIDO2 архітектура. Attestation. Resident vs non-resident credentials. MFA bypass: SIM swap, push fatigue, prompt bombing. Phishing-resistant MFA.',
    artifactEn: 'Demo application with WebAuthn on webauthn.io-like architecture, working passkey login',
    artifactUk: 'Демо-застосунок з WebAuthn на архітектурі типу webauthn.io, робочий вхід через passkey',
    hours: 7,
    resources: [
      { name: 'webauthn.io', url: 'https://webauthn.io/' },
      { name: 'FIDO Alliance Passkeys', url: 'https://fidoalliance.org/passkeys/' },
    ],
  },
  {
    week: 28,
    titleEn: 'Phase 2 checkpoint — BSCP exam',
    titleUk: 'Контрольний тиждень фази 2 — іспит BSCP',
    topicsEn: 'Take the PortSwigger Burp Suite Certified Practitioner (BSCP) exam — $90, 2 vulnerable systems, 4 hours. This is formal validation of web skills.',
    topicsUk: 'Складання іспиту PortSwigger Burp Suite Certified Practitioner (BSCP) — $90, 2 вразливі системи, 4 години. Це формальне підтвердження веб-навичок.',
    artifactEn: 'BSCP certificate (or retry). HackerOne profile created, prerequisites filled',
    artifactUk: 'Сертифікат BSCP (або повторна спроба). Профіль на HackerOne створений, prerequisites заповнені',
    hours: 8,
    advanced: true,
    resources: [
      { name: 'BSCP Certification', url: 'https://portswigger.net/web-security/certification' },
      { name: 'HackerOne', url: 'https://www.hackerone.com/' },
    ],
  },
  // ─── PHASE 3: DEFENSIVE APPSEC ────────────────────────────────────
  // Month 8
  {
    week: 29,
    titleEn: 'Secure SDLC and the AppSec role in a team',
    titleUk: 'Secure SDLC і місце AppSec у команді',
    topicsEn: 'Development lifecycle and where security fits. Shift-left vs shift-right. Security champions. AppSec program metrics. How not to be a bottleneck.',
    topicsUk: 'Життєвий цикл розробки і де вбудовується security. Shift-left vs shift-right. Security champions. Метрики AppSec-програми. Як не бути вузьким місцем.',
    artifactEn: 'Document: proposal for integrating security practices into SDLC of the QA engineer\'s current company',
    artifactUk: 'Документ: пропозиція з інтеграції security-практик в SDLC поточної компанії QA-інженера',
    hours: 6,
    resources: [
      { name: 'OWASP SAMM', url: 'https://owasp.org/www-project-samm/' },
      { name: 'Microsoft SDL', url: 'https://www.microsoft.com/en-us/securityengineering/sdl' },
    ],
  },
  {
    week: 30,
    titleEn: 'Threat modeling: STRIDE',
    titleUk: 'Threat modeling: STRIDE',
    topicsEn: 'STRIDE categories. Data flow diagrams. Trust boundaries. Detail level. Working with Microsoft Threat Modeling Tool or OWASP Threat Dragon.',
    topicsUk: 'STRIDE категорії. Data flow diagrams. Trust boundaries. Рівень деталізації. Робота з Microsoft Threat Modeling Tool або OWASP Threat Dragon.',
    artifactEn: 'Full threat model for a typical SaaS (e.g. multi-tenant CRM): DFD, identified threats per STRIDE, mitigations',
    artifactUk: 'Повна threat model для типового SaaS (наприклад, multi-tenant CRM): DFD, ідентифіковані загрози по STRIDE, mitigations',
    hours: 7,
    resources: [
      { name: 'OWASP Threat Dragon', url: 'https://owasp.org/www-project-threat-dragon/' },
      { name: 'MS Threat Modeling Tool', url: 'https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool' },
    ],
  },
  {
    week: 31,
    titleEn: 'Threat modeling: PASTA, attack trees',
    titleUk: 'Threat modeling: PASTA, attack trees',
    topicsEn: 'PASTA as a risk-oriented approach. Attack trees. MITRE ATT&CK as reference. When to use which method. LINDDUN for privacy.',
    topicsUk: 'PASTA як ризик-орієнтований підхід. Attack trees. MITRE ATT&CK як референс. Коли який метод застосовувати. LINDDUN для privacy.',
    artifactEn: 'Attack tree for the authentication process of the previously modeled SaaS. Cross-reference with MITRE ATT&CK techniques',
    artifactUk: 'Attack tree для процесу автентифікації того ж SaaS, що моделювали раніше. Cross-reference з MITRE ATT&CK techniques',
    hours: 7,
    resources: [
      { name: 'MITRE ATT&CK', url: 'https://attack.mitre.org/' },
      { name: 'LINDDUN', url: 'https://linddun.org/' },
      { name: 'OWASP Threat Modeling', url: 'https://owasp.org/www-community/Threat_Modeling' },
    ],
  },
  {
    week: 32,
    titleEn: 'Architecture review and working with developers',
    titleUk: 'Architecture review та робота з розробниками',
    topicsEn: 'Reading architecture diagrams. Finding design issues. Soft skills: giving feedback that teams listen to. Risk acceptance.',
    topicsUk: 'Читання архітектурних діаграм. Пошук проблем дизайну. Soft skills: як давати зворотний зв\'язок, щоб команди слухали. Risk acceptance.',
    artifactEn: 'Revised threat model: adding compensating controls and risk prioritization (likelihood × impact)',
    artifactUk: 'Переглянута threat model: додавання компенсуючих контролів і пріоритезація за ризиком (likelihood × impact)',
    hours: 6,
    resources: [
      { name: 'OWASP Threat Modeling Cheatsheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html' },
    ],
  },
  // Month 9
  {
    week: 33,
    titleEn: 'SAST with Semgrep',
    titleUk: 'SAST з Semgrep',
    topicsEn: 'Static analysis principles. AST, taint analysis. Semgrep: rule syntax, built-in packs. CI integration. Triaging findings: true positive, false positive, accepted risk.',
    topicsUk: 'Принципи статичного аналізу. AST, taint analysis. Semgrep: синтаксис правил, вбудовані пакети. Інтеграція в CI. Triage findings: true positive, false positive, accepted risk.',
    artifactEn: 'At least 3 custom Semgrep rules (for typical bugs in Express.js or FastAPI). PR to open-source with Semgrep CI integration',
    artifactUk: 'Мінімум 3 власних Semgrep-правила (для типових багів в Express.js або FastAPI). PR в open-source з інтеграцією Semgrep в CI',
    hours: 8,
    resources: [
      { name: 'Semgrep', url: 'https://semgrep.dev/' },
      { name: 'Semgrep Playground', url: 'https://semgrep.dev/playground' },
    ],
  },
  {
    week: 34,
    titleEn: 'CodeQL and advanced SAST',
    titleUk: 'CodeQL та просунутий SAST',
    topicsEn: 'CodeQL code model. Basic queries. When CodeQL beats Semgrep and vice versa. Snyk Code, SonarQube as alternatives. SAST limitations.',
    topicsUk: 'CodeQL модель коду. Базові queries. Коли CodeQL кращий за Semgrep і навпаки. Snyk Code, SonarQube як альтернативи. Обмеження SAST.',
    artifactEn: 'Complete a CodeQL CTF (GitHub publishes them regularly). Custom query finding a specific vulnerability pattern',
    artifactUk: 'Проходження CodeQL CTF (GitHub публікує регулярно). Свій query, що знаходить конкретний паттерн вразливості',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'CodeQL', url: 'https://codeql.github.com/' },
      { name: 'GitHub Security Lab CTF', url: 'https://securitylab.github.com/ctf/' },
    ],
  },
  {
    week: 35,
    titleEn: 'SCA, secrets scanning, supply chain',
    titleUk: 'SCA, secrets scanning, supply chain',
    topicsEn: 'Dependency scanning: Snyk, Dependabot, OSV-Scanner. CVE severity levels. SBOM (CycloneDX, SPDX). Secrets: gitleaks, trufflehog. Supply chain: SLSA framework, dependency confusion, typosquatting.',
    topicsUk: 'Dependency scanning: Snyk, Dependabot, OSV-Scanner. Рівні критичності CVE. SBOM (CycloneDX, SPDX). Secrets: gitleaks, trufflehog. Supply chain: SLSA framework, dependency confusion, typosquatting.',
    artifactEn: 'Full security pipeline in GitHub Actions for a test project: SAST + SCA + secrets + SBOM on every PR',
    artifactUk: 'Повний security-пайплайн в GitHub Actions для тестового проєкту: SAST + SCA + secrets + SBOM на кожний PR',
    hours: 8,
    resources: [
      { name: 'Snyk', url: 'https://snyk.io/' },
      { name: 'OSV-Scanner', url: 'https://github.com/google/osv-scanner' },
      { name: 'gitleaks', url: 'https://github.com/gitleaks/gitleaks' },
      { name: 'trufflehog', url: 'https://github.com/trufflesecurity/trufflehog' },
      { name: 'CycloneDX', url: 'https://cyclonedx.org/' },
      { name: 'SPDX', url: 'https://spdx.dev/' },
      { name: 'SLSA', url: 'https://slsa.dev/' },
    ],
  },
  {
    week: 36,
    titleEn: 'DAST and runtime security testing',
    titleUk: 'DAST і runtime security testing',
    topicsEn: 'OWASP ZAP in automated mode. Burp Enterprise. Differences with PortSwigger Pro. Authenticated DAST. IAST concept. Fuzz testing.',
    topicsUk: 'OWASP ZAP в автоматизованому режимі. Burp Enterprise. Відмінності від PortSwigger Pro. Authenticated DAST. Концепція IAST. Fuzz testing.',
    artifactEn: 'ZAP automation framework integrated into CI for a test application. Configuration for authenticated scanning',
    artifactUk: 'ZAP automation framework, інтегрований в CI для тестового застосунку. Конфігурація для аутентифікованого сканування',
    hours: 7,
    resources: [
      { name: 'OWASP ZAP', url: 'https://www.zaproxy.org/' },
    ],
  },
  // Month 10
  {
    week: 37,
    titleEn: 'Secure code review: methodology',
    titleUk: 'Secure code review: методологія',
    topicsEn: 'Approach to reading someone else\'s code. Where to start (entry points, authentication, data handling). Cognitive load: splitting into sessions. Using AI assistants carefully.',
    topicsUk: 'Підхід до читання чужого коду. З чого починати (entry points, автентифікація, обробка даних). Когнітивне навантаження: розбиття на сесії. Використання AI-асистентів обережно.',
    artifactEn: 'Personal code review checklist (own, not copied). Security-focused review of one PR in an open-source project',
    artifactUk: 'Власний checklist для code review (свій, не скопійований). Review одного PR в open-source з фокусом на security',
    hours: 6,
    resources: [
      { name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/' },
    ],
  },
  {
    week: 38,
    titleEn: 'Code review: Python and Node.js',
    titleUk: 'Code review: Python і Node.js',
    topicsEn: 'Typical vulnerability patterns in Express, FastAPI, Django. Dangerous functions: eval, exec, subprocess.shell=True. ORM injection. Template injection (Jinja2, Handlebars).',
    topicsUk: 'Типові паттерни вразливостей в Express, FastAPI, Django. Небезпечні функції: eval, exec, subprocess.shell=True. ORM injection. Template injection (Jinja2, Handlebars).',
    artifactEn: 'Written analysis of 5 CVEs in popular npm/pip packages from the last year: what was in the patch, how it was found',
    artifactUk: 'Письмовий розбір 5 CVE у популярних npm/pip пакетах за останній рік: що було в патчі, як знайшли',
    hours: 7,
    resources: [
      { name: 'GitHub Advisories', url: 'https://github.com/advisories' },
      { name: 'Project Zero blog', url: 'https://googleprojectzero.blogspot.com/' },
    ],
  },
  {
    week: 39,
    titleEn: 'Code review: Go and Java',
    titleUk: 'Code review: Go та Java',
    topicsEn: 'Go: concurrency bugs, improper error handling, unsafe package. Java: deserialization (Spring), XXE, SSRF in HttpClient. Spring Security misconfigurations.',
    topicsUk: 'Go: concurrency-баги, неправильна обробка помилок, unsafe пакет. Java: deserialization (Spring), XXE, SSRF в HttpClient. Spring Security misconfigurations.',
    artifactEn: 'Analysis of 3 CVEs from Spring Framework and 2 from popular Go projects with PoC',
    artifactUk: 'Розбір 3 CVE зі Spring Framework і 2 з популярних Go-проєктів з PoC',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'Spring Security', url: 'https://spring.io/security' },
    ],
  },
  {
    week: 40,
    titleEn: 'Bug bounty: first reports',
    titleUk: 'Bug bounty: перші звіти',
    topicsEn: 'Choosing a program (public, low noise, clear scope). Recon basics: amass, subfinder, httpx. Documentation. Coordinated disclosure ethics.',
    topicsUk: 'Вибір програми (public, низький рівень шуму, чіткий scope). Recon basics: amass, subfinder, httpx. Документування. Coordinated disclosure етика.',
    artifactEn: 'At least 2 reports to bug bounty programs (HackerOne or Bugcrowd) — even informational counts as experience',
    artifactUk: 'Мінімум 2 звіти в bug bounty програми (HackerOne або Bugcrowd) — навіть informational зараховується як досвід',
    hours: 8,
    advanced: true,
    resources: [
      { name: 'HackerOne', url: 'https://www.hackerone.com/' },
      { name: 'Bugcrowd', url: 'https://www.bugcrowd.com/' },
      { name: 'subfinder', url: 'https://github.com/projectdiscovery/subfinder' },
      { name: 'httpx', url: 'https://github.com/projectdiscovery/httpx' },
      { name: 'amass', url: 'https://github.com/owasp-amass/amass' },
    ],
  },
  // Month 11
  {
    week: 41,
    titleEn: 'Cloud security: AWS IAM',
    titleUk: 'Cloud security: AWS IAM',
    topicsEn: 'IAM users, roles, policies. Trust policies vs permissions policies. AssumeRole. Confused deputy. Service Control Policies. Least privilege in practice.',
    topicsUk: 'IAM users, roles, policies. Trust policies vs permissions policies. AssumeRole. Confused deputy. Service Control Policies. Least privilege на практиці.',
    artifactEn: 'Complete flaws.cloud (all 6 levels). Summary of typical IAM mistakes',
    artifactUk: 'Проходження flaws.cloud (всі 6 рівнів). Конспект з типовими IAM-помилками',
    hours: 7,
    resources: [
      { name: 'flaws.cloud', url: 'http://flaws.cloud/' },
      { name: 'AWS IAM Guide', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html' },
    ],
  },
  {
    week: 42,
    titleEn: 'Cloud security: networking and data',
    titleUk: 'Cloud security: мережі та дані',
    topicsEn: 'VPC, subnets, security groups, NACL. Private endpoints and VPC endpoints. S3 misconfigurations: public buckets, ACLs vs policies, presigned URLs. KMS and encryption at-rest.',
    topicsUk: 'VPC, subnets, security groups, NACL. Private endpoints і VPC endpoints. S3 misconfigurations: public buckets, ACLs vs policies, presigned URLs. KMS і шифрування at-rest.',
    artifactEn: 'Complete flaws2.cloud (attacker and defender tracks). Terraform setup for a secure-by-default S3 bucket',
    artifactUk: 'Проходження flaws2.cloud (attacker і defender tracks). Terraform setup для secure-by-default S3 bucket',
    hours: 8,
    resources: [
      { name: 'flaws2.cloud', url: 'http://flaws2.cloud/' },
      { name: 'Terraform', url: 'https://developer.hashicorp.com/terraform' },
      { name: 'AWS Security Pillar', url: 'https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html' },
    ],
  },
  {
    week: 43,
    titleEn: 'Container and Kubernetes security',
    titleUk: 'Container та Kubernetes security',
    topicsEn: 'Docker image scanning (Trivy, Grype). Dockerfile best practices. Kubernetes RBAC. Pod Security Standards. Network policies. Secrets in k8s and External Secrets Operator.',
    topicsUk: 'Docker image scanning (Trivy, Grype). Best practices Dockerfile. Kubernetes RBAC. Pod Security Standards. Network policies. Secrets в k8s і External Secrets Operator.',
    artifactEn: 'Audit of kind/minikube cluster configuration via kube-bench and kubescape. Written remediation plan',
    artifactUk: 'Аудит конфігурації kind/minikube-кластера через kube-bench і kubescape. Письмовий план remediation',
    hours: 7,
    advanced: true,
    resources: [
      { name: 'Trivy', url: 'https://trivy.dev/' },
      { name: 'Grype', url: 'https://github.com/anchore/grype' },
      { name: 'kube-bench', url: 'https://github.com/aquasecurity/kube-bench' },
      { name: 'Kubescape', url: 'https://kubescape.io/' },
    ],
  },
  {
    week: 44,
    titleEn: 'Detection, logging, incident response',
    titleUk: 'Детекція, логування, incident response',
    topicsEn: 'CloudTrail, GuardDuty, Security Hub in AWS. What to log in the application and how to structure it. SIEM concept. Incident response basics: NIST 800-61 phases.',
    topicsUk: 'CloudTrail, GuardDuty, Security Hub в AWS. Що логувати в застосунку і як структурувати. Концепція SIEM. Incident response basics: NIST 800-61 фази.',
    artifactEn: 'Structured logging added to one of the training projects. Runbook for one incident type (e.g. API key leak)',
    artifactUk: 'Структуроване логування додано до одного з навчальних проєктів. Runbook для одного типу інциденту (наприклад, витік API-ключа)',
    hours: 7,
    resources: [
      { name: 'AWS CloudTrail', url: 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html' },
      { name: 'AWS GuardDuty', url: 'https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html' },
      { name: 'NIST 800-61r2', url: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' },
    ],
  },
  // ─── PHASE 4: PROFESSIONAL DEVELOPMENT ─────────────────────────────
  // Month 12
  {
    week: 45,
    titleEn: 'GitHub portfolio',
    titleUk: 'Портфоліо на GitHub',
    topicsEn: 'Clean up and polish 5–7 key training projects. README with clear descriptions. Demo videos or GIFs where appropriate. Pinning relevant repositories.',
    topicsUk: 'Очистка та оформлення 5–7 ключових навчальних проєктів. README з зрозумілим описом. Демонстраційні відео або GIF де доречно. Pinning релевантних репозиторіїв.',
    artifactEn: 'Ready GitHub profile with pinned repos: minimum 1 security tool, 1 vulnerability research write-up, 1 CTF solution, 1 OSS contribution',
    artifactUk: 'Готовий GitHub-профіль з pinned repos: мінімум 1 security tool, 1 vulnerability research write-up, 1 CTF solution, 1 contribution в OSS',
    hours: 6,
    resources: [
      { name: 'GitHub Pages', url: 'https://pages.github.com/' },
    ],
  },
  {
    week: 46,
    titleEn: 'Technical blog and publications',
    titleUk: 'Технічний блог і публікації',
    topicsEn: 'Launch a personal blog (Hashnode, Medium, or static on GitHub Pages). Structure of a good technical post. SEO for technical writers.',
    topicsUk: 'Запуск персонального блогу (Hashnode, Medium або статика на GitHub Pages). Структура хорошого тех-посту. SEO для технічних авторів.',
    artifactEn: 'At least 2 published articles: one about a found vulnerability (can be training), one analyzing a CVE or security tool',
    artifactUk: 'Мінімум 2 опубліковані статті: одна про знайдену вразливість (може бути навчальна), одна з розбором CVE або security-інструменту',
    hours: 6,
    resources: [
      { name: 'Hashnode', url: 'https://hashnode.com/' },
      { name: 'Medium', url: 'https://medium.com/' },
    ],
  },
  {
    week: 47,
    titleEn: 'Resume, LinkedIn, networking',
    titleUk: 'Резюме, LinkedIn, нетворкінг',
    topicsEn: 'AppSec engineer resume: what to emphasize from QA experience, what to put first. LinkedIn profile. Participating in local communities (OWASP chapter, defcon group).',
    topicsUk: 'Резюме AppSec-інженера: що підкреслити з QA-досвіду, що винести вперед. LinkedIn-профіль. Участь у локальних ком\'юніті (OWASP chapter, defcon group).',
    artifactEn: 'Ready resume in English and Ukrainian. Updated LinkedIn. At least 5 targeted messages to recruiters/managers',
    artifactUk: 'Готове резюме українською та англійською. Оновлений LinkedIn. Мінімум 5 цільових повідомлень рекрутерам/менеджерам',
    hours: 6,
    resources: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/' },
      { name: 'OWASP Community', url: 'https://owasp.org/www-community/' },
    ],
  },
  {
    week: 48,
    titleEn: 'Interview preparation',
    titleUk: 'Підготовка до інтерв\'ю',
    topicsEn: 'Typical AppSec interview sections: web vulnerabilities deep-dive, threat modeling exercise, live code review, system design with security focus, behavioral questions.',
    topicsUk: 'Типові секції AppSec-інтерв\'ю: web vulnerabilities deep-dive, threat modeling exercise, code review live, system design з security-фокусом, поведінкові запитання.',
    artifactEn: 'At least 3 mock interviews (with friends, Pramp, or AI). Written analysis of weak points and plan to address them',
    artifactUk: 'Мінімум 3 mock interview (з друзями, на Pramp або з AI). Письмовий аналіз слабких місць і план їх закриття',
    hours: 7,
    resources: [
      { name: 'BSCP Certification', url: 'https://portswigger.net/web-security/certification' },
      { name: 'TCM PNPT', url: 'https://certifications.tcm-sec.com/pnpt/' },
      { name: 'OffSec OSCP', url: 'https://www.offsec.com/courses/pen-200/' },
    ],
  },
];

export function getWeeksForMonth(month: number): Week[] {
  const start = (month - 1) * 4;
  return WEEKS_DATA.slice(start, start + 4);
}

export function getWeeksForPhase(phase: number): Week[] {
  const start = (phase - 1) * 12;
  return WEEKS_DATA.slice(start, start + 12);
}
