/**
 * Passport Configuration
 * Google OAuth2 Strategy
 */

import passport from 'passport';
import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
import { pool } from './database.js';
import { User } from '../types/index.js';

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || '';
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || '';
const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL || 'http://localhost:3001/api/auth/google/callback';

// Configure Google OAuth2 Strategy
passport.use(
  new GoogleStrategy(
    {
      clientID: GOOGLE_CLIENT_ID,
      clientSecret: GOOGLE_CLIENT_SECRET,
      callbackURL: GOOGLE_CALLBACK_URL,
      scope: ['profile', 'email'],
    },
    async (accessToken, refreshToken, profile, done) => {
      try {
        // Extract user info from Google profile
        const googleId = profile.id;
        const email = profile.emails?.[0]?.value;
        const name = profile.displayName;

        if (!email) {
          return done(new Error('No email found in Google profile'), undefined);
        }

        // Check if user exists by Google ID
        let result = await pool.query(
          'SELECT * FROM users WHERE google_id = $1',
          [googleId]
        );

        let user: User;

        if (result.rows.length > 0) {
          // User exists with this Google ID - return existing user
          user = result.rows[0];
          console.log(`✓ Existing Google user logged in: ${email}`);
        } else {
          // Check if user exists with this email (from password registration)
          result = await pool.query(
            'SELECT * FROM users WHERE email = $1',
            [email]
          );

          if (result.rows.length > 0) {
            // User exists with email but no Google ID - link accounts
            user = result.rows[0];

            // Link Google account to existing user
            await pool.query(
              'UPDATE users SET google_id = $1, email_verified = TRUE, updated_at = NOW() WHERE id = $2',
              [googleId, user.id]
            );

            console.log(`✓ Linked Google account to existing user: ${email}`);
          } else {
            // Create new user with Google account
            // UUID is auto-generated by database (gen_random_uuid())
            result = await pool.query(
              `INSERT INTO users (email, name, google_id, role, email_verified)
               VALUES ($1, $2, $3, 'user', TRUE)
               RETURNING *`,
              [email, name, googleId]
            );

            user = result.rows[0];
            console.log(`✓ New Google user registered: ${email} (UID: ${user.id})`);
          }
        }

        // Return user object
        return done(null, user);
      } catch (error) {
        console.error('❌ Google OAuth error:', error);
        return done(error as Error, undefined);
      }
    }
  )
);

// Serialize user for session (if using sessions)
passport.serializeUser((user: any, done) => {
  done(null, user.id);
});

// Deserialize user from session
passport.deserializeUser(async (id: string, done) => {
  try {
    const result = await pool.query('SELECT * FROM users WHERE id = $1', [id]);
    done(null, result.rows[0]);
  } catch (error) {
    done(error, null);
  }
});

export default passport;
