# WireGuard config for stage server (gate.lexapp.co.ua)
# Node: gate.lexapp.co.ua
# WG IP: 10.149.22.10/32
# Managed by: wg-quick@wg1 (systemctl enable wg-quick@wg1)
# Config location: /etc/wireguard/wg1.conf

[Interface]
ListenPort = 55609
Address = 10.149.22.10/32
PrivateKey = <STAGE_PRIVATE_KEY>

[Peer]
# mail.legal.org.ua (mail server)
PublicKey = uVgiZmmN7AlHl+OJ10VllhhoWN1HHG4/POKn9MM+M1o=
AllowedIPs = 10.149.22.1/32
Endpoint = 178.162.234.145:51820
PersistentKeepalive = 25

[Peer]
# localdev.legal.org.ua (developer machine)
PublicKey = 5l/HsPNNxbD6mvpKWJkDq589+V5aGH3Nch1ATG9BIXI=
AllowedIPs = 10.149.22.181/32
Endpoint = 134.249.53.181:44082
